r"""The general stabilizer code object.

A stabilizer code is a set of commuting Pauli rows ``S \subseteq F_2^{2n}``
together with a symplectically paired logical basis completing ``S`` inside
its own centraliser.  This module owns the *representation* only; every gate
ansatz and solver lives in :mod:`qec_transversal.ansatz`.
"""

from __future__ import annotations

import numpy as np

from ..utils.gf2 import (
    as_binary_matrix,
    nullspace,
    quotient_complement,
    row_basis,
    rref,
)
from ..utils.symplectic import symplectic_gram_schmidt, symplectic_product


class StabilizerCode:
    """A general stabilizer code given by symplectic rows ``(X | Z)``."""

    def __init__(self, h: object):
        matrix = as_binary_matrix(h)
        if matrix.shape[1] % 2 != 0:
            raise ValueError("stabilizer rows must have even width (X | Z)")
        self.n = matrix.shape[1] // 2
        if symplectic_product(matrix, matrix, qubits=self.n).any():
            raise ValueError("stabilizer generators do not commute")
        self.h = row_basis(matrix, ncols=2 * self.n)
        self.rank = self.h.shape[0]
        self.k = self.n - self.rank
        self._h_rref = rref(self.h)

        # normalizer = symplectic kernel of h; logicals complete h inside it.
        # Kept on the object: the preservation algebra needs it too, since the
        # sigma-stable algebra is A(S) cap A(N) (see algebra.preservation).
        swapped = np.hstack([self.h[:, self.n :], self.h[:, : self.n]])
        self.normalizer = row_basis(nullspace(swapped), ncols=2 * self.n)
        normalizer = self.normalizer
        representatives = quotient_complement(normalizer, self.h)
        if representatives.shape[0] != 2 * self.k:
            raise AssertionError("internal error: logical space has wrong dimension")
        if self.k:
            a_rows, b_rows = symplectic_gram_schmidt(representatives, self.n)
            self.logical = np.vstack([a_rows, b_rows])
        else:
            self.logical = np.zeros((0, 2 * self.n), dtype=np.uint8)


def tensor_product(codes: "list[StabilizerCode]") -> StabilizerCode:
    r"""The joint code of several blocks side by side.

    Block ``b`` occupies qubits ``[b*n_b, (b+1)*n_b)`` of the concatenated
    register, and the joint stabilizer is generated by each block's rows padded
    with zeros elsewhere.  Parameters add: ``n = sum n_b``, ``k = sum k_b``.

    This is the entry point for gates *across* code blocks -- transversal
    CNOT and friends.  Pair it with the corresponding-qubit partition from
    :func:`corresponding_qubit_cells`, and the ordinary prescribed-partition
    machinery applies unchanged: an ``l``-block transversal gate is exactly a
    depth-one layer whose cells each hold one qubit from every block.

    Caveat worth stating: the joint logical basis is built by the usual
    symplectic Gram-Schmidt pass, so it need not be the "block ``b``'s logical
    qubit ``j``" basis.  Group orders are basis-independent, but if you want to
    *read* a logical matrix as a two-block gate, transport it into the product
    basis first.
    """

    if not codes:
        raise ValueError("need at least one block")
    total = sum(code.n for code in codes)
    rows = []
    offset = 0
    for code in codes:
        for row in code.h:
            padded = np.zeros(2 * total, dtype=np.uint8)
            padded[offset : offset + code.n] = row[: code.n]
            padded[total + offset : total + offset + code.n] = row[code.n :]
            rows.append(padded)
        offset += code.n
    if not rows:
        raise ValueError("the joint code has no stabilizer generators")
    return StabilizerCode(np.asarray(rows, dtype=np.uint8))


def tensor_power(code: StabilizerCode, blocks: int) -> StabilizerCode:
    """``blocks`` identical copies of ``code`` side by side."""

    if blocks < 1:
        raise ValueError("blocks must be positive")
    return tensor_product([code] * blocks)


def corresponding_qubit_cells(qubits: int, blocks: int) -> list[tuple[int, ...]]:
    """Cells pairing qubit ``i`` of every block: ``{i, n+i, 2n+i, ...}``.

    The partition that turns the prescribed-partition solver into an
    ``blocks``-fold *transversal* solver.  Each cell has ``blocks`` qubits, so
    the per-cell group is ``Sp(2 * blocks, 2)``.
    """

    if qubits % blocks:
        raise ValueError("the register does not split into equal blocks")
    per_block = qubits // blocks
    return [
        tuple(block * per_block + index for block in range(blocks))
        for index in range(per_block)
    ]


def five_qubit_code() -> StabilizerCode:
    """The ``[[5,1,3]]`` perfect code — the canonical non-CSS example."""

    rows = np.zeros((4, 10), dtype=np.uint8)
    paulis = ["XZZXI", "IXZZX", "XIXZZ", "ZXIXZ"]
    for r, word in enumerate(paulis):
        for q, letter in enumerate(word):
            if letter in ("X", "Y"):
                rows[r, q] = 1
            if letter in ("Z", "Y"):
                rows[r, 5 + q] = 1
    return StabilizerCode(rows)
