"""Witness export + independent checker round-trip and mutation tests."""

import copy
import json
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

from qec_transversal import REGISTRY, CSSCode
from qec_transversal.stabilizer import (
    StabilizerCode,
    analyze_local_clifford,
    five_qubit_code,
)
from qec_transversal.witness import export_stabilizer_witness, export_strict_witness

CHECKER = Path(__file__).resolve().parent.parent / "tools" / "check_witness.py"
STABILIZER_CHECKER = (
    Path(__file__).resolve().parent.parent / "tools" / "check_stabilizer_witness.py"
)


def _run_checker(checker, document, tmp_path) -> bool:
    path = tmp_path / "w.json"
    path.write_text(json.dumps(document))
    result = subprocess.run(
        [sys.executable, str(checker), str(path)],
        capture_output=True, text=True, check=False,
    )
    return result.returncode == 0


def _check(document, tmp_path) -> bool:
    return _run_checker(CHECKER, document, tmp_path)


def _check_stabilizer(document, tmp_path) -> bool:
    return _run_checker(STABILIZER_CHECKER, document, tmp_path)


@pytest.mark.parametrize("name", ["steane", "qrm15", "c4-22", "toric-4", "bb72"])
def test_witness_round_trip_passes_independent_checker(name, tmp_path) -> None:
    document = export_strict_witness(CSSCode(*REGISTRY[name].build()), name)
    assert _check(document, tmp_path)


def test_every_registry_code_ships_a_published_witness() -> None:
    """The zoo page claims a machine-checkable witness for every strict verdict.

    Nothing in the sweep exports these automatically, so adding a registry code
    used to leave the claim quietly false (it drifted to 42 of 55 before this
    guard existed).  Regenerate a missing one with::

        export_strict_witness(CSSCode(*REGISTRY[name].build()), name)
        write_witness(document, f"docs/zoo/witnesses/{name}.json.gz")
    """

    published = Path(__file__).resolve().parent.parent / "docs" / "zoo" / "witnesses"
    missing = sorted(
        name for name in REGISTRY if not (published / f"{name}.json.gz").exists()
    )
    assert not missing, f"registry codes without a published witness: {missing}"


def test_checker_catches_mutations(tmp_path) -> None:
    base = export_strict_witness(CSSCode(*REGISTRY["steane"].build()), "steane")

    mutations = []
    m = copy.deepcopy(base); m["A_Z"]["kernel"] = ["1111110"]; mutations.append(m)
    m = copy.deepcopy(base); m["A_Z"]["kernel"].append("1010101"); mutations.append(m)
    m = copy.deepcopy(base); m["A_Z"]["constraints"] = m["A_Z"]["constraints"][:2]; mutations.append(m)
    m = copy.deepcopy(base); m["A_Z"]["constraints"][0]["dual"] = "1000000"; mutations.append(m)
    m = copy.deepcopy(base); m["generators"][0]["logical"] = ["10", "01"]; mutations.append(m)
    m = copy.deepcopy(base); m["logical_group"]["order"] = 12; mutations.append(m)
    m = copy.deepcopy(base); m["logical_group"]["elements"] = m["logical_group"]["elements"][:3]; mutations.append(m)
    m = copy.deepcopy(base); m["logical_X"] = ["1000000"]; mutations.append(m)

    for index, mutated in enumerate(mutations):
        assert not _check(mutated, tmp_path), f"mutation {index} not caught"


def _steane_stabilizer_code() -> StabilizerCode:
    css = CSSCode(*REGISTRY["steane"].build())
    h = np.vstack(
        [
            np.hstack([css.c_x, np.zeros_like(css.c_x)]),
            np.hstack([np.zeros_like(css.c_z), css.c_z]),
        ]
    )
    return StabilizerCode(h)


def _logical_closure_order(document) -> int:
    k = document["k"]
    identity = np.eye(2 * k, dtype=np.uint8)
    elements = {identity.tobytes(): identity}
    queue = [identity]
    logicals = [
        np.array([[int(v) for v in row] for row in g["logical"]], dtype=np.uint8)
        for g in document["generators"]
    ]
    while queue:
        element = queue.pop()
        for g in logicals:
            product = (element @ g) % 2
            key = product.tobytes()
            if key not in elements:
                elements[key] = product
                queue.append(product)
    return len(elements)


def test_stabilizer_witness_round_trip_five_qubit(tmp_path) -> None:
    code = five_qubit_code()
    document = export_stabilizer_witness(code, analyze_local_clifford(code), "five-qubit")
    assert _check_stabilizer(document, tmp_path)


def test_stabilizer_witness_css_code_cross_checks_group_order(tmp_path) -> None:
    code = _steane_stabilizer_code()
    document = export_stabilizer_witness(code, analyze_local_clifford(code), "steane-stab")
    assert _check_stabilizer(document, tmp_path)
    # cross-check: the logical group generated by the stabilizer-route
    # witness must match the CSS witness's logical group (Albert's theorem)
    css_witness = export_strict_witness(CSSCode(*REGISTRY["steane"].build()), "steane")
    assert _logical_closure_order(document) == css_witness["logical_group"]["order"]


def test_stabilizer_checker_catches_mutations(tmp_path) -> None:
    code = five_qubit_code()
    base = export_stabilizer_witness(code, analyze_local_clifford(code), "five-qubit")
    n = base["n"]
    identity = "1001" * n

    mutations = []
    m = copy.deepcopy(base); m["algebra"]["basis"].append("1" + "0" * (4 * n - 1)); mutations.append(m)
    m = copy.deepcopy(base); m["algebra"]["constraints"] = m["algebra"]["constraints"][:2]; mutations.append(m)
    m = copy.deepcopy(base); m["algebra"]["constraints"][0]["dual"] = "1" + "0" * (2 * n - 1); mutations.append(m)
    m = copy.deepcopy(base)
    dropped = next(e for e in m["group"]["elements"] if e != identity)
    m["group"]["elements"] = [e for e in m["group"]["elements"] if e != dropped]
    m["group"]["order"] = len(m["group"]["elements"])
    mutations.append(m)
    m = copy.deepcopy(base); m["group"]["order"] = 12; mutations.append(m)
    m = copy.deepcopy(base); m["generators"][0]["logical"] = ["10", "01"]; mutations.append(m)
    m = copy.deepcopy(base)
    m["group"]["elements"].append("0" * (4 * n))  # in span, but not a unit
    m["group"]["order"] = len(m["group"]["elements"])
    mutations.append(m)

    for index, mutated in enumerate(mutations):
        assert not _check_stabilizer(mutated, tmp_path), f"mutation {index} not caught"
