"""Cross-validation between independent solvers.

Each test here computes the *same mathematical object* by two routes that share
no code path, and asserts they agree.  These are the tests that would catch a
refactor silently changing a convention: the specialised CSS solvers know
nothing about preservation algebras, the general solver knows nothing about
shears, and brute force knows nothing about either.

Invariants covered:

* CSS shear solver == general preservation-algebra solver, physically and
  logically, on every CSS code where both apply;
* singleton-cell ``partition_clifford_group`` == ``strict_transversal_clifford``;
* the structured unit-group route == the ``2^dim`` enumeration route;
* every generator returned by any backend really preserves the code, its
  logical action re-derives independently, and that action is symplectic;
* an exhausted budget reports ``UNKNOWN`` with no group order, never a small
  number.
"""

import itertools

import numpy as np
import pytest

from qec_transversal import (
    REGISTRY,
    Completeness,
    CSSCode,
    StabilizerCode,
    five_qubit_code,
    partition_clifford_group,
    strict_transversal_clifford,
)
from qec_transversal.algebra.preservation import _SL22, _block_action_matrix
from qec_transversal.ansatz.strict_css import shear_matrix
from qec_transversal.logical.group import generated_group_order
from qec_transversal.utils.gf2 import (
    gf2_inverse,
    gf2_matmul,
    rank,
    reduce_rows,
    rowspace_residues,
    rref,
)
from qec_transversal.utils.symplectic import is_symplectic, symplectic_product

#: CSS codes small enough for the general route's 2^dim enumeration and for
#: dense physical-group closure.
SMALL_CSS = ["steane", "c4-22", "c6-22", "qrm15", "toric-4", "surface-5", "cube-832"]


def _stacked(css: CSSCode) -> StabilizerCode:
    return css.to_stabilizer_code()


def _random_css(rng, n, rows):
    """A random CSS pair with ``H_X H_Z^T = 0``."""

    h_x = rng.integers(0, 2, size=(rows, n), dtype=np.uint8)
    from qec_transversal.utils.gf2 import nullspace

    perp = nullspace(h_x)
    if perp.shape[0] == 0:
        return None
    picks = rng.integers(0, 2, size=(rows, perp.shape[0]), dtype=np.uint8)
    h_z = gf2_matmul(picks, perp)
    return h_x, h_z


def _closure(k: int, generators) -> set:
    """Every element of the group generated by ``generators``, as bytes keys."""

    identity = np.eye(2 * k, dtype=np.uint8)
    seen = {identity.tobytes()}
    frontier = [identity]
    while frontier:
        current = frontier.pop()
        for generator in generators:
            product = gf2_matmul(current, generator)
            if product.tobytes() not in seen:
                seen.add(product.tobytes())
                frontier.append(product)
    return seen


def _logical_change_of_basis(css: CSSCode) -> np.ndarray:
    r"""``T`` with ``L_stabilizer = T L_css`` in ``S^\perp / S``.

    The two code objects choose different representatives of the logical Pauli
    basis, so a physical gate's logical matrix ``A`` in the stabilizer basis is
    ``T^{-1} A T`` in the CSS basis.
    """

    from qec_transversal.utils.gf2 import coordinates_over

    stabilizer = css.to_stabilizer_code()
    ambient = np.vstack([css.logical, css.stabilizer])
    rows = []
    for row in stabilizer.logical:
        coefficients = coordinates_over(ambient, row)
        assert coefficients is not None, "logical row outside the normalizer span"
        rows.append(coefficients[: 2 * css.k])
    return np.asarray(rows, dtype=np.uint8)


def _random_stabilizer(rng, n, m):
    rows = np.zeros((0, 2 * n), dtype=np.uint8)
    tries = 0
    while rows.shape[0] < m and tries < 200:
        tries += 1
        candidate = rng.integers(0, 2, size=2 * n, dtype=np.uint8)
        if not candidate.any():
            continue
        if rows.shape[0] and symplectic_product(rows, candidate[None, :], qubits=n).any():
            continue
        stacked = np.vstack([rows, candidate])
        if rank(stacked) > rows.shape[0]:
            rows = stacked
    return rows


# ---------------------------------------------------------------------------
# 1. specialised CSS solver vs the general preservation-algebra solver
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", SMALL_CSS)
def test_css_and_general_strict_solvers_agree(name: str) -> None:
    """Two independent computations of the strict-transversal group.

    The CSS route solves two GF(2) kernels for the diagonal shear families and
    invokes Albert's structure theorem to claim they generate everything.  The
    general route builds the singleton preservation algebra and takes its unit
    group, with no notion of a shear.  Both must be COMPLETE, must induce the
    same logical group, and -- checked here explicitly -- the physical group
    generated by the CSS shear layers must have exactly the order the general
    route reports.
    """

    css = CSSCode(*REGISTRY[name].build())
    specialised = strict_transversal_clifford(css, method="css")
    general = strict_transversal_clifford(css, method="general")

    assert specialised.completeness is Completeness.COMPLETE
    assert general.completeness is Completeness.COMPLETE
    assert specialised.logical_group_order == general.logical_group_order
    assert specialised.logical_group_order_is_exact
    assert general.logical_group_order_is_exact

    # The two engines build their paired logical bases by different
    # constructions, so their logical matrices are conjugate rather than
    # equal.  Transport the general route's group into the CSS basis and then
    # demand equality as SETS -- a much stronger statement than equal orders.
    if css.k:
        change = _logical_change_of_basis(css)
        change_inverse = gf2_inverse(change)
        transported = [
            gf2_matmul(gf2_matmul(change_inverse, matrix), change)
            for matrix in general.logical_generators
        ]
        assert _closure(css.k, list(specialised.logical_generators)) == _closure(
            css.k, transported
        )

    # physical side: close the CSS shear layers as dense 2n x 2n matrices
    analysis = specialised.analysis
    shears = [
        shear_matrix(g.family, g.parameter)
        for g in analysis.generators
    ]
    shears = [m for m in shears if not np.array_equal(m, np.eye(2 * css.n, dtype=np.uint8))]
    closure = generated_group_order(shears, cap=200_000)
    assert closure.exact
    assert closure.order == general.group_order


def test_general_strict_solver_matches_brute_force_on_small_codes() -> None:
    """Exact algebra vs exhaustive enumeration of all 6^n Clifford assignments.

    Covers CSS and non-CSS codes together, including the [[5,1,3]] perfect
    code, whose strict group is the order-3 cyclic (SH)^{otimes 5}.
    """

    rng = np.random.default_rng(20260820)
    codes = [five_qubit_code()]
    for n in (2, 3, 4):
        for _ in range(3):
            rows = _random_stabilizer(rng, n, int(rng.integers(1, n + 1)))
            if rows.shape[0]:
                codes.append(StabilizerCode(rows))
    for name in ("steane", "c4-22"):
        codes.append(_stacked(CSSCode(*REGISTRY[name].build())))

    for code in codes:
        if code.n > 5:
            continue
        result = strict_transversal_clifford(code)
        assert result.completeness is Completeness.COMPLETE
        reduced, pivots = rref(code.h)
        want = 0
        for combo in itertools.product(range(6), repeat=code.n):
            entries = np.zeros(4 * code.n, dtype=np.uint8)
            for i, g in enumerate(combo):
                entries[4 * i : 4 * i + 4] = _SL22[g]
            matrix = _block_action_matrix(entries, code.n)
            if not reduce_rows(gf2_matmul(code.h, matrix), reduced, pivots).any():
                want += 1
        assert result.group_order == want, f"n={code.n}"


# ---------------------------------------------------------------------------
# 2. the partition framework specialises correctly
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", ["steane", "c4-22", "toric-4", "surface-5"])
def test_singleton_partition_reproduces_the_strict_group(name: str) -> None:
    """``GL(2,2) = Sp(2,2)``: at singleton cells the symplectic cut is free."""

    code = _stacked(CSSCode(*REGISTRY[name].build()))
    singletons = [(q,) for q in range(code.n)]
    partition = partition_clifford_group(code, singletons, method="enumeration")
    strict = strict_transversal_clifford(code, method="general")
    assert partition.completeness is Completeness.COMPLETE
    assert strict.completeness is Completeness.COMPLETE
    assert partition.group_order == strict.group_order
    assert partition.logical_group_order == strict.logical_group_order


@pytest.mark.parametrize(
    "name,cells",
    [
        ("steane", [(0, 1), (2, 3), (4, 5), (6,)]),
        ("c4-22", [(0, 1), (2, 3)]),
        ("c6-22", [(0, 1), (2, 3), (4, 5)]),
        ("iceberg-8", [(0, 1), (2, 3), (4, 5), (6, 7)]),
    ],
)
def test_structured_and_enumeration_partition_routes_are_consistent(name, cells) -> None:
    """The certified unit-group route and the ``2^dim`` sweep, side by side.

    Both routes may legitimately decline -- the algebra can outgrow the
    enumeration cap, and the unit group can outgrow the group-enumeration cap
    used for the symplectic cut.  What must hold unconditionally is that a
    decline is *honest* (``UNKNOWN`` with no order) and that when both routes
    finish they agree.
    """

    code = _stacked(CSSCode(*REGISTRY[name].build()))
    structured = partition_clifford_group(code, cells, method="structure")
    enumerated = partition_clifford_group(code, cells, method="enumeration")

    for result in (structured, enumerated):
        if result.completeness is Completeness.UNKNOWN:
            assert result.group_order is None
            assert result.logical_group_order is None

    if Completeness.UNKNOWN in (structured.completeness, enumerated.completeness):
        pytest.skip(f"{name}: a route declined honestly on this instance")
    assert structured.group_order == enumerated.group_order
    assert structured.logical_group_order == enumerated.logical_group_order


def test_structured_and_enumeration_partition_routes_agree_where_both_finish() -> None:
    """At least one instance must exercise the agreement, not just the skip."""

    for name, cells, want in (
        ("steane", [(0, 1), (2, 3), (4, 5), (6,)], 48),
        ("c4-22", [(0, 1), (2, 3)], 384),
    ):
        code = _stacked(CSSCode(*REGISTRY[name].build()))
        structured = partition_clifford_group(code, cells, method="structure")
        enumerated = partition_clifford_group(code, cells, method="enumeration")
        assert structured.completeness is Completeness.COMPLETE
        assert enumerated.completeness is Completeness.COMPLETE
        assert structured.group_order == enumerated.group_order == want
        assert structured.logical_group_order == enumerated.logical_group_order


def test_two_local_partition_strictly_contains_the_strict_group() -> None:
    """Coarsening the partition can only add gates, never remove them."""

    code = _stacked(CSSCode(*REGISTRY["c4-22"].build()))
    strict = partition_clifford_group(code, [(0,), (1,), (2,), (3,)])
    pairs = partition_clifford_group(code, [(0, 1), (2, 3)])
    assert strict.group_order == 6 and pairs.group_order == 384
    assert pairs.group_order % strict.group_order == 0  # Lagrange
    assert pairs.logical_group_order == 48
    assert strict.logical_group_order == 6


# ---------------------------------------------------------------------------
# 3. logical-action consistency, for every backend
# ---------------------------------------------------------------------------


def _recheck_stabilizer_generator(code: StabilizerCode, matrix: np.ndarray) -> np.ndarray:
    """Independently: preserve the stabilizer, re-derive the logical action.

    Deliberately does not call ``logical.action.project_to_logical`` -- this
    is the second opinion, written out longhand.
    """

    n = code.n
    assert is_symplectic(matrix, qubits=n), "physical matrix is not symplectic"
    image = gf2_matmul(code.h, matrix)
    assert not rowspace_residues(image, code.h).any(), "stabilizer not preserved"
    if code.k == 0:
        return np.zeros((0, 0), dtype=np.uint8)
    images = gf2_matmul(code.logical, matrix)
    action = np.zeros((2 * code.k, 2 * code.k), dtype=np.uint8)
    for row_index in range(2 * code.k):
        for j in range(code.k):
            action[row_index, j] = symplectic_product(
                images[row_index], code.logical[code.k + j], qubits=n
            )[0, 0]
            action[row_index, code.k + j] = symplectic_product(
                images[row_index], code.logical[j], qubits=n
            )[0, 0]
    residue = (images ^ gf2_matmul(action, code.logical)) & 1
    assert not rowspace_residues(residue, code.h).any(), "logical residue outside S"
    assert is_symplectic(action, qubits=code.k), "logical action is not symplectic"
    return action


@pytest.mark.parametrize("name", ["steane", "c4-22", "cube-832"])
def test_every_strict_generator_survives_an_independent_recheck(name: str) -> None:
    code = _stacked(CSSCode(*REGISTRY[name].build()))
    result = strict_transversal_clifford(code)
    assert result.generators
    for record in result.generators:
        entries = np.zeros(4 * code.n, dtype=np.uint8)
        for i, block in enumerate(record.blocks):
            entries[4 * i : 4 * i + 4] = block
        matrix = _block_action_matrix(entries, code.n)
        action = _recheck_stabilizer_generator(code, matrix)
        assert np.array_equal(action, record.logical_symplectic)


def _recheck_css_generator(css: CSSCode, matrix: np.ndarray) -> np.ndarray:
    """The same second opinion, in the CSS code's *own* logical basis.

    ``CSSCode`` and ``StabilizerCode`` build their paired logical bases by
    different constructions, so the induced logical matrices are conjugate but
    not equal; comparing a CSS generator's action against the general code
    object's basis would be a basis mismatch, not a disagreement.
    """

    n = css.n
    assert is_symplectic(matrix, qubits=n), "physical matrix is not symplectic"
    image = gf2_matmul(css.stabilizer, matrix)
    assert not rowspace_residues(image, css.stabilizer).any(), "stabilizer not preserved"
    if css.k == 0:
        return np.zeros((0, 0), dtype=np.uint8)
    images = gf2_matmul(css.logical, matrix)
    action = np.zeros((2 * css.k, 2 * css.k), dtype=np.uint8)
    for row_index in range(2 * css.k):
        for j in range(css.k):
            action[row_index, j] = symplectic_product(
                images[row_index], css.logical[css.k + j], qubits=n
            )[0, 0]
            action[row_index, css.k + j] = symplectic_product(
                images[row_index], css.logical[j], qubits=n
            )[0, 0]
    residue = (images ^ gf2_matmul(action, css.logical)) & 1
    assert not rowspace_residues(residue, css.stabilizer).any(), "residue outside S"
    assert is_symplectic(action, qubits=css.k), "logical action is not symplectic"
    return action


@pytest.mark.parametrize("name", ["steane", "qrm15", "grid-4x6", "c4-22", "tesseract"])
def test_every_css_shear_generator_survives_an_independent_recheck(name: str) -> None:
    css = CSSCode(*REGISTRY[name].build())
    result = strict_transversal_clifford(css, method="css")
    for record in result.generators:
        matrix = shear_matrix(record.family, record.parameter)
        action = _recheck_css_generator(css, matrix)
        assert np.array_equal(action, record.logical_symplectic)


def test_logical_generators_of_every_public_entry_point_are_symplectic() -> None:
    """Whatever a backend returns as a logical image must live in Sp(2k, 2)."""

    from qec_transversal import (
        diagonal_transversal_gates,
        matching_clifford_group,
        one_block_clifford_group,
    )

    css = CSSCode(*REGISTRY["steane"].build())
    results = [
        strict_transversal_clifford(css),
        strict_transversal_clifford(css, method="general"),
        partition_clifford_group(css, [(q,) for q in range(css.n)]),
        matching_clifford_group(css, np.arange(css.n)),
        diagonal_transversal_gates(css, level=3),
        one_block_clifford_group(css, name="steane", time_budget_s=20.0),
    ]
    for result in results:
        for matrix in result.logical_generators:
            assert is_symplectic(matrix, qubits=css.k), result.method


# ---------------------------------------------------------------------------
# 4. honest failure
# ---------------------------------------------------------------------------


def test_exhausted_budget_reports_unknown_not_a_small_group() -> None:
    """A capped computation must never look like a certified small answer."""

    code = _stacked(CSSCode(*REGISTRY["steane"].build()))
    starved = strict_transversal_clifford(code, method="general", dim_cap=0)
    if starved.completeness is Completeness.COMPLETE:
        # the structured route succeeded without enumeration; then it must be
        # right, not merely finished
        assert starved.group_order == strict_transversal_clifford(code).group_order
    else:
        assert starved.completeness is Completeness.UNKNOWN
        assert starved.group_order is None
        assert not starved.complete


def test_partition_structure_route_declines_rather_than_guesses() -> None:
    """``method='structure'`` must return UNKNOWN, never a partial count."""

    code = _stacked(CSSCode(*REGISTRY["steane"].build()))
    result = partition_clifford_group(
        code, [tuple(range(code.n))], method="structure"
    )
    assert result.completeness in (Completeness.COMPLETE, Completeness.UNKNOWN)
    if result.completeness is Completeness.UNKNOWN:
        assert result.group_order is None
