"""Certified unit-group solver tests: fuzz vs enumeration + integration."""

import numpy as np
import pytest

from qec_transversal import REGISTRY, CSSCode
from qec_transversal.gf2 import row_basis
from qec_transversal.stabilizer import (
    LocalCliffordAnalysis,
    StabilizerCode,
    analyze_local_clifford,
)
from qec_transversal.unitgroup import AlgebraF2, _char2_radical, unit_group


def _block_multiply(n):
    def mul(a, b):
        out = np.zeros(4 * n, dtype=np.uint8)
        for i in range(n):
            A = a[4 * i : 4 * i + 4].reshape(2, 2)
            B = b[4 * i : 4 * i + 4].reshape(2, 2)
            out[4 * i : 4 * i + 4] = (A @ B % 2).reshape(-1)
        return out

    return mul


def _identity_flat(n):
    v = np.zeros(4 * n, dtype=np.uint8)
    v[0::4] = 1
    v[3::4] = 1
    return v


def _random_closed_algebra(rng, n, n_gens):
    mul = _block_multiply(n)
    one = _identity_flat(n)
    gens = [one] + [rng.integers(0, 2, size=4 * n, dtype=np.uint8) for _ in range(n_gens)]
    basis = row_basis(np.asarray(gens, dtype=np.uint8), ncols=4 * n)
    for _ in range(4 * n + 1):  # closure stabilizes within dim steps
        products = [mul(a, b) for a in basis for b in basis]
        new = row_basis(
            np.vstack([basis] + [p[None, :] for p in products]), ncols=4 * n
        )
        if new.shape[0] == basis.shape[0]:
            return new, mul, one
        basis = new
    return None, mul, one


def _brute_unit_count(basis, dim, n):
    count = 0
    for mask in range(1 << dim):
        v = np.zeros(basis.shape[1], dtype=np.uint8)
        for b in range(dim):
            if (mask >> b) & 1:
                v ^= basis[b]
        if all(
            (int(v[4 * i]) & int(v[4 * i + 3])) ^ (int(v[4 * i + 1]) & int(v[4 * i + 2]))
            for i in range(n)
        ):
            count += 1
    return count


def _closure_size(algebra: AlgebraF2, generators) -> int:
    """Order of the group generated by unit-group coordinate generators."""

    rights = [algebra.right_matrix(g) for g in generators]
    seen = {algebra.one_coords.tobytes()}
    frontier = [algebra.one_coords]
    while frontier:
        current = frontier.pop()
        for matrix in rights:
            nxt = ((matrix @ current) % 2).astype(np.uint8)
            if nxt.tobytes() not in seen:
                seen.add(nxt.tobytes())
                frontier.append(nxt)
    return len(seen)


def test_unit_group_fuzz_never_wrong() -> None:
    rng = np.random.default_rng(2026)
    exact = failures = 0
    trials = 200
    for trial in range(trials):
        n = int(rng.integers(1, 4))
        basis, mul, one = _random_closed_algebra(rng, n, int(rng.integers(1, 3)))
        if basis is None:
            continue
        algebra = AlgebraF2(basis, mul, one)
        result = unit_group(algebra, seed=trial)
        if result.status != "exact":
            continue  # honest unknown is acceptable; wrong answers are not
        exact += 1
        if basis.shape[0] <= 11:
            want = _brute_unit_count(basis, basis.shape[0], n)
            if result.order != want:
                failures += 1
                continue
        # generation certificate: closure of generators is the full group
        if _closure_size(algebra, result.generators) != result.order:
            failures += 1
    assert failures == 0
    # the deterministic Cohen-Ivanyos-Wales radical makes the structured
    # route near-total on these algebras; unknowns must stay exceptional
    assert exact >= 190


def _adversarial_algebra() -> AlgebraF2:
    """``A = F_2*1 + N`` with ``N = span{x, y, z}``, ``xy = yx = z`` and all
    other products zero, presented in the adversarial flat basis
    ``e0 = 1, e1 = x, e2 = y+z, e3 = x+y``: the RREF radical basis is then
    ``{x, y+z, x+y}``, whose ``1 + basis`` elements generate only 4 of the
    8 elements of ``1 + N`` (``(1+x)(1+y+z) = 1+(x+y)``)."""

    def to_struct(v: np.ndarray) -> np.ndarray:
        c0, c1, c2, c3 = (int(t) for t in v)
        return np.array([c0, (c1 + c3) % 2, (c2 + c3) % 2, c2], dtype=np.uint8)

    def to_flat(d: np.ndarray) -> np.ndarray:
        d0, dx, dy, dz = (int(t) for t in d)
        return np.array(
            [d0, (dx + dy + dz) % 2, dz, (dy + dz) % 2], dtype=np.uint8
        )

    def struct_mul(u: np.ndarray, v: np.ndarray) -> np.ndarray:
        u0, ux, uy, uz = (int(t) for t in u)
        v0, vx, vy, vz = (int(t) for t in v)
        return np.array(
            [
                (u0 * v0) % 2,
                (u0 * vx + v0 * ux) % 2,
                (u0 * vy + v0 * uy) % 2,
                (u0 * vz + v0 * uz + ux * vy + uy * vx) % 2,
            ],
            dtype=np.uint8,
        )

    def multiply(a: np.ndarray, b: np.ndarray) -> np.ndarray:
        return to_flat(struct_mul(to_struct(a), to_struct(b)))

    one = to_flat(np.array([1, 0, 0, 0], dtype=np.uint8))
    return AlgebraF2(np.eye(4, dtype=np.uint8), multiply, one)


def test_unit_group_adversarial_radical_basis_generates() -> None:
    """Regression: an RREF radical basis can under-generate ``1 + N``; the
    filtration-adapted basis must make the generators total on every seed."""

    algebra = _adversarial_algebra()
    for seed in [*range(61), None]:
        result = (
            unit_group(algebra) if seed is None else unit_group(algebra, seed=seed)
        )
        assert result.status == "exact", f"seed {seed}: {result.detail}"
        assert result.order == 8
        assert _closure_size(algebra, result.generators) == result.order


def _matrix2_mul(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return ((a.reshape(2, 2) @ b.reshape(2, 2)) % 2).reshape(-1).astype(np.uint8)


def test_char2_radical_known_algebras() -> None:
    # F_2[x]/(x^2): the naive trace form degenerates here; radical = (x)
    def dual_mul(a, b):
        return np.array(
            [a[0] & b[0], (a[0] & b[1]) ^ (a[1] & b[0])], dtype=np.uint8
        )

    dual = AlgebraF2(
        np.eye(2, dtype=np.uint8), dual_mul, np.array([1, 0], dtype=np.uint8)
    )
    radical = _char2_radical(dual)
    assert radical.shape[0] == 1
    assert np.array_equal(
        (radical[0] @ dual.basis) % 2, np.array([0, 1], dtype=np.uint8)
    )

    # upper-triangular 2x2 over F_2: radical = span{e12}
    upper_basis = np.array(
        [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1]], dtype=np.uint8
    )
    upper = AlgebraF2(
        upper_basis, _matrix2_mul, np.array([1, 0, 0, 1], dtype=np.uint8)
    )
    radical = _char2_radical(upper)
    assert radical.shape[0] == 1
    assert np.array_equal(
        (radical[0] @ upper.basis) % 2, np.array([0, 1, 0, 0], dtype=np.uint8)
    )

    # M_2(F_2) is semisimple: radical = 0
    full = AlgebraF2(
        np.eye(4, dtype=np.uint8), _matrix2_mul, np.array([1, 0, 0, 1], dtype=np.uint8)
    )
    assert _char2_radical(full).shape[0] == 0

    # direct sum (upper-triangular 2x2) + M_2(F_2): radical = span{e12 + 0}
    def sum_mul(a, b):
        return np.concatenate(
            [_matrix2_mul(a[:4], b[:4]), _matrix2_mul(a[4:], b[4:])]
        )

    basis = np.zeros((7, 8), dtype=np.uint8)
    basis[:3, :4] = upper_basis
    basis[3:, 4:] = np.eye(4, dtype=np.uint8)
    one = np.array([1, 0, 0, 1, 1, 0, 0, 1], dtype=np.uint8)
    algebra = AlgebraF2(basis, sum_mul, one)
    radical = _char2_radical(algebra)
    assert radical.shape[0] == 1
    assert np.array_equal(
        (radical[0] @ algebra.basis) % 2,
        np.array([0, 1, 0, 0, 0, 0, 0, 0], dtype=np.uint8),
    )


# Best-known [[7,5,1]] and [[7,6,1]] stabilizer matrices in (X|Z) form from
# M. Grassl's tables, https://codetables.de (QECC.php?q=4&n=7&k=5 and
# QECC.php?q=4&n=7&k=6, both last modified 2005).  Regression: their local
# Clifford algebras (dims 26 and 27) force the structured route, and the
# randomized radical search used to miss the nilpotent element of the dim-3
# triangular block on the stabilized qubits, returning "unknown" on every
# seed; the deterministic CIW radical finds it.
_CODETABLES_7_5 = [
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
]
_CODETABLES_7_6 = [
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
]


@pytest.mark.parametrize(
    "rows, order",
    [(_CODETABLES_7_5, 6**5 * 2 * 2), (_CODETABLES_7_6, 6**6 * 2)],
    ids=["[[7,5,1]]", "[[7,6,1]]"],
)
def test_codetables_structured_route_exact(rows, order) -> None:
    analysis = analyze_local_clifford(
        StabilizerCode(np.asarray(rows, dtype=np.uint8))
    )
    result = analysis.to_dict()
    assert result["algebra_dimension"] > 24  # exercises the structured route
    assert result["status"] == "exact"
    assert result["certified"] is True
    assert result["physical_group_order"] == order


def _stacked(css: CSSCode) -> StabilizerCode:
    return StabilizerCode(
        np.vstack(
            [
                np.hstack([css.c_x, np.zeros_like(css.c_x)]),
                np.hstack([np.zeros_like(css.c_z), css.c_z]),
            ]
        )
    )


@pytest.mark.parametrize(
    "name", ["steane", "c4-22", "iceberg-8", "cube-832", "qrm15", "toric-4"]
)
def test_structured_route_matches_enumeration(name) -> None:
    code = _stacked(CSSCode(*REGISTRY[name].build()))
    structured = LocalCliffordAnalysis(code, dim_cap=0).to_dict()
    enumerated = LocalCliffordAnalysis(code).to_dict()
    assert structured["status"] == "exact"
    assert structured["physical_group_order"] == enumerated["physical_group_order"]
    assert (
        structured["logical_group"]["order"] == enumerated["logical_group"]["order"]
    )


def test_partition_units_structured_or_honest() -> None:
    from qec_transversal.stabilizer import partition_units_via_structure

    steane = _stacked(CSSCode(*REGISTRY["steane"].build()))
    result = partition_units_via_structure(steane, [(0, 1), (2, 3), (4, 5), (6,)])
    assert result["status"] == "exact"
    assert result["symplectic_group_order"] == 48
    assert result["logical_group"]["order"] == 6

    c422 = _stacked(CSSCode(*REGISTRY["c4-22"].build()))
    result = partition_units_via_structure(c422, [(0, 1), (2, 3)])
    # structured route may fall back to enumeration; either way the result
    # must be exact and correct, never silently wrong
    assert result["status"] == "exact"
    assert result["symplectic_group_order"] == 384
    assert result["logical_group"]["order"] == 48
