"""Exhaustive completeness check of the parameter-space method.

For small codes, enumerate ALL ``6^n`` strict-transversal assignments (an
arbitrary single-qubit Clifford mod Pauli on each qubit, including
Hadamard-type gates, not only the diagonal layers the tool searches).  The
assignments preserving the stabilizer row space form the true
strict-transversal group mod Paulis; per Albert (arXiv:2608.05688) it must
equal the group generated by the ``A_Z``/``A_X`` shear layers alone, and its
size must match the Eq. 23 normal-form count
``#{(t, q, p) in (A_Z n A_X) x A_Z x A_X : q * p = 0}``.
"""

import numpy as np
import pytest

from qec_transversal import REGISTRY, CSSCode
from qec_transversal.ansatz.strict_css import shear_matrix
from qec_transversal.codes import steane_code, surface_code, toric_code
from qec_transversal.utils.gf2 import nullspace, rref

# The six elements of SL(2,2) acting on row vectors (x, z).
GATES = np.array(
    [
        [[1, 0], [0, 1]],
        [[1, 1], [0, 1]],
        [[1, 0], [1, 1]],
        [[0, 1], [1, 0]],
        [[1, 1], [1, 0]],
        [[0, 1], [1, 1]],
    ],
    dtype=np.uint8,
)


def _assignment_matrix(digits: tuple[int, ...], n: int) -> np.ndarray:
    matrix = np.zeros((2 * n, 2 * n), dtype=np.uint8)
    for qubit, gate in enumerate(digits):
        block = GATES[gate]
        matrix[qubit, qubit] = block[0, 0]
        matrix[qubit, n + qubit] = block[0, 1]
        matrix[n + qubit, qubit] = block[1, 0]
        matrix[n + qubit, n + qubit] = block[1, 1]
    return matrix


def _true_transversal_group(code: CSSCode) -> set[bytes]:
    reduced, pivots = rref(code.stabilizer)
    pivot_list = list(pivots)
    survivors: set[bytes] = set()
    for index in range(6**code.n):
        digits = []
        rem = index
        for _ in range(code.n):
            digits.append(rem % 6)
            rem //= 6
        matrix = _assignment_matrix(tuple(digits), code.n)
        image = (code.stabilizer.astype(np.int64) @ matrix.astype(np.int64) % 2).astype(np.uint8)
        if pivot_list:
            residue = image ^ (
                image[:, pivot_list].astype(np.int64) @ reduced.astype(np.int64) % 2
            ).astype(np.uint8)
        else:
            residue = image
        if not residue.any():
            survivors.add(matrix.tobytes())
    return survivors


def _generated_group(code: CSSCode, analysis) -> set[bytes]:
    generators = [shear_matrix("Z", p) for p in analysis.a_z.basis] + [
        shear_matrix("X", p) for p in analysis.a_x.basis
    ]
    identity = np.eye(2 * code.n, dtype=np.uint8)
    seen = {identity.tobytes(): identity}
    queue = [identity]
    while queue:
        element = queue.pop()
        for generator in generators:
            product = (element @ generator) & 1
            key = product.tobytes()
            if key not in seen:
                seen[key] = product
                queue.append(product)
    return set(seen)


def _albert_count(analysis, n: int) -> int:
    def span(basis: np.ndarray) -> list[np.ndarray]:
        vectors = []
        for mask in range(1 << basis.shape[0]):
            vector = np.zeros(n, dtype=np.uint8)
            for row in range(basis.shape[0]):
                if (mask >> row) & 1:
                    vector ^= basis[row]
            vectors.append(vector)
        return vectors

    a_z = span(analysis.a_z.basis)
    a_x = span(analysis.a_x.basis)
    intersection = {v.tobytes() for v in a_z} & {v.tobytes() for v in a_x}
    pairs = sum(1 for q in a_z for p in a_x if not (q & p).any())
    return len(intersection) * pairs


def _check(code: CSSCode) -> None:
    analysis = code.analyze_transversal()
    true_group = _true_transversal_group(code)
    generated = _generated_group(code, analysis)
    assert generated == true_group
    assert _albert_count(analysis, code.n) == len(true_group)


def test_diagonal_families_generate_the_full_transversal_group_random() -> None:
    rng = np.random.default_rng(20260810)
    for n in range(2, 6):
        for _ in range(4):
            rows_x = rng.integers(0, n + 1)
            h_x = rng.integers(0, 2, size=(rows_x, n), dtype=np.uint8)
            x_perp = nullspace(h_x)
            rows_z = rng.integers(0, n + 1)
            z = rng.integers(0, 2, size=(rows_z, x_perp.shape[0]), dtype=np.uint8)
            h_z = (z.astype(np.int64) @ x_perp.astype(np.int64) % 2).astype(np.uint8)
            _check(CSSCode(h_x, h_z, n=n))


def test_diagonal_families_generate_the_full_transversal_group_named() -> None:
    _check(CSSCode(np.ones((1, 4), np.uint8), np.ones((1, 4), np.uint8)))
    _check(CSSCode(*surface_code(2)))
    _check(CSSCode(*steane_code()))


# The zoo page (§10, "Exhaustive validation") quotes this sweep by its numbers:
# 46 codes at n <= 8, up to 6^8 = 1,679,616 layers on the [[8,2,2]] toric code.
# The fast tests above cover a subset; this is the whole claim, so the page and
# the suite cannot drift apart.
EXHAUSTIVE_SWEEP_CODES = 46
EXHAUSTIVE_SWEEP_MAX_N = 8


@pytest.mark.slow
def test_exhaustive_sweep_backing_the_published_completeness_claim() -> None:
    checked, max_n = 0, 0
    for entry in REGISTRY.values():
        if entry.n <= EXHAUSTIVE_SWEEP_MAX_N:
            _check(CSSCode(*entry.build()))
            checked, max_n = checked + 1, max(max_n, entry.n)
    toric = CSSCode(*toric_code(2))
    assert (toric.n, toric.k) == (8, 2)
    _check(toric)
    checked, max_n = checked + 1, max(max_n, toric.n)

    rng = np.random.default_rng(20260810)
    for n in range(2, 7):
        for _ in range(8):
            rows_x = rng.integers(0, n + 1)
            h_x = rng.integers(0, 2, size=(rows_x, n), dtype=np.uint8)
            x_perp = nullspace(h_x)
            rows_z = rng.integers(0, n + 1)
            z = rng.integers(0, 2, size=(rows_z, x_perp.shape[0]), dtype=np.uint8)
            h_z = (z.astype(np.int64) @ x_perp.astype(np.int64) % 2).astype(np.uint8)
            _check(CSSCode(h_x, h_z, n=n))
            checked, max_n = checked + 1, max(max_n, n)

    assert (checked, max_n) == (EXHAUSTIVE_SWEEP_CODES, EXHAUSTIVE_SWEEP_MAX_N)
