"""The Jacobson radical of a finite ``F_2``-algebra, and its peeling.

The deterministic Cohen-Ivanyos-Wales characteristic-polynomial chain
(:func:`_char2_radical`) supplies a radical *candidate*; the caller never
trusts it.  A nonzero candidate is closed into a two-sided ideal and proven
nilpotent by explicit power computation, and a zero candidate (a
semisimplicity claim) is independently re-certified downstream by the
constructive Wedderburn stage in :mod:`.wedderburn`.
"""

from __future__ import annotations

import numpy as np

from ..utils.gf2 import nullspace, rank, row_basis
from ..utils.polynomials import (
    _berlekamp_factor,
    _charpoly_f2,
    _minimal_polynomial,
    _solve_coords,
)
from .finite_algebra import AlgebraF2


def _ideal_closure(algebra: AlgebraF2, seed_rows: np.ndarray) -> np.ndarray:
    """Row basis of the two-sided ideal generated by ``seed_rows`` (coords)."""

    current = row_basis(seed_rows, ncols=algebra.dim) if seed_rows.size else seed_rows
    while True:
        extended = [current]
        for v in current:
            for i in range(algebra.dim):
                extended.append(algebra.coords_multiply(algebra.basis_coords(i), v)[None, :])
                extended.append(algebra.coords_multiply(v, algebra.basis_coords(i))[None, :])
        stacked = np.vstack(extended)
        new = row_basis(stacked, ncols=algebra.dim)
        if new.shape[0] == current.shape[0]:
            return new
        current = new



def _is_nilpotent_ideal(algebra: AlgebraF2, ideal: np.ndarray) -> bool:
    """Prove nilpotency by explicit power computation (exact, no heuristics)."""

    current = ideal
    for _ in range(algebra.dim + 1):
        if current.shape[0] == 0:
            return True
        products = [
            algebra.coords_multiply(u, v) for u in current for v in ideal
        ]
        nxt = row_basis(np.asarray(products, dtype=np.uint8), ncols=algebra.dim)
        if nxt.shape[0] >= current.shape[0]:
            return False  # dimension must strictly descend for nilpotency
        current = nxt
    return current.shape[0] == 0


def _find_nilpotent_ideal(algebra: AlgebraF2, rng: np.random.Generator) -> np.ndarray | None:
    """Search for a nonzero nilpotent two-sided ideal (None if not found)."""

    for _ in range(60):
        a = rng.integers(0, 2, size=algebra.dim, dtype=np.uint8)
        if not a.any():
            continue
        R = algebra.right_matrix(a)
        # kernels of powers of a right-multiplication are left submodules;
        # their ideal closures are candidates
        power = R.copy()
        for _ in range(3):
            kern = nullspace(power)  # vectors v with (power) v = 0 (column action)
            if 0 < kern.shape[0] < algebra.dim:
                ideal = _ideal_closure(algebra, kern)
                if ideal.shape[0] < algebra.dim and _is_nilpotent_ideal(algebra, ideal):
                    if ideal.shape[0] > 0:
                        return ideal
            power = (power @ R) % 2
        L = algebra.left_matrix(a)
        power = L.copy()
        for _ in range(3):
            kern = nullspace(power)
            if 0 < kern.shape[0] < algebra.dim:
                ideal = _ideal_closure(algebra, kern)
                if 0 < ideal.shape[0] < algebra.dim and _is_nilpotent_ideal(algebra, ideal):
                    return ideal
            power = (power @ L) % 2
        coords_a = a.copy()
        for _ in range(algebra.dim.bit_length()):
            coords_a = algebra.coords_multiply(coords_a, coords_a)
        if coords_a.any():
            continue
        # a itself nilpotent: ideal closure candidate
        ideal = _ideal_closure(algebra, a[None, :])
        if 0 < ideal.shape[0] < algebra.dim and _is_nilpotent_ideal(algebra, ideal):
            return ideal
    return None


def _char2_radical(algebra: AlgebraF2) -> np.ndarray:
    """Deterministic Jacobson-radical candidate over F_2 (the CIW chain).

    Cohen-Ivanyos-Wales (J. Algebra 194, 1997) / Ivanyos-Ronyai char-p
    radical computation, specialised to the prime field F_2 and to the
    faithful left regular representation ``x -> L_x`` (dimension
    ``d = algebra.dim``).  With ``c_i(M)`` the coefficient of
    ``lambda^{d-i}`` in the characteristic polynomial of ``M``, the chain

        ``I_0 = A,   I_{j+1} = {x in I_j : c_{2^j}(L_x L_y) = 0
                                for all y in I_j}``

    consists of ideals and reaches ``Rad(A)`` once ``2^j`` exceeds ``d``,
    i.e. after ``floor(log2 d) + 1`` steps.  Level ``j = 0`` is Dickson's
    trace form; the higher charpoly-coefficient forms repair its char-2
    degeneracy.  Over the prime field the level-``j`` form is additive in
    each argument *on* ``I_j`` (Friedl-Ronyai / CIW), so each step is a
    single GF(2) kernel of the form matrix on a basis of ``I_j``.

    The caller treats the result as a CANDIDATE only: a nonzero result is
    closed into an ideal and proven nilpotent explicitly, and a zero
    result (a semisimplicity claim) is independently re-certified by the
    constructive Wedderburn stage.
    """

    d = algebra.dim
    current = np.eye(d, dtype=np.uint8)
    j = 0
    while (1 << j) <= d and current.shape[0]:
        r = current.shape[0]
        index = d - (1 << j)  # low-degree-first position of c_{2^j}
        lefts = [algebra.left_matrix(row) for row in current]
        forms = np.zeros((r, r), dtype=np.uint8)
        for a in range(r):
            for b in range(a, r):
                # charpoly(AB) = charpoly(BA): the form matrix is symmetric
                value = _charpoly_f2((lefts[a] @ lefts[b]) % 2)[index]
                forms[a, b] = forms[b, a] = value
        kernel = nullspace(forms.T)  # rows t: sum_a t_a T_j(x_a, y_b) = 0
        if kernel.shape[0] == 0:
            current = np.zeros((0, d), dtype=np.uint8)
        else:
            current = row_basis((kernel @ current) % 2, ncols=d)
        j += 1
    return current


def _filtration_adapted_basis(algebra: AlgebraF2, ideal: np.ndarray) -> np.ndarray:
    """Basis of a certified-nilpotent ideal adapted to ``I >= I^2 >= ...``.

    Theorem (generation of ``1 + I``).  Let ``I`` be a nilpotent ideal
    (``I^m = 0``) and ``n_1, ..., n_r`` a *filtration-adapted* basis: each
    ``n_t`` carries a level ``l(t)`` with ``n_t in I^{l(t)}`` such that
    for every ``i`` the images of ``{n_t : l(t) = i}`` in ``I^i/I^{i+1}``
    form a basis of that quotient.  Then ``{1 + n_t}`` generates the
    group ``1 + I``.

    Proof: downward induction on ``i`` with hypothesis "``1 + I^i`` is
    generated by ``{1 + n_t : l(t) >= i}``"; the base ``i = m`` is
    trivial.  For ``a, b in I^i`` one has ``(1+a)(1+b) = 1 + (a+b) + ab``
    with ``ab in I^{2i} <= I^{i+1}``, so multiplying the ``1 + n_t`` with
    ``l(t) = i`` selected by the coordinates of ``a`` modulo ``I^{i+1}``
    produces ``(1 + a)(1 + c)`` for some ``c in I^{i+1}``, and ``1 + c``
    is generated by the deeper generators by induction.  Inverses come
    free in a finite group.  QED

    Adaptedness is NECESSARY, not bookkeeping: in ``N = span{x, y, z}``
    with ``xy = yx = z`` (all other products zero) the RREF basis
    ``{x, y+z, x+y}`` under-generates — ``(1+x)(1+y+z) = 1 + (x+y)``, so
    the three ``1 + basis`` elements reach only 4 of the 8 elements of
    ``1 + N``.  The greedy construction below (deepest nonzero power
    first, keep the rows that grow the rank) always yields an adapted
    basis: rows added at level ``i`` lie in ``I^i`` and are independent
    modulo the previously chosen rows, whose span after level ``i+1`` is
    exactly ``I^{i+1}``.  The span equals ``ideal``'s, so the order
    formula ``2^{dim I}`` and the quotient step are unchanged.
    """

    if ideal.shape[0] == 0:
        return ideal
    powers = [row_basis(ideal, ncols=algebra.dim)]
    while powers[-1].shape[0]:
        products = [
            algebra.coords_multiply(u, v) for u in powers[-1] for v in powers[0]
        ]
        nxt = row_basis(np.asarray(products, dtype=np.uint8), ncols=algebra.dim)
        if nxt.shape[0] >= powers[-1].shape[0]:
            raise AssertionError(
                "filtration of a certified-nilpotent ideal must descend"
            )
        powers.append(nxt)
    chosen = np.zeros((0, algebra.dim), dtype=np.uint8)
    for level in powers[-2::-1]:  # deepest nonzero power first
        for row in level:
            candidate = np.vstack([chosen, row[None, :]])
            if rank(candidate) > chosen.shape[0]:
                chosen = candidate
    return chosen


def _quotient(algebra: AlgebraF2, ideal: np.ndarray, lift: np.ndarray):
    """Quotient algebra with a coordinate section back into the parent."""

    complement_rows = []
    current = row_basis(ideal, ncols=algebra.dim)
    for i in range(algebra.dim):
        candidate = np.vstack([current, algebra.basis_coords(i)[None, :]])
        if rank(candidate) > current.shape[0]:
            complement_rows.append(algebra.basis_coords(i))
            current = row_basis(candidate, ncols=algebra.dim)
    section = np.asarray(complement_rows, dtype=np.uint8)
    stacked = np.vstack([section, ideal])

    def project(v: np.ndarray) -> np.ndarray:
        # solve v = s . section + j . ideal jointly; return the section part
        coords = _solve_coords(stacked, v % 2)
        if coords is None:
            raise AssertionError("projection failed: vector outside the algebra")
        return coords[: section.shape[0]]

    def multiply(a_q: np.ndarray, b_q: np.ndarray) -> np.ndarray:
        a_full = (a_q @ section) % 2
        b_full = (b_q @ section) % 2
        return project(algebra.coords_multiply(a_full, b_full))

    one_q = project(algebra.one_coords)
    quotient = AlgebraF2(np.eye(section.shape[0], dtype=np.uint8), multiply, one=(one_q))
    new_lift = (section @ lift) % 2
    return quotient, new_lift


def _composition_flag(algebra: AlgebraF2, rng: np.random.Generator) -> list[np.ndarray]:
    """A heuristic composition flag of the left regular module.

    Splitting uses kernels of irreducible-factor evaluations of random
    right multiplications intersected with the current submodule (both are
    left submodules).  The flag is only a HEURISTIC — everything derived
    from it is verified exactly downstream, so a bad flag can only lead to
    an honest unknown.
    """

    from ..utils.gf2 import row_basis as rb

    def intersect(a: np.ndarray, b: np.ndarray) -> np.ndarray:
        if a.shape[0] == 0 or b.shape[0] == 0:
            return np.zeros((0, algebra.dim), dtype=np.uint8)
        # kernel-of-stacked-duals intersection
        na = nullspace(a)
        nb = nullspace(b)
        return nullspace(np.vstack([na, nb]))

    def split(space: np.ndarray) -> np.ndarray | None:
        for _ in range(40):
            coeffs = rng.integers(0, 2, size=algebra.dim, dtype=np.uint8)
            if not coeffs.any():
                continue
            R = algebra.right_matrix(coeffs)
            poly = _minimal_polynomial(R)
            for factor in _berlekamp_factor(poly):
                if factor.size - 1 == 0:
                    continue
                evaluated = np.zeros((algebra.dim, algebra.dim), dtype=np.uint8)
                power = np.eye(algebra.dim, dtype=np.uint8)
                for coeff in factor:
                    if coeff:
                        evaluated ^= power
                    power = (power @ R) % 2
                candidate = nullspace(evaluated)  # column kernel: a left submodule
                sub = intersect(rb(candidate, ncols=algebra.dim), space)
                if 0 < sub.shape[0] < space.shape[0] and _is_invariant(algebra, sub):
                    return rb(sub, ncols=algebra.dim)
        return None

    def _is_invariant(alg, rows) -> bool:
        span_dual = nullspace(rows)
        for i in range(alg.dim):
            image = (alg.left[i] @ rows.T) % 2  # columns are images
            if span_dual.shape[0] and ((span_dual @ image) % 2).any():
                return False
        return True

    full = np.eye(algebra.dim, dtype=np.uint8)

    def refine(space: np.ndarray) -> list[np.ndarray]:
        sub = split(space)
        if sub is None:
            return [space]
        below = refine(sub)
        return below + [space]

    return refine(full)


def _radical_from_flag(algebra: AlgebraF2, flag: list[np.ndarray]) -> np.ndarray:
    r"""The flag-lowering set {x : L_x V_i \subseteq V_{i-1}} (a two-sided
    ideal when the flag levels are submodules); returned as a row basis of
    coordinate vectors.  Verified for nilpotency by the caller."""

    constraints: list[np.ndarray] = []
    previous = np.zeros((0, algebra.dim), dtype=np.uint8)
    for level in flag:
        duals = nullspace(previous) if previous.shape[0] else np.eye(algebra.dim, dtype=np.uint8)
        # condition: for v in level, w in duals of previous: w . (L_x v) = 0
        for v in level:
            for w in duals:
                row = np.zeros(algebra.dim, dtype=np.uint8)
                for i in range(algebra.dim):
                    row[i] = int((w @ ((algebra.left[i] @ v) % 2)) % 2)
                if row.any():
                    constraints.append(row)
        previous = level
    if not constraints:
        return np.zeros((0, algebra.dim), dtype=np.uint8)
    from ..utils.gf2 import row_basis as rb

    return nullspace(rb(np.asarray(constraints, dtype=np.uint8), ncols=algebra.dim))
