"""Certified unit groups of finite-dimensional matrix algebras over ``F_2``.

Given a basis of an algebra ``A`` (flat GF(2) vectors plus a multiplication),
produce generators of the unit group ``A^x`` together with its exact order,
through the classical structure sequence

    ``1 -> 1 + N -> A^x -> (A/N)^x -> 1``

with ``N`` the iteratively peeled nilpotent radical and the semisimple
quotient split into simple factors ``M_{d_i}(F_{2^{e_i}})``.  This replaces
``2^{dim A}`` element enumeration in the partition solvers.

Every stage is *verified*, never trusted:

- candidate ideals are proven nilpotent by explicit power computation;
- the final quotient is proven semisimple constructively (:mod:`.wedderburn`);
- the returned generators are units by construction, and the order formula
  ``|A^x| = 2^{dim N} * prod_i |GL(d_i, q_i)|`` is assembled only from
  certified pieces.

If any verification fails the result carries ``status = "unknown"`` -- an
incomplete computation is never turned into a negative result.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import numpy as np

from .finite_algebra import AlgebraF2
from .orders import _gl_order
from .radical import (
    _char2_radical,
    _composition_flag,
    _filtration_adapted_basis,
    _find_nilpotent_ideal,
    _ideal_closure,
    _is_nilpotent_ideal,
    _quotient,
    _radical_from_flag,
)
from .wedderburn import _wedderburn


@dataclass
class UnitGroupResult:
    status: str  # "exact" | "unknown"
    order: int | None
    generators: list[np.ndarray] = field(default_factory=list)  # coords in A
    detail: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "order": self.order,
            "generator_count": len(self.generators),
            "detail": self.detail,
        }




def unit_group(algebra: AlgebraF2, *, seed: int = 11) -> UnitGroupResult:
    """Certified generators and exact order of ``A^x``.

    Generation of the whole group by the returned generators is a
    theorem, not a hope, via two nested inductions:

    - within one peel, the nilpotent generators ``1 + n_t`` come from a
      *filtration-adapted* basis of the certified-nilpotent ideal, so
      they generate ``1 + I`` exactly — downward induction on the powers
      ``I^i`` using ``(1+a)(1+b) = 1 + (a+b) + ab`` with ``ab in
      I^{i+1}`` for ``a, b in I^i`` (theorem and the counterexample that
      makes adaptedness necessary: :func:`_filtration_adapted_basis`);
    - across peels, ``pi_1 : A^x -> (A/I_1)^x`` is onto (units lift along
      nilpotent quotients) with kernel ``1 + I_1``.  The later-stage
      generators map under ``pi_1`` onto exactly the quotient's
      generators, which generate ``(A/I_1)^x`` by induction over the
      stages — the induction bottoms out in the semisimple quotient,
      where per-block generation is Schreier-Sims-certified against the
      closed-form ``|GL(d, q)|`` — and the kernel is generated by the
      stage-1 nilpotent generators.  Hence the union generates ``A^x``.

    Falls back to ``status="unknown"`` whenever a structural verification
    fails, per the verifier semantics.
    """

    rng = np.random.default_rng(seed)

    # ---- stage 1: peel nilpotent ideals ----
    nil_rows: list[np.ndarray] = []
    work = algebra
    lift = np.eye(algebra.dim, dtype=np.uint8)  # coords(work) -> coords(algebra)
    total_nil_dim = 0
    for _ in range(algebra.dim):
        # deterministic Cohen-Ivanyos-Wales radical first; its output is
        # only a candidate — verified below before any peeling
        ideal = None
        ciw = _char2_radical(work)
        if ciw.shape[0] == 0:
            # CIW claims semisimplicity; _wedderburn re-certifies it
            # constructively, so an erroneous claim stays an honest unknown
            break
        ciw = _ideal_closure(work, ciw)  # no-op when CIW is correct
        if ciw.shape[0] < work.dim and _is_nilpotent_ideal(work, ciw):
            ideal = ciw
        if ideal is None:
            ideal = _find_nilpotent_ideal(work, rng)
        if ideal is None:
            # flag route: heuristic composition series, exact verification
            flag = _composition_flag(work, rng)
            candidate = _radical_from_flag(work, flag)
            if (
                0 < candidate.shape[0] < work.dim
                and _is_nilpotent_ideal(work, candidate)
            ):
                ideal = candidate
            else:
                break
        # adapted basis: same span (order formula and quotient untouched),
        # but {1 + row} now provably generates 1 + ideal
        ideal = _filtration_adapted_basis(work, ideal)
        total_nil_dim += ideal.shape[0]
        for row in ideal:
            nil_rows.append((row @ lift) % 2)
        # quotient algebra work/ideal
        work, lift = _quotient(work, ideal, lift)
    quotient = work

    # ---- stage 2: verify the quotient is semisimple constructively ----
    split = _wedderburn(quotient, rng)
    if split is None:
        return UnitGroupResult(
            status="unknown",
            order=None,
            detail=(
                "semisimple decomposition could not be verified; unit group "
                "not certified (no silent fallback)"
            ),
        )
    blocks, block_gens = split

    order = 1 << total_nil_dim
    for d, e in blocks:
        order *= _gl_order(d, 1 << e)

    generators: list[np.ndarray] = []
    one_full = algebra.one_coords
    for row in nil_rows:
        generators.append((one_full ^ row) % 2)  # 1 + nilpotent
    for g in block_gens:
        # lift a quotient unit to a full unit: any preimage works because
        # units lift along nilpotent quotients (1 + N is in the kernel)
        lifted = (g @ lift) % 2
        # correct to an actual unit by adding a nilpotent part if necessary
        if not algebra.is_unit(lifted):
            for row in nil_rows:
                candidate = (lifted ^ row) % 2
                if algebra.is_unit(candidate):
                    lifted = candidate
                    break
        if not algebra.is_unit(lifted):
            return UnitGroupResult(
                status="unknown", order=None, detail="unit lifting failed"
            )
        generators.append(lifted)

    return UnitGroupResult(
        status="exact",
        order=order,
        generators=generators,
        detail=(
            f"nilpotent dimension {total_nil_dim}; simple factors "
            + " x ".join(f"M_{d}(F_{1 << e})" for d, e in blocks)
        ),
    )
