"""Exact module elimination over the local ring ``Z_{2^L}``.

The diagonal Clifford-hierarchy solvers reduce to kernels of integer matrices
modulo ``2^L``.  ``Z_{2^L}`` is local with maximal ideal ``(2)``, so a pivot
of minimal 2-adic valuation clears its column and the kernel is generated by
scaled pivot rows -- a Smith-style elimination that is exact, never
approximate.
"""

from __future__ import annotations

import numpy as np


def _valuation(value: int, exponent: int = 3) -> int:
    """2-adic valuation of ``value`` within Z_{2^exponent} (v(0) = exponent)."""

    modulus = 1 << exponent
    if value % modulus == 0:
        return exponent
    value %= modulus
    v = 0
    while value % 2 == 0:
        value //= 2
        v += 1
    return v


def module_kernel(
    constraints: list[tuple[np.ndarray, int]], n: int, *, exponent: int = 3
) -> np.ndarray:
    """Generators of ``{t in Z_{2^exponent}^n : factor * (u . t) = 0}`` for
    all ``(u, factor)`` constraints.

    Standard module elimination over the local ring ``Z_8``: each constraint
    refines the generating set; a pivot generator with minimal 2-adic value
    clears the others and is then scaled by the exact power of two that
    keeps it in the kernel.
    """

    modulus = 1 << exponent
    generators = np.eye(n, dtype=np.int64)
    for pattern, factor in constraints:
        values = (factor * (generators @ pattern.astype(np.int64))) % modulus
        support = np.flatnonzero(values)
        if support.size == 0:
            continue
        valuations = np.array([_valuation(int(v), exponent) for v in values[support]])
        pivot_pos = int(support[np.argmin(valuations)])
        pivot_val = int(values[pivot_pos])
        v_star = _valuation(pivot_val, exponent)
        unit = pivot_val >> v_star
        unit_inv = pow(unit, -1, modulus)
        for index in support:
            if index == pivot_pos:
                continue
            coefficient = ((int(values[index]) >> v_star) * unit_inv) % modulus
            generators[index] = (generators[index] - coefficient * generators[pivot_pos]) % modulus
        generators[pivot_pos] = (generators[pivot_pos] * (1 << (exponent - v_star))) % modulus
    keep = [row for row in generators if (row % modulus).any()]
    if not keep:
        return np.zeros((0, n), dtype=np.int64)
    return np.asarray(keep, dtype=np.int64) % modulus
