"""One-block Clifford analysis over *varying* partitions and dualities.

Chakraborty-Gottesman (arXiv:2602.13395) prove that gadget sets built on one
FIXED partition or duality — sets closed under composition, hence constant
depth — can never realize the full logical Clifford group ``Sp(2k, 2)`` of a
single code block (strict transversality and code automorphisms for k >= 2,
bare permutations even for k = 1, fixed-duality fold gates for k >= 3).  The
same paper points out the loophole: depth-one fold-transversal layers over
*varying* partitions/dualities are not closed under composition, and their
compositions (non-constant-depth circuits of depth-one layers with error
correction in between) may generate everything.  arXiv:2602.09788 proves
exactly that for the middle Reed-Muller family ``RM(m/2-1, m)`` (the
registry's ``tesseract``, ``rm64``, ``rm256``): transversal plus varying-fold
gates generate the full addressable logical Clifford group on one block.

This module decides that question *per code*: it collects every certified
depth-one one-block layer the repository knows how to certify —

* strict transversal shears (:meth:`~..codes.css.CSSCode.analyze_transversal`),
* diagonal fold layers ``S_M^Z`` / ``S_M^X`` and the fold-Hadamard for every
  certified involution (:mod:`..ansatz.matching`), the involutions coming from the
  structural candidates of :mod:`..ansatz.dualities`, the BLISS-discovered involutive
  duality, and involutions sampled from the Tanner automorphism group
  (:func:`..ansatz.twofold.automorphism_involutions`),
* SWAP-class permutation gates from Tanner-graph automorphism generators
  (:mod:`..ansatz.permutation`),

then certifies the group generated by their logical symplectic images
against ``|Sp(2k, 2)|``.  Certification tiers, chosen automatically:

``closure``
    Breadth-first element enumeration (:func:`.group.generated_group_order`)
    when it completes under a cap — exact at any ``k``.
``exact-order``
    Deterministic Schreier-Sims (:func:`.group.schreier_sims_order`) for
    moderate ``k``, compared with ``|Sp(2k, 2)|``.
``recognition``
    For large ``k``, a certified recognition route based on McLaughlin's
    classification of transvection groups (see
    :func:`recognize_full_symplectic`).  Every sub-certificate is exact; if
    any step fails the result downgrades instead of guessing.
``lower-bound``
    The honest fallback: the truncated closure count as a lower bound,
    ``is_full`` undecided.
``skipped``
    Nothing could be certified inside the time budget.

Every generator's logical action is taken only from certified analyses, so a
wrong exact answer is impossible; at worst the verdict is undecided.

Synthesis: :func:`factor_target` factors a target logical symplectic matrix
into an explicit word in the collected depth-one layers via a word-tracking
Schreier-Sims chain, with the chain's completeness cross-checked against the
independent order engine and every returned word verified by recomposition.

Known limits (deliberate, and load-bearing for how results may be quoted):

``is_full`` is one-sided.
    ``True`` is a certificate.  There is no ``False``: a code admits
    exponentially many involutions and this engine samples them, so a group
    short of the target means "the layers found do not suffice", never "the
    code cannot" — such rows report an exact order for the collected
    generating set with ``is_full`` undecided, i.e. a *lower bound* on the
    code's one-block group.
Orders are modulo Pauli.
    Generators are certified at the symplectic/GF(2) level: :mod:`..ansatz.matching`
    checks that each stabilizer row's image lies in the stabilizer row space,
    not that it returns with sign ``+1``.  Sign defects form a character on
    the stabilizer group and are always killable by a Pauli, so the group
    orders are unaffected — but only the strict diagonal generators are
    actually run through the sign-exact Stim verifier (:mod:`..certificates.phase`); fold,
    permutation and partition layers are not.
Fold layers come from certified *matchings*, not only ZX dualities.
    :attr:`MatchingAnalysis.certified` does not require ``is_zx_duality``; a
    matching whose kernels certify contributes a legitimate depth-one layer
    either way.
The Levi (CNOT-network) units are NOT collected.
    Albert's fixed-matching group is ``N_M = <S_M^Z, S_M^X, L_M>``; this
    module takes only what :func:`..ansatz.matching.analyze_matching` returns — the
    two diagonal families and the fold-Hadamard — so the Levi factor
    ``L_M`` (implemented in :mod:`..ansatz.twofold`) is absent from every matching.
    Together with the permutation gates, which ``N_2fold`` does not contain,
    that makes this group and Albert's *incomparable*: neither contains the
    other, and an order above or below a published two-fold number is
    evidence about neither.
``factor_target`` is narrower than the order engine.
    Word-tracking chain construction currently fails past ``k >= 6`` and is
    refused outright for ``k > 8``, so the tesseract full-``Sp(12,2)`` result
    is certified but not yet convertible into an explicit circuit.  Generator
    provenance also records a label and involution index rather than the
    physical layer parameter, so a returned word is not yet directly
    executable on hardware.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from typing import Any

import numpy as np

from ..ansatz.discovery import discover_involutions, structural_permutations
from ..ansatz.dualities import candidates_for
from ..ansatz.matching import analyze_matching
from ..ansatz.twofold import automorphism_involutions
from ..codes.css import CSSCode
from ..utils.gf2 import gf2_inverse, gf2_matmul, nullspace
from ..utils.permutations import random_involution
from ..utils.symplectic import is_symplectic, symplectic_group_order
from .group import generated_group_order, schreier_sims_order
from .recognition import RecognitionReport, recognize_full_symplectic
from .words import WordBSGS

try:  # pragma: no cover - exercised through the igraph import guard
    from ..ansatz.permutation import analyze_automorphisms, describe_permutation
except ImportError:  # pragma: no cover
    analyze_automorphisms = None
    describe_permutation = None
try:  # pragma: no cover - same igraph guard
    from ..ansatz.codeword_permutation import analyze_codeword_automorphisms
except ImportError:  # pragma: no cover
    analyze_codeword_automorphisms = None

#: the codeword-automorphism engine enumerates 2^rank below its full-enum
#: threshold and switches to bounded-weight information-set enumeration
#: above it (bb360, rank 174: exact in ~3 s), so the sweep gate is now the
#: code SIZE, not the rank; over-budget codes decline internally in <1 s.
_CODEWORD_AUT_RANK_CAP = 200
#: and keep the incidence graph modest in a sweep.
_CODEWORD_AUT_N_CAP = 512

#: Schreier-Sims is attempted at or below this k.  The chain's cost is the
#: node budget, not the dimension (matching.logical_group_summary certifies a
#: k = 18 census group of order 1,524,096 in ~16 s), so this reaches to the
#: largest k where moderate orders remain realistic; the budgets stay the
#: guard against groups that are genuinely too big.
_EXACT_ORDER_K_LIMIT = 18

#: The stabilizer chain runs to its own node budget and cannot be cut short by
#: the caller's deadline, so the budget is what scales: full only when the
#: group is already known small (closure completed) or k is trivially tiny.
_SCHREIER_TRIVIAL_K = 4

#: The all-generator chain is affordable only for small generating sets; past
#: this, fullness is decided by subsets (sound, since fullness is monotone) and
#: everything else falls through to a bounded lower bound.
_CHAIN_GENERATOR_LIMIT = 32

#: Past this k the stabilizer chain's orbits (up to 2^{2k} points per level)
#: make it slower than the recognition route, which runs first instead.
_CHAIN_CHEAP_K = 6
#: ...except for generating sets this small, where the chain is still the
#: cheapest way to pin a proper subgroup's exact order.  Sized from the data:
#: the bicycle codes carry 9-14 certified generators and chain in seconds,
#: while the pathological cases (grid-4x6: 270) are far above any threshold.
#: Too low a limit is not merely slow but misleading — bb72 at 14 generators
#: fell through to a truncated closure and reported a floor of 35,715, below
#: the 276,480 its own fold column already proves.
_CHAIN_SPARSE_LIMIT = 18

#: Matrix products the closure tier may spend on one code (element cap times
#: generator count), so a wide generating set cannot silently cost minutes.
_CLOSURE_WORK_BUDGET = 500_000
_SCHREIER_NODE_BUDGET = 2_000_000
_SCHREIER_TIGHT_BUDGET = 250_000

#: Closure enumeration stores dense 2k x 2k matrices; above this k the cap is
#: tightened so a huge-k code cannot exhaust memory before giving up.
_CLOSURE_DENSE_K_LIMIT = 32
_CLOSURE_TIGHT_CAP = 5_000

#: Memory the closure tier may spend on one code.  An element cap alone is not
#: a bound: a stored element is a dense ``2k x 2k`` uint8 matrix *and* its bytes
#: key, so at k = 580 (``apm1152``) five thousand elements would authorize
#: ~13 GB and the sweep thrashes instead of failing over to the next tier.
#: Converting the budget into an element count keeps every k in the same
#: envelope and makes the tier fail fast into ``lower-bound`` where it must.
_CLOSURE_MEMORY_BUDGET_BYTES = 256 << 20


def _memory_safe_closure_cap(k: int, requested: int) -> int:
    """Element cap for the closure tier that respects the memory envelope."""

    if k <= 0:
        return requested
    per_element = 2 * (2 * k) ** 2  # the matrix plus its bytes key
    affordable = max(64, _CLOSURE_MEMORY_BUDGET_BYTES // per_element)
    return int(min(requested, affordable))


@dataclass(frozen=True, eq=False)
class OneBlockGenerator:
    """One certified depth-one one-block layer, by its logical action."""

    matrix: np.ndarray
    kind: str  # "strict-Z" | "strict-X" | "fold-Z" | "fold-X" | "fold-H" | "perm"
    involution: int | None
    label: str

    @property
    def provenance(self) -> dict[str, Any]:
        return {"kind": self.kind, "involution": self.involution, "label": self.label}


def _affine_involutions(n: int, rng: np.random.Generator, count: int) -> list[np.ndarray]:
    """Involutions from the affine group ``AGL(m, 2)`` when ``n = 2^m``.

    Qubit ``j`` is read as the point ``bits(j)`` of ``F_2^m`` (the Reed-Muller
    convention of :func:`..codes.families.reed_muller_generator`).  Candidates:
    translations ``x -> x + b`` (fixed-point-free involutions), coordinate
    transpositions ``x_i <-> x_j``, and shears ``x_i -> x_i + x_j`` — the
    duality/automorphism supply behind the varying-fold generation theorem
    for middle Reed-Muller codes (arXiv:2602.09788).  These are only
    *candidates*: codes without affine symmetry simply reject them during
    matching certification, exactly like the structural guesses in
    :mod:`..ansatz.dualities`.
    """

    m = n.bit_length() - 1
    if n != 1 << m or m < 1:
        return []
    points = np.arange(n)
    coordinates = [(points >> i) & 1 for i in range(m)]
    identity_m = np.eye(m, dtype=np.uint8)
    taus: list[np.ndarray] = []

    structured: list[np.ndarray] = []
    for b in range(1, min(n, m + 2)):  # a few translations (the rest are random)
        structured.append(points ^ b)
    for i in range(m):  # coordinate transpositions
        for j in range(i + 1, m):
            swapped = points & ~((1 << i) | (1 << j))
            swapped |= coordinates[j] << i
            swapped |= coordinates[i] << j
            structured.append(swapped)
    for i in range(m):  # shears x_i -> x_i + x_j
        for j in range(m):
            if i != j:
                structured.append(points ^ (coordinates[j] << i))
    taus.extend(structured[:count])

    def apply_affine(linear: np.ndarray, offset: np.ndarray) -> np.ndarray:
        bits = ((points[:, None] >> np.arange(m)) & 1).astype(np.uint8)
        image = (gf2_matmul(bits, linear.T) ^ offset).astype(np.int64)
        return (image * (1 << np.arange(m))).sum(axis=1)

    # General affine involutions x -> Lx + b with L^2 = I and (L + I)b = 0:
    # canonical unipotent involutions conjugated by random invertible maps.
    # Empirically these are the duality supply that saturates the middle
    # Reed-Muller fold groups where coordinate-aligned involutions plateau.
    attempts = 0
    while len(taus) < count and attempts < 20 * count:
        attempts += 1
        pairs = int(rng.integers(1, m // 2 + 1))
        canonical = identity_m.copy()
        for index in range(pairs):
            canonical[2 * index, 2 * index + 1] = 1
        while True:
            conjugator = rng.integers(0, 2, size=(m, m)).astype(np.uint8)
            try:
                inverse = gf2_inverse(conjugator)
                break
            except ValueError:
                continue
        linear = gf2_matmul(gf2_matmul(inverse, canonical), conjugator)
        kernel = nullspace(linear ^ identity_m)
        offset = np.zeros(m, dtype=np.uint8)
        if kernel.shape[0]:
            coefficients = rng.integers(0, 2, size=kernel.shape[0]).astype(np.uint8)
            offset = (coefficients[None, :] @ kernel % 2).astype(np.uint8)[0]
        tau = apply_affine(linear, offset)
        if not np.array_equal(tau, points) and np.array_equal(tau[tau], points):
            taus.append(tau)
    return taus[:count]


#: The fallback matching sampler, shared with :mod:`..ansatz.twofold`.
_random_involution = random_involution


def _collect_involutions(
    code: CSSCode,
    name: str | None,
    aut,
    *,
    involution_cap: int,
    seed: int,
    extra_taus: list[np.ndarray] | None,
    discover: bool = True,
) -> list[tuple[str, np.ndarray]]:
    """Candidate involutions: identity, structural, BLISS duality, affine
    candidates (for ``n = 2^m``), automorphism-group samples, then random
    matchings as filler — every candidate is certified or rejected by
    :class:`..ansatz.matching.MatchingAnalysis` before any gate is trusted."""

    n = code.n
    identity = np.arange(n)
    candidates: list[tuple[str, np.ndarray]] = [("identity", identity)]
    if name is not None:
        for label, tau in candidates_for(name):
            tau = np.asarray(tau, dtype=int)
            if np.array_equal(tau[tau], identity):
                candidates.append((label, tau))
    for index, tau in enumerate(extra_taus or []):
        tau = np.asarray(tau, dtype=int)
        if np.array_equal(tau[tau], identity):
            candidates.append((f"extra-{index}", tau))
    # Structure-inferred candidates are ADDITIVE: they raise the cap by their
    # own count instead of competing under it.  They are the only supply that
    # works on codes outside the registry (the 2026-08-19 census cross-check
    # found order-1 blind verdicts on quasi-cyclic codes whose certified
    # groups reach 5x10^11), but letting them displace the legacy supplies
    # under one shared cap costs certificates that depend on a wide legacy
    # sample (rm64's full-Sp(40,2) needs its 48 affine candidates).  The
    # analysis loop's time budget remains the hard guard on total work.
    discovered = discover_involutions(code, forward_cap=involution_cap) if discover else []
    candidates.extend(discovered)
    keep_cap = involution_cap + len(discovered)
    if aut is not None:
        duality = aut.involutive_duality()
        if duality is not None:
            candidates.append(("bliss-involutive-duality", duality))
        if aut.qubit_generators:
            sampled = automorphism_involutions(
                aut.qubit_generators, n, count=involution_cap, seed=seed
            )
            for index, tau in enumerate(sampled):
                candidates.append((f"aut-sample-{index}", tau))
    rng = np.random.default_rng(seed)
    for index, tau in enumerate(_affine_involutions(n, rng, involution_cap)):
        candidates.append((f"affine-{index}", tau))
    # Random-matching filler is sized against the LEGACY candidate count: the
    # additive discovered block must not eat the random sample (bb72's order
    # 35,715 depends on it) any more than the legacy supplies may crowd out
    # discovery.
    while len(candidates) - len(discovered) < 2 * involution_cap:
        candidates.append((f"random-{len(candidates)}", _random_involution(rng, n)))
    unique: list[tuple[str, np.ndarray]] = []
    seen: set[bytes] = set()
    for label, tau in candidates:
        key = tau.tobytes()
        if key not in seen:
            seen.add(key)
            unique.append((label, tau))
        if len(unique) >= keep_cap:
            break
    return unique



class OneBlockAnalysis:
    """Result of :func:`analyze_one_block`; ``to_dict`` follows the shared
    one-block data contract (see the module docstring)."""

    def __init__(
        self,
        code: CSSCode,
        generators: tuple[OneBlockGenerator, ...],
        *,
        involutions_used: int,
        strict_dim: int,
        logical_order: int | None,
        logical_order_exact: bool,
        is_full: bool | None,
        certification: str,
        detail: str,
        seconds: float,
        recognition: RecognitionReport | None = None,
    ):
        self.code = code
        self.generators = generators
        self.involutions_used = involutions_used
        self.strict_dim = strict_dim
        self.logical_order = logical_order
        self.logical_order_exact = logical_order_exact
        self.sp_target = symplectic_group_order(code.k)
        self.is_full = is_full
        self.certification = certification
        self.detail = detail
        self.seconds = seconds
        self.recognition = recognition
        self._bsgs: WordBSGS | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "generator_count": len(self.generators),
            "involutions_used": int(self.involutions_used),
            "strict_dim": int(self.strict_dim),
            "logical_order": self.logical_order,
            "logical_order_exact": bool(self.logical_order_exact),
            "sp_target": int(self.sp_target),
            "is_full": self.is_full,
            "certification": self.certification,
            "detail": self.detail,
            "seconds": float(round(self.seconds, 3)),
        }


def analyze_one_block(
    code: CSSCode,
    *,
    name: str | None = None,
    involution_cap: int = 16,
    time_budget_s: float = 120.0,
    closure_cap: int = 100_000,
    seed: int = 7,
    extra_taus: list[np.ndarray] | None = None,
    discover: bool = True,
) -> OneBlockAnalysis:
    """Certified one-block varying-partition Clifford analysis of ``code``.

    Collects the logical actions of every certified depth-one one-block layer
    (strict shears, per-involution fold layers and fold-Hadamards, Tanner
    automorphism permutation gates) and certifies the generated subgroup of
    ``Sp(2k, 2)`` by the tier ladder described in the module docstring.
    ``name`` (a registry key) unlocks the structural duality candidates of
    :mod:`..ansatz.dualities`; ``involution_cap`` bounds how many involutions are
    analyzed; ``extra_taus`` allows caller-supplied involutions (certified
    like all others before use).
    """

    start = time.perf_counter()
    deadline = start + time_budget_s
    notes: list[str] = []

    strict = code.analyze_transversal()
    strict_dim = strict.a_z.dimension + strict.a_x.dimension

    records: list[OneBlockGenerator] = []
    seen: set[bytes] = set()

    def add(matrix: np.ndarray, kind: str, involution: int | None, label: str) -> None:
        matrix = (np.asarray(matrix, dtype=np.uint8) & 1).copy()
        if matrix.size == 0 or np.array_equal(matrix, np.eye(matrix.shape[0], dtype=np.uint8)):
            return
        if not is_symplectic(matrix, qubits=code.k):  # pragma: no cover - certified upstream
            raise AssertionError("internal error: non-symplectic logical action collected")
        key = matrix.tobytes()
        if key in seen:
            return
        seen.add(key)
        records.append(OneBlockGenerator(matrix, kind, involution, label))

    if strict.certified:
        for generator in strict.generators:
            if all(generator.certificate.values()):
                add(
                    generator.logical_symplectic,
                    f"strict-{generator.family}",
                    None,
                    "strict transversal shear",
                )
    else:  # pragma: no cover - strict analysis certifies on all repo codes
        notes.append("strict analysis failed certification; strict layers skipped")

    aut = None
    if analyze_automorphisms is not None:
        try:
            aut = analyze_automorphisms(code)
        except ImportError:  # pragma: no cover
            notes.append("python-igraph unavailable; automorphism gates skipped")

    involutions = _collect_involutions(
        code,
        name,
        aut,
        involution_cap=involution_cap,
        seed=seed,
        extra_taus=extra_taus,
        discover=discover,
    )
    # Only involutions that actually hand over a gate are counted: a matching
    # whose kernels are empty certifies vacuously (``all()`` of nothing), and
    # counting those would advertise contributing pairings the code lacks.
    contributing: set[int] = set()
    truncated = False
    for index, (label, tau) in enumerate(involutions):
        if time.perf_counter() > deadline:
            notes.append(f"time budget hit during collection after {index} involutions")
            truncated = True
            break
        matching = analyze_matching(code, tau)
        if not matching.certified:
            continue
        before = len(records)
        for generator in matching.generators:
            if all(generator.certificate.values()):
                add(
                    generator.logical_symplectic,
                    f"fold-{generator.family}",
                    index,
                    f"fold layer on {label}",
                )
        fold_h = matching.fold_hadamard
        if fold_h is not None and all(fold_h.certificate.values()):
            add(fold_h.logical_symplectic, "fold-H", index, f"fold-Hadamard on {label}")
        if len(records) > before:
            contributing.add(index)

    if aut is not None and aut.certified:
        for generator in aut.generators:
            if all(generator.certificate.values()):
                add(generator.logical_symplectic, "perm", None, "Tanner automorphism")

    # Structural shift automorphisms: quasi-cyclic block shifts certified by
    # rank identities on the row SPACES, which the Tanner route (row-SET
    # scoped) misses whenever the recorded generators are not shift-closed —
    # precisely the failure observed on external census codes.
    if discover and describe_permutation is not None:
        for perm in structural_permutations(code):
            record = describe_permutation(code, perm)
            if all(record.certificate.values()):
                add(record.logical_symplectic, "perm", None, "structural shift automorphism")

    # Characteristic-set (row-space) permutation automorphisms: the
    # Leon-style invariant-set reduction through BLISS.  Enumeration is
    # 2^rank, so this stays behind rank/size caps; within them it is the
    # exact CSS permutation automorphism group, the capability every other
    # open tool defers to MAGMA or GAP for.
    if (
        discover
        and analyze_codeword_automorphisms is not None
        and max(code.c_x.shape[0], code.c_z.shape[0]) <= _CODEWORD_AUT_RANK_CAP
        and code.n <= _CODEWORD_AUT_N_CAP
        and time.perf_counter() < deadline
    ):
        try:
            codeword_group = analyze_codeword_automorphisms(code)
        except (ImportError, ValueError):
            codeword_group = None
        if codeword_group is not None:
            for generator in codeword_group.generators:
                if all(generator.certificate.values()):
                    add(generator.logical_symplectic, "perm", None, "codeword automorphism")

    generators = tuple(records)
    matrices = [record.matrix for record in generators]
    sp_target = symplectic_group_order(code.k)
    recognition: RecognitionReport | None = None

    def finish(
        logical_order, exact, is_full, certification, message
    ) -> OneBlockAnalysis:
        # ``is_full`` is one-sided by construction.  True is a certificate: we
        # exhibited certified layers whose logical images generate Sp(2k, 2).
        # False is NOT: the matchings a code admits cannot be enumerated (there
        # are exponentially many involutions of n qubits, and this engine
        # samples them), so a group short of the target only says "the layers
        # found so far do not suffice" — never "the code cannot".  Publishing
        # that as a negative would be exactly the failed-search-dressed-as-a-
        # proof this project refuses to ship, so it is reported as undecided
        # with an exact order for the collected generating set.
        if is_full is False:
            is_full = None
            message = (
                f"{message}; short of |Sp({2 * code.k},2)| for the layers found — "
                "a lower bound on the code's one-block group, not a negative verdict"
            )
        detail = "; ".join([message] + notes) if notes else message
        if truncated:
            # A deadline-truncated collection saw only part of the code's
            # layers: the group it found is a subgroup of the real one, so the
            # order is a lower bound however exactly it was computed, and a
            # not-full verdict would be unsound.
            return OneBlockAnalysis(
                code,
                generators,
                involutions_used=len(contributing),
                strict_dim=strict_dim,
                logical_order=logical_order,
                logical_order_exact=False,
                is_full=True if is_full else None,
                certification="lower-bound",
                detail=detail,
                seconds=time.perf_counter() - start,
                recognition=recognition,
            )
        return OneBlockAnalysis(
            code,
            generators,
            involutions_used=len(contributing),
            strict_dim=strict_dim,
            logical_order=logical_order,
            logical_order_exact=exact,
            is_full=is_full,
            certification=certification,
            detail=detail,
            seconds=time.perf_counter() - start,
            recognition=recognition,
        )

    if code.k == 0 or not matrices:
        order = 1
        return finish(
            order,
            True,
            order == sp_target,
            "closure",
            "no nontrivial certified generators" if code.k else "k = 0: trivial target",
        )

    if time.perf_counter() > deadline:
        return finish(None, False, None, "skipped", "time budget exhausted before certification")

    # Tier order matters more than any single budget.  Enumeration costs one
    # matrix product per (element, generator) pair, so a group of a few
    # million with fifty generators is hundreds of millions of numpy calls —
    # grid-4x6 (k = 8) spent over half an hour there — while the stabilizer
    # chain reaches the same exact order in polynomial time (gross, order
    # 11,059,200 at k = 12: 3.9 s).  So where the chain is viable at all, run
    # it FIRST and let enumeration be the fallback, not the gate.
    #
    # Cost is driven by the GENERATOR COUNT, not by k: the chain processes one
    # Schreier generator per (orbit point, generator), so gross (k = 12, nine
    # generators) certifies in three seconds while grid-4x6 (k = 8, but 270
    # generators after sweeping 48 matchings) does not finish at any budget.
    # Two consequences, both sound:
    #   * fullness is monotone — if a SUBSET generates Sp(2k,2) then so does
    #     the whole certified set, since every generator is symplectic — so
    #     subsets are tried first and a hit is a genuine certificate;
    #   * the exact order of a non-full group is never published (the column
    #     reports FULL or a lower bound), so the expensive all-generator chain
    #     is reserved for sets small enough to afford it.
    if code.k <= _CHAIN_CHEAP_K and time.perf_counter() < deadline:
        for size in (6, 10, 16):
            if size >= len(matrices):
                break
            if time.perf_counter() > deadline:
                break
            subset_order = schreier_sims_order(
                matrices[:size], node_budget=_SCHREIER_TIGHT_BUDGET
            )
            if subset_order == sp_target:
                return finish(
                    sp_target,
                    True,
                    True,
                    "exact-order",
                    f"Schreier-Sims: a {size}-generator subset already reaches "
                    f"|Sp({2 * code.k},2)|, so the full certified set does too",
                )
        if len(matrices) <= _CHAIN_GENERATOR_LIMIT and time.perf_counter() < deadline:
            chain_first = schreier_sims_order(matrices, node_budget=_SCHREIER_NODE_BUDGET)
            if chain_first is not None:
                return finish(
                    chain_first,
                    True,
                    chain_first == sp_target,
                    "exact-order",
                    "Schreier-Sims exact order over all generators",
                )

    # Tier: recognition-first for larger k.  The chain's cost grows with the
    # ORBIT size (up to 2^{2k} points per level), so past k = 6 it is the
    # recognition route — a transvection witness plus certified irreducibility
    # and the absence of an invariant quadratic form — that decides fullness
    # quickly (rm64, k = 20: 5.4 s).  Enumeration and the all-generator chain
    # stay below it as the ways to pin an order when fullness does not hold.
    if code.k > _CHAIN_CHEAP_K and time.perf_counter() < deadline:
        recognition = recognize_full_symplectic(
            matrices,
            code.k,
            seed=seed,
            time_budget_s=max(1.0, min(30.0, deadline - time.perf_counter())),
        )
        if recognition.verdict == "full":
            return finish(
                sp_target,
                True,
                True,
                "recognition",
                "McLaughlin transvection recognition certified fullness: " + recognition.detail,
            )
        if (
            len(matrices) <= _CHAIN_SPARSE_LIMIT
            and code.k <= _EXACT_ORDER_K_LIMIT
            and time.perf_counter() < deadline
        ):
            # Few generators: the chain is affordable and pins the exact order
            # of a proper subgroup (gross, nine generators at k = 12: 3.7 s).
            sparse_chain = schreier_sims_order(matrices, node_budget=_SCHREIER_NODE_BUDGET)
            if sparse_chain is not None:
                return finish(
                    sparse_chain,
                    True,
                    sparse_chain == sp_target,
                    "exact-order",
                    "Schreier-Sims exact order over all generators (sparse set)",
                )

    # Tier: closure — exact at any k when the group is small enough to list.
    effective_cap = closure_cap if code.k <= _CLOSURE_DENSE_K_LIMIT else min(
        closure_cap, _CLOSURE_TIGHT_CAP
    )
    effective_cap = _memory_safe_closure_cap(code.k, effective_cap)
    # Enumeration costs one matrix product per (element, generator) pair, so a
    # wide generating set is as expensive as a large cap: wzl20 sweeps 233
    # certified layers, where a 100k cap would mean 23M products.  Since this
    # tier only supplies a lower bound once recognition has declined to
    # certify, bound the WORK rather than the element count.
    effective_cap = max(64, min(effective_cap, _CLOSURE_WORK_BUDGET // max(1, len(matrices))))
    closure = generated_group_order(matrices, cap=effective_cap)
    if closure.exact:
        if code.k <= _EXACT_ORDER_K_LIMIT and closure.order <= 50_000:
            chain = schreier_sims_order(matrices)
            if chain is not None and chain != closure.order:
                raise AssertionError("internal error: closure and stabilizer chain disagree")
        return finish(
            closure.order,
            True,
            closure.order == sp_target,
            "closure",
            f"closure enumeration completed with {closure.order} elements",
        )

    # Tier: exact-order — deterministic Schreier-Sims for moderate k.
    #
    # The chain cannot be interrupted by the caller's deadline: it runs to
    # its own ``node_budget`` and only then returns ``None``.  The default
    # budget of two million transversal points is minutes of work per call
    # on a group the size of Sp(20,2) — a census run spent an hour inside a
    # single k = 10 code before this was bounded.  So the budget, not the
    # attempt, is what scales: generous where the chain is known to be cheap
    # (k <= 8, or a closure that already completed and so proved the group
    # small), tight elsewhere, where an over-budget ``None`` costs little and
    # simply hands the code to the recognition tier.
    # Gate on EVIDENCE, not on k.  A completed closure is proof the group is
    # small, so the chain will be quick; k alone proves nothing — grid-4x6 has
    # k = 8 and a group large enough that the full budget ran for 35 minutes
    # inside one code.  Everything else gets the tight budget, where an
    # over-budget ``None`` is cheap and simply defers to recognition.
    cheap_chain = closure.exact or code.k <= _SCHREIER_TRIVIAL_K
    node_budget = _SCHREIER_NODE_BUDGET if cheap_chain else _SCHREIER_TIGHT_BUDGET
    if code.k <= _EXACT_ORDER_K_LIMIT and time.perf_counter() < deadline:
        chain: int | None = None
        via = "stabilizer chain over all generators"
        if len(matrices) > 12:
            for size in (8, 12):
                subset_order = schreier_sims_order(matrices[:size], node_budget=node_budget)
                if subset_order == sp_target:
                    # A subgroup already reaches |Sp(2k,2)|; since every
                    # generator is certified symplectic, G <= Sp(2k,2), so
                    # G = Sp(2k,2) without processing the rest.
                    chain = subset_order
                    via = f"stabilizer chain over a {size}-generator subset (already full)"
                    break
        if chain is None:
            chain = schreier_sims_order(matrices, node_budget=node_budget)
        if chain is not None:
            return finish(
                chain,
                True,
                chain == sp_target,
                "exact-order",
                f"Schreier-Sims exact order via {via}",
            )

    # Tier: recognition — McLaughlin route for large k.
    if time.perf_counter() < deadline:
        recognition = recognize_full_symplectic(
            matrices,
            code.k,
            seed=seed,
            time_budget_s=max(1.0, deadline - time.perf_counter()),
        )
        if recognition.verdict == "full":
            return finish(
                sp_target,
                True,
                True,
                "recognition",
                "McLaughlin transvection recognition certified fullness: " + recognition.detail,
            )
        if recognition.verdict == "not-full":
            return finish(
                closure.lower_bound,
                False,
                False,
                "recognition",
                "recognition certified G != Sp(2k,2): " + recognition.detail,
            )
        notes.append("recognition inconclusive: " + recognition.detail)

    floor = closure.lower_bound
    if discover:
        # Discovery can widen the certified set past what any exact tier
        # affords, leaving only this truncated floor — which may sit BELOW
        # the order the LEGACY set alone certifies exactly (bb72: floor
        # 9,804 against a certified 35,715).  One discovery-free rerun
        # recovers that certificate; its order bounds the wider group from
        # below because the legacy generators are a subset of the full set.
        legacy = analyze_one_block(
            code,
            name=name,
            involution_cap=involution_cap,
            time_budget_s=max(1.0, deadline - time.perf_counter()),
            closure_cap=closure_cap,
            seed=seed,
            extra_taus=extra_taus,
            discover=False,
        )
        if legacy.logical_order is not None and legacy.logical_order > (floor or 0):
            floor = legacy.logical_order
            notes.append(
                f"floor raised to the legacy-set verdict {legacy.logical_order} "
                f"({legacy.certification}): its generators are a subset of this run's"
            )
    return finish(
        floor,
        False,
        None,
        "lower-bound",
        f"closure truncated at cap {effective_cap}; order >= {floor} "
        "— a partial-enumeration floor, so it can sit BELOW an order another "
        "column certifies exactly (the fold group is a subgroup of this one): "
        "read it as 'at least', never as a measurement of the group",
    )


def single_matching_fullness(
    code: CSSCode,
    name: str | None = None,
    *,
    involution_cap: int = 16,
    seed: int = 7,
    closure_cap: int = 4_000_000,
    time_budget_s: float = 300.0,
) -> dict[str, Any]:
    """Does *one* matching already suffice, or is varying them necessary?

    :func:`analyze_one_block` answers whether the union of every certified
    depth-one layer reaches ``Sp(2k, 2)``, but not how few matchings that
    took — and the distinction is the whole point of the
    Chakraborty-Gottesman discussion.  This routine tests each certified
    matching *on its own*: strict layers plus Tanner automorphism gates plus
    the fold layers of that single involution.

    A ``True`` verdict does not contradict arXiv:2602.13395.  That theorem
    bounds gadget sets built on ONE fixed partition, which are closed under
    composition; adding automorphism gates that fail to normalize the
    involution conjugates its fold layers onto *other* matchings, so the
    generated set is not of fixed partition.  ``normalized`` records, for the
    witnessing involution, whether each automorphism generator normalizes it
    — an all-``True`` list would be the case that genuinely needs explaining.

    Returns ``single_matching_full`` (``None`` when nothing could be decided
    inside the budget), the number of matchings tried, and the witness label.
    """

    deadline = time.perf_counter() + time_budget_s
    strict = code.analyze_transversal()
    strict_gens = [
        g.logical_symplectic
        for g in strict.generators
        if all(g.certificate.values()) and not g.is_logical_identity
    ] if strict.certified else []

    aut = None
    aut_gens: list[np.ndarray] = []
    if analyze_automorphisms is not None:
        try:
            aut = analyze_automorphisms(code)
            if aut.certified:
                aut_gens = [
                    g.logical_symplectic for g in aut.generators if all(g.certificate.values())
                ]
        except ImportError:  # pragma: no cover - optional dependency
            aut = None

    target = symplectic_group_order(code.k)
    base = strict_gens + aut_gens
    if base and generated_group_order(base, cap=closure_cap).order == target:
        return {
            "single_matching_full": True,
            "matchings_tried_singly": 0,
            "witness": "strict + automorphisms alone",
            "normalized": None,
        }

    involutions = _collect_involutions(
        code, name, aut, involution_cap=involution_cap, seed=seed, extra_taus=None
    )
    tried = 0
    for label, tau in involutions:
        if time.perf_counter() > deadline:
            return {
                "single_matching_full": None,
                "matchings_tried_singly": tried,
                "witness": "time budget exhausted",
                "normalized": None,
            }
        matching = analyze_matching(code, tau)
        if not matching.certified:
            continue
        fold = [
            g.logical_symplectic
            for g in matching.generators
            if all(g.certificate.values())
        ]
        if matching.fold_hadamard is not None and all(matching.fold_hadamard.certificate.values()):
            fold.append(matching.fold_hadamard.logical_symplectic)
        if not fold:
            continue
        tried += 1
        result = generated_group_order(base + fold, cap=closure_cap)
        if result.exact and result.order == target:
            normalized = None
            if aut is not None:
                tau_array = np.asarray(tau, dtype=int)
                normalized = []
                for generator in aut.generators:
                    permutation = np.asarray(generator.qubit_permutation, dtype=int)
                    conjugate = np.empty_like(tau_array)
                    for qubit in range(tau_array.size):
                        conjugate[permutation[qubit]] = permutation[tau_array[qubit]]
                    normalized.append(bool(np.array_equal(conjugate, tau_array)))
            return {
                "single_matching_full": True,
                "matchings_tried_singly": tried,
                "witness": label,
                "normalized": normalized,
            }
    return {
        "single_matching_full": False,
        "matchings_tried_singly": tried,
        "witness": None,
        "normalized": None,
    }



def factor_target(analysis: OneBlockAnalysis, target: np.ndarray) -> dict[str, Any] | None:
    """Factor ``target`` (a ``2k x 2k`` logical symplectic matrix) into an
    explicit word in the collected depth-one layers, or return ``None``.

    The word-tracking Schreier-Sims chain is cross-checked against the
    independent order engine before use (an internal error is raised on any
    mismatch), and the returned word is verified by recomposition, so a
    reported factorization is always correct and ``None`` is a certified
    non-membership.  Words may be long; ``length`` records the cost honestly.
    """

    code = analysis.code
    if code.k > 8:
        raise ValueError("factor_target supports k <= 8")
    target = (np.asarray(target, dtype=np.uint8) & 1).copy()
    if target.shape != (2 * code.k, 2 * code.k):
        raise ValueError(f"target must be {2 * code.k} x {2 * code.k}")
    if not is_symplectic(target, qubits=code.k):
        raise ValueError("target must be symplectic")
    if not analysis.generators:
        if np.array_equal(target, np.eye(2 * code.k, dtype=np.uint8)):
            return {"found": True, "word": [], "length": 0, "provenance": [], "verified": True}
        return None

    if analysis._bsgs is None:
        matrices = [record.matrix for record in analysis.generators]
        bsgs = WordBSGS(matrices)
        independent = schreier_sims_order(matrices)
        if independent is not None and bsgs.order() != independent:
            raise AssertionError("internal error: word chain and order engine disagree")
        if analysis.logical_order_exact and analysis.logical_order is not None:
            if bsgs.order() != analysis.logical_order:
                raise AssertionError("internal error: word chain disagrees with certified order")
        analysis._bsgs = bsgs
    bsgs = analysis._bsgs

    word = bsgs.factor(target)
    if word is None:
        return None
    recomposed = bsgs.word_product(word)
    if not np.array_equal(recomposed, target):
        raise AssertionError("internal error: recomposition of the synthesis word failed")
    return {
        "found": True,
        "word": word,
        "length": len(word),
        "provenance": [analysis.generators[index].provenance for index in word],
        "verified": True,
    }
