r"""Certified fullness for large ``k``: the McLaughlin transvection route.

Deciding ``G = Sp(2k, 2)`` by computing ``|G|`` becomes infeasible well before
``k = 20``, yet fullness is exactly the question a transversal-gate census
wants answered.  This module implements a *recognition* certificate instead of
an order computation, based on McLaughlin's classification of irreducible
groups generated by symplectic transvections: a transvection-generated group
acting irreducibly, with a transvection-direction orbit spanning the space and
no invariant quadratic form, is the full symplectic group unless it is one of
the excluded symmetric-group cases -- which are ruled out by an exact
element-order argument (:func:`..utils.permutations._symmetric_group_element_orders`).

Every sub-certificate is exact.  The verdict is ``"full"`` (certified),
``"not-full"`` (a *verified* invariant subspace or quadratic form excludes
fullness), or ``"inconclusive"`` -- never a guess.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from math import gcd
from typing import Any

import numpy as np

from ..utils.gf2 import (
    gf2_inverse,
    gf2_matmul,
    nullspace,
    rank,
    row_basis,
    rowspace_residues,
)
from ..utils.permutations import _symmetric_group_element_orders
from ..utils.polynomials import (
    _pdeg,
    _pfactors,
    _poly_eval_matrix,
    _ppowmod,
    _vector_minpoly,
)
from ..utils.symplectic import (
    _transvection_direction,
    is_symplectic,
    symplectic_group_order,
    symplectic_transvection,
)


@dataclass(frozen=True)
class RecognitionReport:
    """Outcome of the transvection-recognition certificate.

    ``verdict`` is ``"full"`` (G = Sp(2k,2), certified), ``"not-full"``
    (a verified invariant subspace or quadratic form excludes fullness), or
    ``"inconclusive"`` (some sub-certificate could not be established —
    never a wrong answer, only an honest failure).
    """

    verdict: str
    checks: dict[str, Any]
    detail: str


def _shear_transvection(
    gens: list[np.ndarray], rng: np.random.Generator, deadline: float
) -> tuple[np.ndarray, np.ndarray] | None:
    """Exact transvection search inside the abelian shear families.

    Layers of the form ``[[I, S], [0, I]]`` (Z-type) commute and compose by
    adding their symmetric blocks, and ``S = b b^T`` is exactly the
    symplectic transvection ``t_(0|b)``; dually ``[[I, 0], [T, I]]`` with
    ``T = a a^T`` is ``t_(a|0)``.  Whether some GF(2) combination of the
    reachable shear blocks equals a chosen rank-one target is a *linear*
    question, so shear-rich groups (the depth-one layers collected here are
    mostly shears) yield certified transvections by exact solves instead of
    random search.

    The reachable shear spaces are first enriched by conjugation: for any
    group element ``w``, ``w^-1 [[I,S],[0,I]] w`` is again a group element,
    and whenever it happens to be a shear its block joins the span.  Every
    basis element carries the explicit conjugated group element, so the
    returned transvection is a verified product of generators (a product of
    commuting shear elements of G, checked against the closed form).
    """

    two_k = gens[0].shape[0]
    k = two_k // 2
    identity = np.eye(two_k, dtype=np.uint8)
    identity_k = np.eye(k, dtype=np.uint8)
    symmetric_dim = k * (k + 1) // 2

    def classify(matrix: np.ndarray) -> tuple[str | None, np.ndarray | None]:
        a, b, c, d = matrix[:k, :k], matrix[:k, k:], matrix[k:, :k], matrix[k:, k:]
        if np.array_equal(a, identity_k) and np.array_equal(d, identity_k):
            if not c.any():
                return "U", b
            if not b.any():
                return "L", c
        return None, None

    # span basis per family: parallel lists of (block, group element)
    blocks: dict[str, list[np.ndarray]] = {"U": [], "L": []}
    elements: dict[str, list[np.ndarray]] = {"U": [], "L": []}
    pivots: dict[str, list[int]] = {"U": [], "L": []}
    echelon: dict[str, list[np.ndarray]] = {"U": [], "L": []}

    def basis_add(kind: str, block: np.ndarray, element: np.ndarray) -> bool:
        reduced = block.reshape(-1).copy()
        for row, pivot in zip(echelon[kind], pivots[kind]):
            if reduced[pivot]:
                reduced ^= row
        support = np.flatnonzero(reduced)
        if support.size == 0:
            return False
        blocks[kind].append(block.copy())
        elements[kind].append(element.copy())
        echelon[kind].append(reduced)
        pivots[kind].append(int(support[0]))
        return True

    for g in gens:
        kind, block = classify(g)
        if kind is not None and not np.array_equal(g, identity):
            basis_add(kind, block, g)
    if not blocks["U"] and not blocks["L"]:
        return None

    # conjugation enrichment by single generators (systematic) ...
    inverses = [gf2_inverse(g) for g in gens]
    queue = list(elements["U"]) + list(elements["L"])
    while queue and time.perf_counter() < deadline:
        element = queue.pop()
        for g, g_inv in zip(gens, inverses):
            conjugate = gf2_matmul(gf2_matmul(g_inv, element), g)
            kind, block = classify(conjugate)
            if kind is not None and basis_add(kind, block, conjugate):
                queue.append(conjugate)
    # ... then by random generator words, catching conjugators whose
    # intermediate conjugates leave the shear families.  The patience scales
    # with the target dimension: high-k spans need thousands of successful
    # additions before the rank-one solve can succeed.
    stall = 0
    stall_limit = max(300, symmetric_dim)
    while stall < stall_limit and time.perf_counter() < deadline:
        if len(blocks["U"]) >= symmetric_dim and len(blocks["L"]) >= symmetric_dim:
            break
        word = identity
        for _ in range(int(rng.integers(1, 7))):
            word = gf2_matmul(word, gens[int(rng.integers(0, len(gens)))])
        word_inv = gf2_inverse(word)
        kind = "U" if (blocks["U"] and (not blocks["L"] or rng.integers(2))) else "L"
        element = elements[kind][int(rng.integers(0, len(elements[kind])))]
        conjugate = gf2_matmul(gf2_matmul(word_inv, element), word)
        new_kind, block = classify(conjugate)
        if new_kind is not None and basis_add(new_kind, block, conjugate):
            stall = 0
        else:
            stall += 1

    for kind in ("U", "L"):
        if not blocks[kind]:
            continue
        flat = np.asarray([block.reshape(-1) for block in blocks[kind]], dtype=np.uint8)
        targets = [identity_k[i] for i in range(k)]
        targets += [
            identity_k[i] ^ identity_k[j]
            for i in range(min(k, 12))
            for j in range(i + 1, min(k, 12))
        ]
        for _ in range(16):
            random_target = rng.integers(0, 2, size=k).astype(np.uint8)
            if random_target.any():
                targets.append(random_target)
        for b_vec in targets:
            goal = np.outer(b_vec, b_vec).astype(np.uint8).reshape(-1)
            solution = _solve_gf2_system(flat.T, goal)
            if solution is None:
                continue
            product = identity.copy()
            for index in np.flatnonzero(solution):
                product = gf2_matmul(product, elements[kind][int(index)])
            if kind == "U":
                direction = np.concatenate([np.zeros(k, dtype=np.uint8), b_vec])
            else:
                direction = np.concatenate([b_vec, np.zeros(k, dtype=np.uint8)])
            if np.array_equal(product, symplectic_transvection(direction)):
                return product, direction
    return None


def _find_transvection(
    gens: list[np.ndarray], rng: np.random.Generator, deadline: float
) -> tuple[np.ndarray, np.ndarray] | None:
    """Search for an explicit transvection among products of the generators.

    Every candidate is a verified product of group generators, so membership
    in G is certified by construction.  The exact shear-family solve of
    :func:`_shear_transvection` runs first; the fallback candidates are the
    generators, pairwise products, short random words, and small powers of
    each (catching elements that power into a transvection).
    """

    two_k = gens[0].shape[0]
    identity = np.eye(two_k, dtype=np.uint8)

    from_shears = _shear_transvection(gens, rng, deadline)
    if from_shears is not None:
        return from_shears

    def scan(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray] | None:
        power = matrix.copy()
        for _ in range(32):
            if np.array_equal(power, identity):
                return None
            direction = _transvection_direction(power)
            if direction is not None:
                return power, direction
            power = gf2_matmul(power, matrix)
        return None

    for g in gens:
        found = scan(g)
        if found is not None:
            return found
    if len(gens) <= 24:
        for i, a in enumerate(gens):
            for b in gens[i + 1 :]:
                found = scan(gf2_matmul(a, b))
                if found is not None:
                    return found
                if time.perf_counter() > deadline:
                    return None
    for _ in range(300):
        if time.perf_counter() > deadline:
            return None
        length = int(rng.integers(2, 7))
        word = identity
        for _ in range(length):
            word = gf2_matmul(word, gens[int(rng.integers(0, len(gens)))])
        found = scan(word)
        if found is not None:
            return found
    return None


def _direction_orbit(
    seed: np.ndarray, gens: list[np.ndarray], *, cap: int
) -> tuple[list[np.ndarray], bool]:
    """Partial orbit of ``seed`` under right multiplication by the generators.

    Every returned vector ``w`` satisfies ``w = seed * g`` for a word ``g``
    in the generators, so ``t_w = g^-1 t_seed g`` lies in G (conjugates of a
    symplectic transvection by symplectic maps are transvections in the
    image direction).  The boolean reports whether the orbit closed.
    """

    seen = {seed.tobytes()}
    orbit = [seed]
    cursor = 0
    while cursor < len(orbit):
        current = orbit[cursor]
        cursor += 1
        for g in gens:
            image = gf2_matmul(current[None, :], g)[0]
            key = image.tobytes()
            if key not in seen:
                seen.add(key)
                orbit.append(image)
                if len(orbit) >= cap:
                    return orbit, False
    return orbit, True


def _spin_span(
    seed: np.ndarray, directions: list[np.ndarray], *, transpose: bool
) -> np.ndarray:
    """Smallest transvection-invariant subspace containing ``seed``.

    Forward action of ``t_w``: ``x -> x + <x, w> w``.  Transposed (dual)
    action: ``x -> x + (x . w) (J w)``.  Returns a row basis; spinning stops
    early once the span is the full space.
    """

    two_k = seed.shape[0]
    k = two_k // 2
    swapped = [np.concatenate([w[k:], w[:k]]) for w in directions]
    rows: list[np.ndarray] = []
    pivots: list[int] = []

    def add(vector: np.ndarray) -> bool:
        reduced = vector.copy()
        for row, pivot in zip(rows, pivots):
            if reduced[pivot]:
                reduced ^= row
        support = np.flatnonzero(reduced)
        if support.size == 0:
            return False
        pivot = int(support[0])
        for index, row in enumerate(rows):
            if row[pivot]:
                rows[index] = row ^ reduced
        rows.append(reduced)
        pivots.append(pivot)
        return True

    queue = [seed]
    add(seed)
    while queue and len(rows) < two_k:
        current = queue.pop()
        for w, jw in zip(directions, swapped):
            if transpose:
                coefficient = int(current @ w) & 1
                image = current ^ jw if coefficient else None
            else:
                coefficient = int(current @ jw) & 1
                image = current ^ w if coefficient else None
            if image is not None and add(image):
                queue.append(image)
                if len(rows) == two_k:
                    break
    return np.asarray(rows, dtype=np.uint8)


def _transvection_invariant(basis: np.ndarray, directions: list[np.ndarray]) -> bool:
    """Exact check that a row space is invariant under every ``t_w``."""

    if basis.shape[0] == 0:
        return True
    two_k = basis.shape[1]
    k = two_k // 2
    for w in directions:
        jw = np.concatenate([w[k:], w[:k]])
        coefficients = gf2_matmul(basis, jw[:, None])[:, 0]
        images = basis ^ (coefficients[:, None] & w[None, :])
        if rowspace_residues(images, basis).any():
            return False
    return True


def _matrix_invariant(basis: np.ndarray, gens: list[np.ndarray]) -> bool:
    """Exact check that a row space is invariant under every generator."""

    if basis.shape[0] == 0:
        return True
    for g in gens:
        if rowspace_residues(gf2_matmul(basis, g), basis).any():
            return False
    return True


def _norton_irreducibility(
    directions: list[np.ndarray],
    two_k: int,
    rng: np.random.Generator,
    deadline: float,
    *,
    attempts: int = 24,
) -> dict[str, Any]:
    """Certified irreducibility (and endomorphism field) of the transvection
    module, or a verified invariant subspace.

    Norton's criterion (Holt-Rees, "Testing modules for irreducibility",
    J. Austral. Math. Soc. 57 (1994); Holt-Eick-O'Brien, Handbook of CGT
    §7.4), in the multiplicity-one form used here.  Let ``A`` lie in the
    enveloping algebra of the acting group, ``theta`` an irreducible
    polynomial with ``N = null theta(A)`` of dimension exactly
    ``deg theta``, and ``N' = null theta(A)^T`` (the dual-module null space).
    If one nonzero ``v in N`` spins (under the group) to the whole space and
    one nonzero ``f in N'`` spins under the transposed action to the whole
    dual space, the module is irreducible.  Proof sketch, fully re-derived
    for this implementation: a proper submodule ``W`` either meets ``N`` — but
    any ``v' in N`` generates ``N`` over ``F_2[A]`` (dim N = deg theta makes
    ``N`` an irreducible ``F_2[A]``-module), so ``spin(v') >= spin(v) = V``,
    contradiction — or misses it, in which case ``theta(A)`` is a bijection
    of ``W``, so ``W`` lies inside ``im theta(A)`` and the annihilator of
    ``W`` meets ``N' = (im theta(A))^0`` nontrivially, giving the dual
    contradiction.  Every claimed invariant subspace is re-verified exactly,
    so a false "reducible" is impossible.

    The witness degrees also certify the endomorphism field: ``End(V)`` embeds
    into ``End_{F_2[A]}(N) ~ F_2^(deg theta)`` (restriction to ``N`` is
    injective by Schur's lemma), so ``End(V) = F_2`` once witness degrees with
    gcd 1 are found — the absolute-irreducibility certificate used by the
    invariant-form argument.

    Returns a dict with ``status`` in ``{"abs_irreducible", "reducible",
    "unknown"}`` plus ``subspace`` (verified basis) or ``witness_degrees``.
    """

    witness_degrees: list[int] = []
    # sample directions across the whole partial orbit: breadth-first
    # prefixes are nearly parallel and generate degenerate algebra elements
    sample_size = min(len(directions), max(128, two_k))
    chosen = rng.choice(len(directions), size=sample_size, replace=False)
    matrices = [symplectic_transvection(directions[int(i)]) for i in chosen]
    for _ in range(attempts):
        if time.perf_counter() > deadline:
            break
        # Terms must be *long* products: a product of r transvections is
        # I + (rank <= r), so short terms give algebra elements whose
        # nontrivial factors never reach nullity = degree at large 2k.
        algebra_element = np.zeros((two_k, two_k), dtype=np.uint8)
        for _ in range(int(rng.integers(2, 5))):
            term = np.eye(two_k, dtype=np.uint8)
            for _ in range(int(rng.integers(max(1, two_k // 2), two_k + 1))):
                term = gf2_matmul(term, matrices[int(rng.integers(0, len(matrices)))])
            algebra_element ^= term
        probe = rng.integers(0, 2, size=two_k).astype(np.uint8)
        if not probe.any():
            continue
        annihilator = _vector_minpoly(algebra_element, probe)
        for theta in _pfactors(annihilator, rng):
            degree = _pdeg(theta)
            evaluated = _poly_eval_matrix(theta, algebra_element)
            null_rows = nullspace(evaluated.T)  # {x : x theta(A) = 0}
            if null_rows.shape[0] != degree:
                continue
            null_dual = nullspace(evaluated)  # {f : theta(A) f^T = 0}
            if null_dual.shape[0] != degree:
                continue
            span = _spin_span(null_rows[0], directions, transpose=False)
            if span.shape[0] < two_k:
                if 0 < span.shape[0] and _transvection_invariant(span, directions):
                    return {"status": "reducible", "subspace": span}
                continue  # spin bookkeeping failed verification; try another witness
            dual_span = _spin_span(null_dual[0], directions, transpose=True)
            if dual_span.shape[0] < two_k:
                subspace = nullspace(dual_span)  # annihilator of the dual span
                if (
                    0 < subspace.shape[0] < two_k
                    and _transvection_invariant(subspace, directions)
                ):
                    return {"status": "reducible", "subspace": subspace}
                continue
            witness_degrees.append(degree)
            if len(witness_degrees) >= 1:
                overall = witness_degrees[0]
                for d in witness_degrees[1:]:
                    overall = gcd(overall, d)
                if overall == 1:
                    return {
                        "status": "abs_irreducible",
                        "witness_degrees": sorted(set(witness_degrees)),
                    }
    return {"status": "unknown", "witness_degrees": sorted(set(witness_degrees))}


def _canonical_quadratic(matrix: np.ndarray) -> np.ndarray:
    """Canonical (upper-triangular) coefficient matrix of ``x -> x M x^T``.

    Over GF(2), ``x_i^2 = x_i``: the coefficient of ``x_i x_j`` (i < j) is
    ``M_ij + M_ji`` and the coefficient of ``x_i`` is ``M_ii``.
    """

    upper = (np.triu(matrix, 1) ^ np.triu(matrix.T, 1)) & 1
    return (upper ^ np.diag(np.diag(matrix))).astype(np.uint8)


def _solve_gf2_system(system: np.ndarray, rhs: np.ndarray) -> np.ndarray | None:
    """One solution of ``system @ x = rhs`` over GF(2), or ``None``."""

    from ..utils.gf2 import rref

    columns = system.shape[1]
    augmented = np.hstack([system & 1, rhs[:, None] & 1]).astype(np.uint8)
    reduced, pivots = rref(augmented)
    if columns in pivots:
        return None
    solution = np.zeros(columns, dtype=np.uint8)
    for row, pivot in zip(reduced, pivots):
        solution[pivot] = row[columns]
    return solution


def _invariant_quadratic_form(
    directions: list[np.ndarray], two_k: int
) -> np.ndarray | None:
    """A quadratic form polarizing to the symplectic form and invariant under
    every ``t_w`` — or ``None``, certifying that no such form exists.

    Any invariant quadratic form of an absolutely irreducible symplectic
    group has polar form 0 or J (the space of invariant bilinear forms is
    ``Hom_G(V, V*) ~ End_G(V) = F_2``, spanned by J); polar 0 forces a
    G-fixed linear functional, impossible for an irreducible module.  So it
    suffices to search among ``Q_1 + linear`` with ``Q_1`` a fixed form
    polarizing to J: invariance under a symplectic ``g`` reads
    ``(g + I) c = d_g`` with ``d_g`` the diagonal defect of ``Q_1`` under
    ``g`` — a tiny exact linear system.  Callers must hold the absolute
    irreducibility certificate before interpreting ``None`` as the absence of
    *any* nonzero invariant quadratic form.
    """

    k = two_k // 2
    identity = np.eye(two_k, dtype=np.uint8)
    q_one = np.zeros((two_k, two_k), dtype=np.uint8)
    q_one[np.arange(k), k + np.arange(k)] = 1
    blocks: list[np.ndarray] = []
    rhs: list[np.ndarray] = []
    for w in directions:
        t = symplectic_transvection(w)
        moved = _canonical_quadratic(gf2_matmul(gf2_matmul(t, q_one), t.T))
        difference = moved ^ q_one
        if np.triu(difference, 1).any():
            raise AssertionError("internal error: transvection moved the polar form")
        blocks.append(t ^ identity)
        rhs.append(np.diag(difference).astype(np.uint8))
    solution = _solve_gf2_system(np.vstack(blocks), np.concatenate(rhs))
    if solution is None:
        return None
    return (q_one ^ np.diag(solution)).astype(np.uint8)


def _form_invariant_under(form: np.ndarray, gens: list[np.ndarray]) -> bool:
    for g in gens:
        moved = _canonical_quadratic(gf2_matmul(gf2_matmul(g, form), g.T))
        if not np.array_equal(moved, form):
            return False
    return True


def _excludes_symmetric_groups(
    directions: list[np.ndarray],
    two_k: int,
    rng: np.random.Generator,
    deadline: float,
    *,
    attempts: int = 24,
) -> int | None:
    """Certify that the transvection group is not ``S_{2k+1}`` or ``S_{2k+2}``.

    If ``M`` in the group has an irreducible characteristic-polynomial factor
    ``theta`` whose root order (the multiplicative order of ``x`` mod
    ``theta``) is not an element order of ``S_{2k+2}``, the group cannot be
    isomorphic to ``S_{2k+1}`` or ``S_{2k+2}``: the root order divides
    ``ord(M)``, and the element-order set of a symmetric group is closed
    under divisors (a divisor of an lcm of a partition is again such an lcm).
    The root-order test is run against the *exact* order set from
    :func:`_symmetric_group_element_orders`, so the certificate is
    module-independent — it excludes the symmetric groups under any
    isomorphism, not only in their natural representation.  Returns the
    witness degree, or ``None`` when no witness was found (honest failure).
    """

    allowed = _symmetric_group_element_orders(two_k + 2)
    sample_size = min(len(directions), max(128, two_k))
    chosen = rng.choice(len(directions), size=sample_size, replace=False)
    matrices = [symplectic_transvection(directions[int(i)]) for i in chosen]
    for _ in range(attempts):
        if time.perf_counter() > deadline:
            return None
        # Long random products approximate uniform group elements, which for
        # symplectic groups carry high-degree irreducible factors with large
        # root orders; short products only ever move a low-rank subspace.
        element = np.eye(two_k, dtype=np.uint8)
        for _ in range(int(rng.integers(two_k, 3 * two_k + 1))):
            element = gf2_matmul(element, matrices[int(rng.integers(0, len(matrices)))])
        for _ in range(3):
            probe = rng.integers(0, 2, size=two_k).astype(np.uint8)
            if not probe.any():
                continue
            annihilator = _vector_minpoly(element, probe)
            for theta in _pfactors(annihilator, rng):
                if _pdeg(theta) < 2:
                    continue
                if rank(_poly_eval_matrix(theta, element)) == two_k:
                    continue  # not actually a characteristic factor; skip
                if all(_ppowmod(2, order, theta) != 1 for order in allowed):
                    return _pdeg(theta)
    return None


def recognize_full_symplectic(
    generators: list[np.ndarray],
    k: int,
    *,
    seed: int = 11,
    time_budget_s: float = 60.0,
    max_directions: int = 2048,
) -> RecognitionReport:
    """Certified decision of ``<generators> = Sp(2k, 2)`` for large ``k``.

    The route rests on McLaughlin's classification (J. McLaughlin, *Some
    subgroups of SL_n(F_2)*, Illinois J. Math. 13 (1969), 108-115; statement
    verified against the surveys cited in the module tests): an irreducible
    subgroup of ``GL(n, 2)`` generated by transvections is ``SL(n, 2)`` or,
    for even ``n >= 4``, ``Sp(n, 2)``, ``O^+/-(n, 2)``, ``S_{n+1}`` or
    ``S_{n+2}`` on its natural module.  The certificate chain:

    1. every generator is verified symplectic, so ``G <= Sp(2k, 2)``;
    2. an explicit transvection ``t_v`` is exhibited as a verified product of
       generators (``rank(t - I) = 1`` plus exact reconstruction as ``t_v``);
    3. directions ``w = v g`` from the partial G-orbit of ``v`` give a
       transvection-generated subgroup ``T = <t_w> <= G`` (conjugation
       identity ``g^-1 t_v g = t_{v g}`` for symplectic ``g``);
    4. Norton's criterion (:func:`_norton_irreducibility`) certifies that
       ``T`` acts irreducibly and, via witness degrees of gcd 1, that
       ``End(V) = F_2`` — so McLaughlin's list applies to ``T``;
    5. exclusions, each exact: ``SL(2k, 2)`` by cardinality
       (``|SL(2k,2)| > |Sp(2k,2)|`` for ``2k >= 4`` yet ``T`` preserves the
       form); ``O^+/-`` because no nonzero ``T``-invariant quadratic form
       exists (:func:`_invariant_quadratic_form`, sound given step 4);
       ``S_{2k+1}``/``S_{2k+2}`` by the root-order certificate
       (:func:`_excludes_symmetric_groups`);
    6. what remains is ``T = Sp(V, B)`` for an invariant nondegenerate
       alternating form ``B``; by step 4 the only such form is J, so
       ``T = Sp(2k, 2)`` and ``Sp(2k, 2) = T <= G <= Sp(2k, 2)``.

    A verified invariant subspace or quadratic form that survives the *full*
    generator set instead certifies ``is_full = False`` (the natural module
    of ``Sp(2k, 2)`` is irreducible and, for ``k >= 2``, admits no nonzero
    invariant quadratic form).  Anything else returns ``"inconclusive"`` —
    the McLaughlin route never guesses.
    """

    start = time.perf_counter()
    deadline = start + time_budget_s
    checks: dict[str, Any] = {}
    two_k = 2 * k
    if k < 2:
        return RecognitionReport(
            "inconclusive", checks, "recognition needs k >= 2 (the 2k = 2 list degenerates)"
        )
    gens: list[np.ndarray] = []
    identity = np.eye(two_k, dtype=np.uint8)
    for generator in generators:
        matrix = (np.asarray(generator, dtype=np.uint8) & 1).copy()
        if matrix.shape != (two_k, two_k):
            raise ValueError("generators must be 2k x 2k matrices")
        if not is_symplectic(matrix, qubits=k):
            raise ValueError("recognition requires certified symplectic generators")
        if not np.array_equal(matrix, identity):
            gens.append(matrix)
    if not gens:
        return RecognitionReport("inconclusive", checks, "trivial generator set")
    checks["generators_symplectic"] = True

    sl_order = 1
    for i in range(two_k):
        sl_order *= (1 << two_k) - (1 << i)
    checks["sl_excluded_by_cardinality"] = sl_order > symplectic_group_order(k)
    if not checks["sl_excluded_by_cardinality"]:  # pragma: no cover - k >= 2 always passes
        return RecognitionReport("inconclusive", checks, "SL cardinality exclusion failed")

    rng = np.random.default_rng(seed)
    found = _find_transvection(gens, rng, deadline)
    if found is None:
        return RecognitionReport(
            "inconclusive", checks, "no transvection found among generator products"
        )
    _, direction = found
    checks["transvection_exhibited"] = True

    cap = max(4 * two_k, 64)
    while True:
        if time.perf_counter() > deadline:
            return RecognitionReport("inconclusive", checks, "time budget exhausted")
        directions, orbit_closed = _direction_orbit(direction, gens, cap=cap)
        checks["directions_used"] = len(directions)
        # The span of the full orbit of the transvection direction is a
        # G-invariant subspace.  When the collected directions span a proper
        # subspace that is verified invariant under every generator, G is
        # reducible — while Sp(2k,2) acts irreducibly (indeed transitively,
        # by Witt) on nonzero vectors — so fullness is refuted outright.
        # Norton cannot certify anything from a non-spanning direction set,
        # so that case either refutes or forces more orbit.
        span_basis = row_basis(np.asarray(directions, dtype=np.uint8), ncols=two_k)
        checks["direction_span_dim"] = int(span_basis.shape[0])
        if span_basis.shape[0] < two_k:
            if _matrix_invariant(span_basis, gens):
                checks["invariant_subspace_dim"] = int(span_basis.shape[0])
                return RecognitionReport(
                    "not-full",
                    checks,
                    "the transvection-direction orbit spans a verified proper "
                    "G-invariant subspace: G is reducible, but the natural "
                    "Sp(2k,2) module is irreducible",
                )
            if orbit_closed or cap >= max_directions:
                return RecognitionReport(
                    "inconclusive",
                    checks,
                    "direction orbit does not span the module within the cap",
                )
            cap *= 2
            continue
        norton = _norton_irreducibility(directions, two_k, rng, deadline)
        if norton["status"] == "reducible":
            subspace = norton["subspace"]
            if _matrix_invariant(subspace, gens) and 0 < subspace.shape[0] < two_k:
                checks["invariant_subspace_dim"] = int(subspace.shape[0])
                return RecognitionReport(
                    "not-full",
                    checks,
                    "verified proper invariant subspace: G is reducible, but the "
                    "natural Sp(2k,2) module is irreducible",
                )
        elif norton["status"] == "abs_irreducible":
            checks["irreducible"] = True
            checks["norton_witness_degrees"] = norton["witness_degrees"]
            checks["endomorphism_field_is_F2"] = True
            form = _invariant_quadratic_form(directions, two_k)
            if form is None:
                checks["no_invariant_quadratic_form"] = True
                if two_k == 4:
                    # Exceptional isomorphisms collapse the 2k = 4 list:
                    # S_6 ~ Sp(4,2) (its natural module IS the symplectic
                    # module, so that case is already fullness) and
                    # S_5 ~ O^-(4,2) preserves a quadratic form (for odd m
                    # the deleted permutation module carries the invariant
                    # form Q(v) = wt(v)/2 mod 2 polarizing to the dot
                    # product), so the no-form certificate above excludes
                    # it.  No separate symmetric exclusion exists or is
                    # needed at this dimension.
                    checks["symmetric_groups_excluded"] = "exceptional isomorphisms at 2k=4"
                    return RecognitionReport(
                        "full",
                        checks,
                        "McLaughlin classification at 2k = 4: SL and O^+/- excluded, "
                        "S_5 ~ O^-(4,2) excluded with them, S_6 ~ Sp(4,2); T = Sp(4,2) <= G",
                    )
                witness = _excludes_symmetric_groups(directions, two_k, rng, deadline)
                if witness is not None:
                    checks["symmetric_groups_excluded"] = True
                    checks["symmetric_witness_degree"] = witness
                    return RecognitionReport(
                        "full",
                        checks,
                        "McLaughlin classification: irreducible transvection subgroup "
                        "with SL, O^+/-, S_{2k+1}, S_{2k+2} excluded; T = Sp(2k,2) <= G",
                    )
                return RecognitionReport(
                    "inconclusive", checks, "could not exclude S_{2k+1}/S_{2k+2}"
                )
            if _form_invariant_under(form, gens):
                checks["invariant_quadratic_form"] = True
                return RecognitionReport(
                    "not-full",
                    checks,
                    "verified G-invariant quadratic form polarizing to J: G lies in an "
                    "orthogonal group, but Sp(2k,2) (k >= 2) fixes no nonzero form",
                )
        if orbit_closed or cap >= max_directions:
            return RecognitionReport(
                "inconclusive",
                checks,
                "certificates did not stabilize within the direction-orbit cap",
            )
        cap *= 2
