"""Fixed-partition staircase vs varying-partition group, both exhaustive.

For a code and width cap W:
  fixed  : max over ALL partitions of width <= W of the exact logical image order
  varying: order of the group generated by the logical images of ALL of them
Both are exhaustive over the partition set, so 'short of |Sp(2k,2)|' is a
certified negative for the ansatz, not a sampling artefact.
"""
import sys, time, json
from staircase import partitions_max_cell
from qec_transversal.codes.registry import REGISTRY
from qec_transversal.codes.css import CSSCode
from qec_transversal.api import partition_clifford_group, Completeness
from qec_transversal.utils.symplectic import symplectic_group_order
from qec_transversal.logical.group import schreier_sims_order


def run(name, w):
    entry = REGISTRY[name]
    code = CSSCode(*entry.build())
    k = code.k
    target = symplectic_group_order(k)
    best, best_p, bad = 1, None, []
    pool, seen = [], set()
    t0 = time.time()
    total = 0
    for p in partitions_max_cell(code.n, w):
        total += 1
        r = partition_clifford_group(code, p)
        if r.completeness is not Completeness.COMPLETE or not r.logical_group_order_is_exact:
            bad.append(p)
        order = r.logical_group_order or 1
        if order > best:
            best, best_p = order, p
        for g in r.logical_generators:
            key = g.astype(int).tobytes()
            if key not in seen:
                seen.add(key)
                pool.append(g)
    varying = schreier_sims_order(pool) if pool else 1
    dt = time.time() - t0
    print(f"{name:10s} [[{entry.n},{entry.k},{entry.d}]] width<={w}  "
          f"partitions={total}  fixed_best={best}  varying={varying}  "
          f"|Sp(2k,2)|={target}  fixed={'FULL' if best==target else 'SHORT'}  "
          f"varying={'FULL' if varying==target else 'SHORT'}  "
          f"non_exact={len(bad)}  {dt:.1f}s", flush=True)
    print(f"           argmax: {best_p}", flush=True)
    return dict(name=name, n=entry.n, k=k, d=entry.d, width=w, partitions=total,
                fixed_best=best, varying=varying, target=target,
                non_exact=len(bad), seconds=dt)


if __name__ == "__main__":
    out = []
    for arg in sys.argv[1:]:
        nm, w = arg.split(":")
        out.append(run(nm, int(w)))
    print(json.dumps(out))
