"""One-block Clifford analysis over *varying* partitions and dualities.

Chakraborty-Gottesman (arXiv:2602.13395) prove that gadget sets built on one
FIXED partition or duality — sets closed under composition, hence constant
depth — can never realize the full logical Clifford group ``Sp(2k, 2)`` of a
single code block (strict transversality and code automorphisms for k >= 2,
bare permutations even for k = 1, fixed-duality fold gates for k >= 3).  The
same paper points out the loophole: depth-one fold-transversal layers over
*varying* partitions/dualities are not closed under composition, and their
compositions (non-constant-depth circuits of depth-one layers with error
correction in between) may generate everything.  arXiv:2602.09788 proves
exactly that for the middle Reed-Muller family ``RM(m/2-1, m)`` (the
registry's ``tesseract``, ``rm64``, ``rm256``): transversal plus varying-fold
gates generate the full addressable logical Clifford group on one block.

This module decides that question *per code*: it collects every certified
depth-one one-block layer the repository knows how to certify —

* strict transversal shears (:meth:`CSSCode.analyze_transversal`),
* diagonal fold layers ``S_M^Z`` / ``S_M^X`` and the fold-Hadamard for every
  certified involution (:mod:`.matching`), the involutions coming from the
  structural candidates of :mod:`.dualities`, the BLISS-discovered involutive
  duality, and involutions sampled from the Tanner automorphism group
  (:func:`.twofold.automorphism_involutions`),
* SWAP-class permutation gates from Tanner-graph automorphism generators
  (:mod:`.automorphisms`),

then certifies the group generated by their logical symplectic images
against ``|Sp(2k, 2)|``.  Certification tiers, chosen automatically:

``closure``
    Breadth-first element enumeration (:func:`.group.generated_group_order`)
    when it completes under a cap — exact at any ``k``.
``exact-order``
    Deterministic Schreier-Sims (:func:`.group.schreier_sims_order`) for
    moderate ``k``, compared with ``|Sp(2k, 2)|``.
``recognition``
    For large ``k``, a certified recognition route based on McLaughlin's
    classification of transvection groups (see
    :func:`recognize_full_symplectic`).  Every sub-certificate is exact; if
    any step fails the result downgrades instead of guessing.
``lower-bound``
    The honest fallback: the truncated closure count as a lower bound,
    ``is_full`` undecided.
``skipped``
    Nothing could be certified inside the time budget.

Every generator's logical action is taken only from certified analyses, so a
wrong exact answer is impossible; at worst the verdict is undecided.

Synthesis: :func:`factor_target` factors a target logical symplectic matrix
into an explicit word in the collected depth-one layers via a word-tracking
Schreier-Sims chain, with the chain's completeness cross-checked against the
independent order engine and every returned word verified by recomposition.

Known limits (deliberate, and load-bearing for how results may be quoted):

``is_full`` is one-sided.
    ``True`` is a certificate.  There is no ``False``: a code admits
    exponentially many involutions and this engine samples them, so a group
    short of the target means "the layers found do not suffice", never "the
    code cannot" — such rows report an exact order for the collected
    generating set with ``is_full`` undecided, i.e. a *lower bound* on the
    code's one-block group.
Orders are modulo Pauli.
    Generators are certified at the symplectic/GF(2) level: :mod:`.matching`
    checks that each stabilizer row's image lies in the stabilizer row space,
    not that it returns with sign ``+1``.  Sign defects form a character on
    the stabilizer group and are always killable by a Pauli, so the group
    orders are unaffected — but only the strict diagonal generators are
    actually run through the sign-exact Stim verifier (:mod:`.phase`); fold,
    permutation and partition layers are not.
Fold layers come from certified *matchings*, not only ZX dualities.
    :attr:`MatchingAnalysis.certified` does not require ``is_zx_duality``; a
    matching whose kernels certify contributes a legitimate depth-one layer
    either way.
The Levi (CNOT-network) units are NOT collected.
    Albert's fixed-matching group is ``N_M = <S_M^Z, S_M^X, L_M>``; this
    module takes only what :func:`.matching.analyze_matching` returns — the
    two diagonal families and the fold-Hadamard — so the Levi factor
    ``L_M`` (implemented in :mod:`.twofold`) is absent from every matching.
    Together with the permutation gates, which ``N_2fold`` does not contain,
    that makes this group and Albert's *incomparable*: neither contains the
    other, and an order above or below a published two-fold number is
    evidence about neither.
``factor_target`` is narrower than the order engine.
    Word-tracking chain construction currently fails past ``k >= 6`` and is
    refused outright for ``k > 8``, so the tesseract full-``Sp(12,2)`` result
    is certified but not yet convertible into an explicit circuit.  Generator
    provenance also records a label and involution index rather than the
    physical layer parameter, so a returned word is not yet directly
    executable on hardware.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from math import gcd
from typing import Any

import numpy as np

from .css import CSSCode
from .discovery import discover_involutions, structural_permutations
from .dualities import candidates_for
from .gf2 import (
    gf2_inverse,
    gf2_matmul,
    is_symplectic,
    nullspace,
    rank,
    row_basis,
    rowspace_residues,
)
from .group import (
    _apply,
    _pack_rows,
    generated_group_order,
    schreier_sims_order,
    symplectic_group_order,
)
from .matching import analyze_matching
from .twofold import automorphism_involutions

try:  # pragma: no cover - exercised through the automorphisms import guard
    from .automorphisms import analyze_automorphisms, describe_permutation
except ImportError:  # pragma: no cover
    analyze_automorphisms = None
    describe_permutation = None
try:  # pragma: no cover - same igraph guard as the automorphisms module
    from .codewordaut import analyze_codeword_automorphisms
except ImportError:  # pragma: no cover
    analyze_codeword_automorphisms = None

#: characteristic-set enumeration is 2^rank: decline above this row-space rank.
_CODEWORD_AUT_RANK_CAP = 23
#: and keep the incidence graph modest in a sweep.
_CODEWORD_AUT_N_CAP = 256

#: Schreier-Sims is attempted at or below this k.  The chain's cost is the
#: node budget, not the dimension (matching.logical_group_summary certifies a
#: k = 18 census group of order 1,524,096 in ~16 s), so this reaches to the
#: largest k where moderate orders remain realistic; the budgets stay the
#: guard against groups that are genuinely too big.
_EXACT_ORDER_K_LIMIT = 18

#: The stabilizer chain runs to its own node budget and cannot be cut short by
#: the caller's deadline, so the budget is what scales: full only when the
#: group is already known small (closure completed) or k is trivially tiny.
_SCHREIER_TRIVIAL_K = 4

#: The all-generator chain is affordable only for small generating sets; past
#: this, fullness is decided by subsets (sound, since fullness is monotone) and
#: everything else falls through to a bounded lower bound.
_CHAIN_GENERATOR_LIMIT = 32

#: Past this k the stabilizer chain's orbits (up to 2^{2k} points per level)
#: make it slower than the recognition route, which runs first instead.
_CHAIN_CHEAP_K = 6
#: ...except for generating sets this small, where the chain is still the
#: cheapest way to pin a proper subgroup's exact order.  Sized from the data:
#: the bicycle codes carry 9-14 certified generators and chain in seconds,
#: while the pathological cases (grid-4x6: 270) are far above any threshold.
#: Too low a limit is not merely slow but misleading — bb72 at 14 generators
#: fell through to a truncated closure and reported a floor of 35,715, below
#: the 276,480 its own fold column already proves.
_CHAIN_SPARSE_LIMIT = 18

#: Matrix products the closure tier may spend on one code (element cap times
#: generator count), so a wide generating set cannot silently cost minutes.
_CLOSURE_WORK_BUDGET = 500_000
_SCHREIER_NODE_BUDGET = 2_000_000
_SCHREIER_TIGHT_BUDGET = 250_000

#: Closure enumeration stores dense 2k x 2k matrices; above this k the cap is
#: tightened so a huge-k code cannot exhaust memory before giving up.
_CLOSURE_DENSE_K_LIMIT = 32
_CLOSURE_TIGHT_CAP = 5_000

#: Memory the closure tier may spend on one code.  An element cap alone is not
#: a bound: a stored element is a dense ``2k x 2k`` uint8 matrix *and* its bytes
#: key, so at k = 580 (``apm1152``) five thousand elements would authorize
#: ~13 GB and the sweep thrashes instead of failing over to the next tier.
#: Converting the budget into an element count keeps every k in the same
#: envelope and makes the tier fail fast into ``lower-bound`` where it must.
_CLOSURE_MEMORY_BUDGET_BYTES = 256 << 20


def _memory_safe_closure_cap(k: int, requested: int) -> int:
    """Element cap for the closure tier that respects the memory envelope."""

    if k <= 0:
        return requested
    per_element = 2 * (2 * k) ** 2  # the matrix plus its bytes key
    affordable = max(64, _CLOSURE_MEMORY_BUDGET_BYTES // per_element)
    return int(min(requested, affordable))


# ---------------------------------------------------------------------------
# GF(2)[x] polynomials as integer bitmasks (bit i = coefficient of x^i)
# ---------------------------------------------------------------------------


def _pdeg(p: int) -> int:
    return p.bit_length() - 1


def _pmul(a: int, b: int) -> int:
    r = 0
    while b:
        if b & 1:
            r ^= a
        a <<= 1
        b >>= 1
    return r


def _pmod(a: int, m: int) -> int:
    dm = _pdeg(m)
    while _pdeg(a) >= dm:
        a ^= m << (_pdeg(a) - dm)
    return a


def _pdivmod(a: int, m: int) -> tuple[int, int]:
    q = 0
    dm = _pdeg(m)
    while _pdeg(a) >= dm:
        shift = _pdeg(a) - dm
        q ^= 1 << shift
        a ^= m << shift
    return q, a


def _pgcd(a: int, b: int) -> int:
    while b:
        a, b = b, _pmod(a, b)
    return a


def _ppowmod(base: int, exponent: int, mod: int) -> int:
    result = _pmod(1, mod) if _pdeg(mod) == 0 else 1
    base = _pmod(base, mod)
    while exponent:
        if exponent & 1:
            result = _pmod(_pmul(result, base), mod)
        base = _pmod(_pmul(base, base), mod)
        exponent >>= 1
    return result


def _pderiv(a: int) -> int:
    # d/dx sum a_i x^i = sum over odd i of a_i x^(i-1) over GF(2)
    result = 0
    for i in range(1, a.bit_length(), 2):
        if (a >> i) & 1:
            result |= 1 << (i - 1)
    return result


def _psqrt(a: int) -> int:
    """Square root of a perfect square over GF(2) (coefficients at even powers)."""

    result = 0
    i = 0
    while (a >> (2 * i)) != 0:
        if (a >> (2 * i)) & 1:
            result |= 1 << i
        i += 1
    return result


def _primes_up_to(limit: int) -> list[int]:
    sieve = np.ones(limit + 1, dtype=bool)
    sieve[:2] = False
    for p in range(2, int(limit**0.5) + 1):
        if sieve[p]:
            sieve[p * p :: p] = False
    return [int(p) for p in np.flatnonzero(sieve)]


def _pirreducible(p: int) -> bool:
    """Rabin's deterministic irreducibility test over GF(2)."""

    d = _pdeg(p)
    if d <= 0:
        return False
    if d == 1:
        return True
    x = 2
    # x^(2^d) mod p must equal x
    frob = x
    for _ in range(d):
        frob = _pmod(_pmul(frob, frob), p)
    if frob != _pmod(x, p):
        return False
    for q in {prime for prime in _primes_up_to(d) if d % prime == 0}:
        e = d // q
        frob = x
        for _ in range(e):
            frob = _pmod(_pmul(frob, frob), p)
        if _pdeg(_pgcd(frob ^ x, p)) != 0:
            return False
    return True


def _equal_degree_split(product: int, degree: int, rng: np.random.Generator) -> list[int]:
    """Cantor-Zassenhaus splitting of a product of degree-``degree`` factors."""

    if _pdeg(product) == degree:
        return [product]
    total = _pdeg(product)
    for _ in range(64):
        coefficients = rng.integers(0, 2, size=total)
        bits = 0
        for index in np.flatnonzero(coefficients):
            bits |= 1 << int(index)
        if bits == 0:
            continue
        trace = 0
        current = _pmod(bits, product)
        for _ in range(degree):
            trace ^= current
            current = _pmod(_pmul(current, current), product)
        w = _pgcd(trace, product)
        if 0 < _pdeg(w) < _pdeg(product):
            quotient, remainder = _pdivmod(product, w)
            if remainder:
                raise AssertionError("internal error: gcd does not divide its argument")
            return _equal_degree_split(w, degree, rng) + _equal_degree_split(
                quotient, degree, rng
            )
    return []  # split not found within the attempt budget; caller treats as miss


def _pfactors(f: int, rng: np.random.Generator) -> list[int]:
    """Some (Rabin-verified) irreducible factors of ``f`` over GF(2).

    Repeated squares are peeled off first; the odd-multiplicity part is then
    factored by distinct-degree + equal-degree splitting.  The returned list
    may omit even-multiplicity factors — callers only need *witness* factors,
    and every returned polynomial is re-verified irreducible.
    """

    factors: set[int] = set()
    while _pdeg(f) >= 1:
        derivative = _pderiv(f)
        if derivative == 0:
            f = _psqrt(f)
            continue
        squarefree, _ = _pdivmod(f, _pgcd(f, derivative))
        g = squarefree
        h = 2  # the polynomial x
        d = 0
        while _pdeg(g) >= 1 and d < _pdeg(squarefree) + 1:
            d += 1
            h = _pmod(_pmul(h, h), g)
            w = _pgcd(h ^ 2, g)
            if _pdeg(w) > 0:
                for factor in _equal_degree_split(w, d, rng):
                    factors.add(factor)
                g, remainder = _pdivmod(g, w)
                if remainder:
                    raise AssertionError("internal error: DDF component does not divide")
                h = _pmod(h, g) if _pdeg(g) >= 1 else 0
        break
    return [factor for factor in sorted(factors) if _pirreducible(factor)]


# ---------------------------------------------------------------------------
# Matrix helpers over GF(2)
# ---------------------------------------------------------------------------


def _vector_minpoly(matrix: np.ndarray, vector: np.ndarray) -> int:
    """Monic minimal polynomial of ``matrix`` on ``vector`` (row action).

    Krylov elimination with combination tracking: the first linear dependence
    among ``v, vM, vM^2, ...`` is the (monic) minimal annihilator of ``v``,
    which divides the minimal polynomial and hence the characteristic
    polynomial of ``M``.
    """

    rows: list[tuple[np.ndarray, int, int]] = []  # (reduced row, combination, pivot)
    current = np.asarray(vector, dtype=np.uint8).copy()
    power = 0
    while True:
        reduced = current.copy()
        combination = 1 << power
        for row, combo, pivot in rows:
            if reduced[pivot]:
                reduced ^= row
                combination ^= combo
        support = np.flatnonzero(reduced)
        if support.size == 0:
            return combination
        rows.append((reduced, combination, int(support[0])))
        current = gf2_matmul(current[None, :], matrix)[0]
        power += 1


def _poly_eval_matrix(p: int, matrix: np.ndarray) -> np.ndarray:
    """Evaluate a GF(2)[x] polynomial at a square matrix (Horner)."""

    size = matrix.shape[0]
    result = np.zeros((size, size), dtype=np.uint8)
    identity = np.eye(size, dtype=np.uint8)
    for bit in range(_pdeg(p), -1, -1):
        result = gf2_matmul(result, matrix)
        if (p >> bit) & 1:
            result ^= identity
    return result


def _matrix_order(matrix: np.ndarray, *, cap: int = 65_536) -> int:
    """Exact multiplicative order by iterated powering (raises past ``cap``)."""

    size = matrix.shape[0]
    identity = np.eye(size, dtype=np.uint8)
    power = matrix.copy()
    for exponent in range(1, cap + 1):
        if np.array_equal(power, identity):
            return exponent
        power = gf2_matmul(power, matrix)
    raise RuntimeError(f"matrix order exceeds cap {cap}")


# ---------------------------------------------------------------------------
# Symplectic transvections
# ---------------------------------------------------------------------------


def symplectic_transvection(direction: np.ndarray) -> np.ndarray:
    """The symplectic transvection ``t_v : x -> x + <x, v> v`` (row action).

    With the repository's form ``[[0, I], [I, 0]]``, ``<x, v>`` is the dot
    product of ``x`` with the half-swapped ``v``, so the matrix is
    ``I + outer(J v, v)``.
    """

    v = np.asarray(direction, dtype=np.uint8) & 1
    two_k = v.shape[0]
    if two_k % 2 or not v.any():
        raise ValueError("direction must be a nonzero symplectic row vector")
    k = two_k // 2
    swapped = np.concatenate([v[k:], v[:k]])
    return (np.eye(two_k, dtype=np.uint8) ^ (swapped[:, None] & v[None, :])).astype(np.uint8)


def _transvection_direction(matrix: np.ndarray) -> np.ndarray | None:
    """The direction vector when ``matrix`` is a symplectic transvection.

    A symplectic matrix with ``rank(t - I) = 1`` is necessarily ``t_v`` with
    ``v`` spanning the row space of ``t - I`` (the rank-one block must be
    ``outer(J v, v)`` for the form to be preserved); the reconstruction is
    verified exactly before returning.
    """

    two_k = matrix.shape[0]
    difference = matrix ^ np.eye(two_k, dtype=np.uint8)
    if rank(difference) != 1:
        return None
    row_index = int(np.flatnonzero(difference.any(axis=1))[0])
    v = difference[row_index]
    try:
        candidate = symplectic_transvection(v)
    except ValueError:
        return None
    if np.array_equal(candidate, matrix):
        return v
    return None


# ---------------------------------------------------------------------------
# Element orders of symmetric groups (for the McLaughlin exclusion)
# ---------------------------------------------------------------------------

_SYMMETRIC_ORDER_CACHE: dict[int, frozenset[int]] = {}


def _symmetric_group_element_orders(m: int, *, cap: int = 4_000_000) -> frozenset[int]:
    """The exact set of element orders of ``S_m``.

    An element order is the lcm of a partition of ``m``; equivalently a
    product over distinct primes ``p`` of one power ``p^a``, with the sum of
    the chosen prime powers at most ``m``.  Dynamic programming over primes
    (order -> minimal spent budget) enumerates the set exactly.  This set is
    closed under divisors, which the recognition certificate relies on.
    """

    cached = _SYMMETRIC_ORDER_CACHE.get(m)
    if cached is not None:
        return cached
    best: dict[int, int] = {1: 0}
    for p in _primes_up_to(m):
        powers = []
        q = p
        while q <= m:
            powers.append(q)
            q *= p
        for order, spent in list(best.items()):
            for q in powers:
                cost = spent + q
                if cost <= m:
                    new_order = order * q
                    previous = best.get(new_order)
                    if previous is None or previous > cost:
                        best[new_order] = cost
            if len(best) > cap:
                raise RuntimeError("symmetric-order enumeration exceeded its cap")
    result = frozenset(best)
    _SYMMETRIC_ORDER_CACHE[m] = result
    return result


# ---------------------------------------------------------------------------
# Recognition: certified fullness for large k (McLaughlin route)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RecognitionReport:
    """Outcome of the transvection-recognition certificate.

    ``verdict`` is ``"full"`` (G = Sp(2k,2), certified), ``"not-full"``
    (a verified invariant subspace or quadratic form excludes fullness), or
    ``"inconclusive"`` (some sub-certificate could not be established —
    never a wrong answer, only an honest failure).
    """

    verdict: str
    checks: dict[str, Any]
    detail: str


def _shear_transvection(
    gens: list[np.ndarray], rng: np.random.Generator, deadline: float
) -> tuple[np.ndarray, np.ndarray] | None:
    """Exact transvection search inside the abelian shear families.

    Layers of the form ``[[I, S], [0, I]]`` (Z-type) commute and compose by
    adding their symmetric blocks, and ``S = b b^T`` is exactly the
    symplectic transvection ``t_(0|b)``; dually ``[[I, 0], [T, I]]`` with
    ``T = a a^T`` is ``t_(a|0)``.  Whether some GF(2) combination of the
    reachable shear blocks equals a chosen rank-one target is a *linear*
    question, so shear-rich groups (the depth-one layers collected here are
    mostly shears) yield certified transvections by exact solves instead of
    random search.

    The reachable shear spaces are first enriched by conjugation: for any
    group element ``w``, ``w^-1 [[I,S],[0,I]] w`` is again a group element,
    and whenever it happens to be a shear its block joins the span.  Every
    basis element carries the explicit conjugated group element, so the
    returned transvection is a verified product of generators (a product of
    commuting shear elements of G, checked against the closed form).
    """

    two_k = gens[0].shape[0]
    k = two_k // 2
    identity = np.eye(two_k, dtype=np.uint8)
    identity_k = np.eye(k, dtype=np.uint8)
    symmetric_dim = k * (k + 1) // 2

    def classify(matrix: np.ndarray) -> tuple[str | None, np.ndarray | None]:
        a, b, c, d = matrix[:k, :k], matrix[:k, k:], matrix[k:, :k], matrix[k:, k:]
        if np.array_equal(a, identity_k) and np.array_equal(d, identity_k):
            if not c.any():
                return "U", b
            if not b.any():
                return "L", c
        return None, None

    # span basis per family: parallel lists of (block, group element)
    blocks: dict[str, list[np.ndarray]] = {"U": [], "L": []}
    elements: dict[str, list[np.ndarray]] = {"U": [], "L": []}
    pivots: dict[str, list[int]] = {"U": [], "L": []}
    echelon: dict[str, list[np.ndarray]] = {"U": [], "L": []}

    def basis_add(kind: str, block: np.ndarray, element: np.ndarray) -> bool:
        reduced = block.reshape(-1).copy()
        for row, pivot in zip(echelon[kind], pivots[kind]):
            if reduced[pivot]:
                reduced ^= row
        support = np.flatnonzero(reduced)
        if support.size == 0:
            return False
        blocks[kind].append(block.copy())
        elements[kind].append(element.copy())
        echelon[kind].append(reduced)
        pivots[kind].append(int(support[0]))
        return True

    for g in gens:
        kind, block = classify(g)
        if kind is not None and not np.array_equal(g, identity):
            basis_add(kind, block, g)
    if not blocks["U"] and not blocks["L"]:
        return None

    # conjugation enrichment by single generators (systematic) ...
    inverses = [gf2_inverse(g) for g in gens]
    queue = list(elements["U"]) + list(elements["L"])
    while queue and time.perf_counter() < deadline:
        element = queue.pop()
        for g, g_inv in zip(gens, inverses):
            conjugate = gf2_matmul(gf2_matmul(g_inv, element), g)
            kind, block = classify(conjugate)
            if kind is not None and basis_add(kind, block, conjugate):
                queue.append(conjugate)
    # ... then by random generator words, catching conjugators whose
    # intermediate conjugates leave the shear families.  The patience scales
    # with the target dimension: high-k spans need thousands of successful
    # additions before the rank-one solve can succeed.
    stall = 0
    stall_limit = max(300, symmetric_dim)
    while stall < stall_limit and time.perf_counter() < deadline:
        if len(blocks["U"]) >= symmetric_dim and len(blocks["L"]) >= symmetric_dim:
            break
        word = identity
        for _ in range(int(rng.integers(1, 7))):
            word = gf2_matmul(word, gens[int(rng.integers(0, len(gens)))])
        word_inv = gf2_inverse(word)
        kind = "U" if (blocks["U"] and (not blocks["L"] or rng.integers(2))) else "L"
        element = elements[kind][int(rng.integers(0, len(elements[kind])))]
        conjugate = gf2_matmul(gf2_matmul(word_inv, element), word)
        new_kind, block = classify(conjugate)
        if new_kind is not None and basis_add(new_kind, block, conjugate):
            stall = 0
        else:
            stall += 1

    for kind in ("U", "L"):
        if not blocks[kind]:
            continue
        flat = np.asarray([block.reshape(-1) for block in blocks[kind]], dtype=np.uint8)
        targets = [identity_k[i] for i in range(k)]
        targets += [
            identity_k[i] ^ identity_k[j]
            for i in range(min(k, 12))
            for j in range(i + 1, min(k, 12))
        ]
        for _ in range(16):
            random_target = rng.integers(0, 2, size=k).astype(np.uint8)
            if random_target.any():
                targets.append(random_target)
        for b_vec in targets:
            goal = np.outer(b_vec, b_vec).astype(np.uint8).reshape(-1)
            solution = _solve_gf2_system(flat.T, goal)
            if solution is None:
                continue
            product = identity.copy()
            for index in np.flatnonzero(solution):
                product = gf2_matmul(product, elements[kind][int(index)])
            if kind == "U":
                direction = np.concatenate([np.zeros(k, dtype=np.uint8), b_vec])
            else:
                direction = np.concatenate([b_vec, np.zeros(k, dtype=np.uint8)])
            if np.array_equal(product, symplectic_transvection(direction)):
                return product, direction
    return None


def _find_transvection(
    gens: list[np.ndarray], rng: np.random.Generator, deadline: float
) -> tuple[np.ndarray, np.ndarray] | None:
    """Search for an explicit transvection among products of the generators.

    Every candidate is a verified product of group generators, so membership
    in G is certified by construction.  The exact shear-family solve of
    :func:`_shear_transvection` runs first; the fallback candidates are the
    generators, pairwise products, short random words, and small powers of
    each (catching elements that power into a transvection).
    """

    two_k = gens[0].shape[0]
    identity = np.eye(two_k, dtype=np.uint8)

    from_shears = _shear_transvection(gens, rng, deadline)
    if from_shears is not None:
        return from_shears

    def scan(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray] | None:
        power = matrix.copy()
        for _ in range(32):
            if np.array_equal(power, identity):
                return None
            direction = _transvection_direction(power)
            if direction is not None:
                return power, direction
            power = gf2_matmul(power, matrix)
        return None

    for g in gens:
        found = scan(g)
        if found is not None:
            return found
    if len(gens) <= 24:
        for i, a in enumerate(gens):
            for b in gens[i + 1 :]:
                found = scan(gf2_matmul(a, b))
                if found is not None:
                    return found
                if time.perf_counter() > deadline:
                    return None
    for _ in range(300):
        if time.perf_counter() > deadline:
            return None
        length = int(rng.integers(2, 7))
        word = identity
        for _ in range(length):
            word = gf2_matmul(word, gens[int(rng.integers(0, len(gens)))])
        found = scan(word)
        if found is not None:
            return found
    return None


def _direction_orbit(
    seed: np.ndarray, gens: list[np.ndarray], *, cap: int
) -> tuple[list[np.ndarray], bool]:
    """Partial orbit of ``seed`` under right multiplication by the generators.

    Every returned vector ``w`` satisfies ``w = seed * g`` for a word ``g``
    in the generators, so ``t_w = g^-1 t_seed g`` lies in G (conjugates of a
    symplectic transvection by symplectic maps are transvections in the
    image direction).  The boolean reports whether the orbit closed.
    """

    seen = {seed.tobytes()}
    orbit = [seed]
    cursor = 0
    while cursor < len(orbit):
        current = orbit[cursor]
        cursor += 1
        for g in gens:
            image = gf2_matmul(current[None, :], g)[0]
            key = image.tobytes()
            if key not in seen:
                seen.add(key)
                orbit.append(image)
                if len(orbit) >= cap:
                    return orbit, False
    return orbit, True


def _spin_span(
    seed: np.ndarray, directions: list[np.ndarray], *, transpose: bool
) -> np.ndarray:
    """Smallest transvection-invariant subspace containing ``seed``.

    Forward action of ``t_w``: ``x -> x + <x, w> w``.  Transposed (dual)
    action: ``x -> x + (x . w) (J w)``.  Returns a row basis; spinning stops
    early once the span is the full space.
    """

    two_k = seed.shape[0]
    k = two_k // 2
    swapped = [np.concatenate([w[k:], w[:k]]) for w in directions]
    rows: list[np.ndarray] = []
    pivots: list[int] = []

    def add(vector: np.ndarray) -> bool:
        reduced = vector.copy()
        for row, pivot in zip(rows, pivots):
            if reduced[pivot]:
                reduced ^= row
        support = np.flatnonzero(reduced)
        if support.size == 0:
            return False
        pivot = int(support[0])
        for index, row in enumerate(rows):
            if row[pivot]:
                rows[index] = row ^ reduced
        rows.append(reduced)
        pivots.append(pivot)
        return True

    queue = [seed]
    add(seed)
    while queue and len(rows) < two_k:
        current = queue.pop()
        for w, jw in zip(directions, swapped):
            if transpose:
                coefficient = int(current @ w) & 1
                image = current ^ jw if coefficient else None
            else:
                coefficient = int(current @ jw) & 1
                image = current ^ w if coefficient else None
            if image is not None and add(image):
                queue.append(image)
                if len(rows) == two_k:
                    break
    return np.asarray(rows, dtype=np.uint8)


def _transvection_invariant(basis: np.ndarray, directions: list[np.ndarray]) -> bool:
    """Exact check that a row space is invariant under every ``t_w``."""

    if basis.shape[0] == 0:
        return True
    two_k = basis.shape[1]
    k = two_k // 2
    for w in directions:
        jw = np.concatenate([w[k:], w[:k]])
        coefficients = gf2_matmul(basis, jw[:, None])[:, 0]
        images = basis ^ (coefficients[:, None] & w[None, :])
        if rowspace_residues(images, basis).any():
            return False
    return True


def _matrix_invariant(basis: np.ndarray, gens: list[np.ndarray]) -> bool:
    """Exact check that a row space is invariant under every generator."""

    if basis.shape[0] == 0:
        return True
    for g in gens:
        if rowspace_residues(gf2_matmul(basis, g), basis).any():
            return False
    return True


def _norton_irreducibility(
    directions: list[np.ndarray],
    two_k: int,
    rng: np.random.Generator,
    deadline: float,
    *,
    attempts: int = 24,
) -> dict[str, Any]:
    """Certified irreducibility (and endomorphism field) of the transvection
    module, or a verified invariant subspace.

    Norton's criterion (Holt-Rees, "Testing modules for irreducibility",
    J. Austral. Math. Soc. 57 (1994); Holt-Eick-O'Brien, Handbook of CGT
    §7.4), in the multiplicity-one form used here.  Let ``A`` lie in the
    enveloping algebra of the acting group, ``theta`` an irreducible
    polynomial with ``N = null theta(A)`` of dimension exactly
    ``deg theta``, and ``N' = null theta(A)^T`` (the dual-module null space).
    If one nonzero ``v in N`` spins (under the group) to the whole space and
    one nonzero ``f in N'`` spins under the transposed action to the whole
    dual space, the module is irreducible.  Proof sketch, fully re-derived
    for this implementation: a proper submodule ``W`` either meets ``N`` — but
    any ``v' in N`` generates ``N`` over ``F_2[A]`` (dim N = deg theta makes
    ``N`` an irreducible ``F_2[A]``-module), so ``spin(v') >= spin(v) = V``,
    contradiction — or misses it, in which case ``theta(A)`` is a bijection
    of ``W``, so ``W`` lies inside ``im theta(A)`` and the annihilator of
    ``W`` meets ``N' = (im theta(A))^0`` nontrivially, giving the dual
    contradiction.  Every claimed invariant subspace is re-verified exactly,
    so a false "reducible" is impossible.

    The witness degrees also certify the endomorphism field: ``End(V)`` embeds
    into ``End_{F_2[A]}(N) ~ F_2^(deg theta)`` (restriction to ``N`` is
    injective by Schur's lemma), so ``End(V) = F_2`` once witness degrees with
    gcd 1 are found — the absolute-irreducibility certificate used by the
    invariant-form argument.

    Returns a dict with ``status`` in ``{"abs_irreducible", "reducible",
    "unknown"}`` plus ``subspace`` (verified basis) or ``witness_degrees``.
    """

    witness_degrees: list[int] = []
    # sample directions across the whole partial orbit: breadth-first
    # prefixes are nearly parallel and generate degenerate algebra elements
    sample_size = min(len(directions), max(128, two_k))
    chosen = rng.choice(len(directions), size=sample_size, replace=False)
    matrices = [symplectic_transvection(directions[int(i)]) for i in chosen]
    for _ in range(attempts):
        if time.perf_counter() > deadline:
            break
        # Terms must be *long* products: a product of r transvections is
        # I + (rank <= r), so short terms give algebra elements whose
        # nontrivial factors never reach nullity = degree at large 2k.
        algebra_element = np.zeros((two_k, two_k), dtype=np.uint8)
        for _ in range(int(rng.integers(2, 5))):
            term = np.eye(two_k, dtype=np.uint8)
            for _ in range(int(rng.integers(max(1, two_k // 2), two_k + 1))):
                term = gf2_matmul(term, matrices[int(rng.integers(0, len(matrices)))])
            algebra_element ^= term
        probe = rng.integers(0, 2, size=two_k).astype(np.uint8)
        if not probe.any():
            continue
        annihilator = _vector_minpoly(algebra_element, probe)
        for theta in _pfactors(annihilator, rng):
            degree = _pdeg(theta)
            evaluated = _poly_eval_matrix(theta, algebra_element)
            null_rows = nullspace(evaluated.T)  # {x : x theta(A) = 0}
            if null_rows.shape[0] != degree:
                continue
            null_dual = nullspace(evaluated)  # {f : theta(A) f^T = 0}
            if null_dual.shape[0] != degree:
                continue
            span = _spin_span(null_rows[0], directions, transpose=False)
            if span.shape[0] < two_k:
                if 0 < span.shape[0] and _transvection_invariant(span, directions):
                    return {"status": "reducible", "subspace": span}
                continue  # spin bookkeeping failed verification; try another witness
            dual_span = _spin_span(null_dual[0], directions, transpose=True)
            if dual_span.shape[0] < two_k:
                subspace = nullspace(dual_span)  # annihilator of the dual span
                if (
                    0 < subspace.shape[0] < two_k
                    and _transvection_invariant(subspace, directions)
                ):
                    return {"status": "reducible", "subspace": subspace}
                continue
            witness_degrees.append(degree)
            if len(witness_degrees) >= 1:
                overall = witness_degrees[0]
                for d in witness_degrees[1:]:
                    overall = gcd(overall, d)
                if overall == 1:
                    return {
                        "status": "abs_irreducible",
                        "witness_degrees": sorted(set(witness_degrees)),
                    }
    return {"status": "unknown", "witness_degrees": sorted(set(witness_degrees))}


def _canonical_quadratic(matrix: np.ndarray) -> np.ndarray:
    """Canonical (upper-triangular) coefficient matrix of ``x -> x M x^T``.

    Over GF(2), ``x_i^2 = x_i``: the coefficient of ``x_i x_j`` (i < j) is
    ``M_ij + M_ji`` and the coefficient of ``x_i`` is ``M_ii``.
    """

    upper = (np.triu(matrix, 1) ^ np.triu(matrix.T, 1)) & 1
    return (upper ^ np.diag(np.diag(matrix))).astype(np.uint8)


def _solve_gf2_system(system: np.ndarray, rhs: np.ndarray) -> np.ndarray | None:
    """One solution of ``system @ x = rhs`` over GF(2), or ``None``."""

    from .gf2 import rref

    columns = system.shape[1]
    augmented = np.hstack([system & 1, rhs[:, None] & 1]).astype(np.uint8)
    reduced, pivots = rref(augmented)
    if columns in pivots:
        return None
    solution = np.zeros(columns, dtype=np.uint8)
    for row, pivot in zip(reduced, pivots):
        solution[pivot] = row[columns]
    return solution


def _invariant_quadratic_form(
    directions: list[np.ndarray], two_k: int
) -> np.ndarray | None:
    """A quadratic form polarizing to the symplectic form and invariant under
    every ``t_w`` — or ``None``, certifying that no such form exists.

    Any invariant quadratic form of an absolutely irreducible symplectic
    group has polar form 0 or J (the space of invariant bilinear forms is
    ``Hom_G(V, V*) ~ End_G(V) = F_2``, spanned by J); polar 0 forces a
    G-fixed linear functional, impossible for an irreducible module.  So it
    suffices to search among ``Q_1 + linear`` with ``Q_1`` a fixed form
    polarizing to J: invariance under a symplectic ``g`` reads
    ``(g + I) c = d_g`` with ``d_g`` the diagonal defect of ``Q_1`` under
    ``g`` — a tiny exact linear system.  Callers must hold the absolute
    irreducibility certificate before interpreting ``None`` as the absence of
    *any* nonzero invariant quadratic form.
    """

    k = two_k // 2
    identity = np.eye(two_k, dtype=np.uint8)
    q_one = np.zeros((two_k, two_k), dtype=np.uint8)
    q_one[np.arange(k), k + np.arange(k)] = 1
    blocks: list[np.ndarray] = []
    rhs: list[np.ndarray] = []
    for w in directions:
        t = symplectic_transvection(w)
        moved = _canonical_quadratic(gf2_matmul(gf2_matmul(t, q_one), t.T))
        difference = moved ^ q_one
        if np.triu(difference, 1).any():
            raise AssertionError("internal error: transvection moved the polar form")
        blocks.append(t ^ identity)
        rhs.append(np.diag(difference).astype(np.uint8))
    solution = _solve_gf2_system(np.vstack(blocks), np.concatenate(rhs))
    if solution is None:
        return None
    return (q_one ^ np.diag(solution)).astype(np.uint8)


def _form_invariant_under(form: np.ndarray, gens: list[np.ndarray]) -> bool:
    for g in gens:
        moved = _canonical_quadratic(gf2_matmul(gf2_matmul(g, form), g.T))
        if not np.array_equal(moved, form):
            return False
    return True


def _excludes_symmetric_groups(
    directions: list[np.ndarray],
    two_k: int,
    rng: np.random.Generator,
    deadline: float,
    *,
    attempts: int = 24,
) -> int | None:
    """Certify that the transvection group is not ``S_{2k+1}`` or ``S_{2k+2}``.

    If ``M`` in the group has an irreducible characteristic-polynomial factor
    ``theta`` whose root order (the multiplicative order of ``x`` mod
    ``theta``) is not an element order of ``S_{2k+2}``, the group cannot be
    isomorphic to ``S_{2k+1}`` or ``S_{2k+2}``: the root order divides
    ``ord(M)``, and the element-order set of a symmetric group is closed
    under divisors (a divisor of an lcm of a partition is again such an lcm).
    The root-order test is run against the *exact* order set from
    :func:`_symmetric_group_element_orders`, so the certificate is
    module-independent — it excludes the symmetric groups under any
    isomorphism, not only in their natural representation.  Returns the
    witness degree, or ``None`` when no witness was found (honest failure).
    """

    allowed = _symmetric_group_element_orders(two_k + 2)
    sample_size = min(len(directions), max(128, two_k))
    chosen = rng.choice(len(directions), size=sample_size, replace=False)
    matrices = [symplectic_transvection(directions[int(i)]) for i in chosen]
    for _ in range(attempts):
        if time.perf_counter() > deadline:
            return None
        # Long random products approximate uniform group elements, which for
        # symplectic groups carry high-degree irreducible factors with large
        # root orders; short products only ever move a low-rank subspace.
        element = np.eye(two_k, dtype=np.uint8)
        for _ in range(int(rng.integers(two_k, 3 * two_k + 1))):
            element = gf2_matmul(element, matrices[int(rng.integers(0, len(matrices)))])
        for _ in range(3):
            probe = rng.integers(0, 2, size=two_k).astype(np.uint8)
            if not probe.any():
                continue
            annihilator = _vector_minpoly(element, probe)
            for theta in _pfactors(annihilator, rng):
                if _pdeg(theta) < 2:
                    continue
                if rank(_poly_eval_matrix(theta, element)) == two_k:
                    continue  # not actually a characteristic factor; skip
                if all(_ppowmod(2, order, theta) != 1 for order in allowed):
                    return _pdeg(theta)
    return None


def recognize_full_symplectic(
    generators: list[np.ndarray],
    k: int,
    *,
    seed: int = 11,
    time_budget_s: float = 60.0,
    max_directions: int = 2048,
) -> RecognitionReport:
    """Certified decision of ``<generators> = Sp(2k, 2)`` for large ``k``.

    The route rests on McLaughlin's classification (J. McLaughlin, *Some
    subgroups of SL_n(F_2)*, Illinois J. Math. 13 (1969), 108-115; statement
    verified against the surveys cited in the module tests): an irreducible
    subgroup of ``GL(n, 2)`` generated by transvections is ``SL(n, 2)`` or,
    for even ``n >= 4``, ``Sp(n, 2)``, ``O^+/-(n, 2)``, ``S_{n+1}`` or
    ``S_{n+2}`` on its natural module.  The certificate chain:

    1. every generator is verified symplectic, so ``G <= Sp(2k, 2)``;
    2. an explicit transvection ``t_v`` is exhibited as a verified product of
       generators (``rank(t - I) = 1`` plus exact reconstruction as ``t_v``);
    3. directions ``w = v g`` from the partial G-orbit of ``v`` give a
       transvection-generated subgroup ``T = <t_w> <= G`` (conjugation
       identity ``g^-1 t_v g = t_{v g}`` for symplectic ``g``);
    4. Norton's criterion (:func:`_norton_irreducibility`) certifies that
       ``T`` acts irreducibly and, via witness degrees of gcd 1, that
       ``End(V) = F_2`` — so McLaughlin's list applies to ``T``;
    5. exclusions, each exact: ``SL(2k, 2)`` by cardinality
       (``|SL(2k,2)| > |Sp(2k,2)|`` for ``2k >= 4`` yet ``T`` preserves the
       form); ``O^+/-`` because no nonzero ``T``-invariant quadratic form
       exists (:func:`_invariant_quadratic_form`, sound given step 4);
       ``S_{2k+1}``/``S_{2k+2}`` by the root-order certificate
       (:func:`_excludes_symmetric_groups`);
    6. what remains is ``T = Sp(V, B)`` for an invariant nondegenerate
       alternating form ``B``; by step 4 the only such form is J, so
       ``T = Sp(2k, 2)`` and ``Sp(2k, 2) = T <= G <= Sp(2k, 2)``.

    A verified invariant subspace or quadratic form that survives the *full*
    generator set instead certifies ``is_full = False`` (the natural module
    of ``Sp(2k, 2)`` is irreducible and, for ``k >= 2``, admits no nonzero
    invariant quadratic form).  Anything else returns ``"inconclusive"`` —
    the McLaughlin route never guesses.
    """

    start = time.perf_counter()
    deadline = start + time_budget_s
    checks: dict[str, Any] = {}
    two_k = 2 * k
    if k < 2:
        return RecognitionReport(
            "inconclusive", checks, "recognition needs k >= 2 (the 2k = 2 list degenerates)"
        )
    gens: list[np.ndarray] = []
    identity = np.eye(two_k, dtype=np.uint8)
    for generator in generators:
        matrix = (np.asarray(generator, dtype=np.uint8) & 1).copy()
        if matrix.shape != (two_k, two_k):
            raise ValueError("generators must be 2k x 2k matrices")
        if not is_symplectic(matrix, qubits=k):
            raise ValueError("recognition requires certified symplectic generators")
        if not np.array_equal(matrix, identity):
            gens.append(matrix)
    if not gens:
        return RecognitionReport("inconclusive", checks, "trivial generator set")
    checks["generators_symplectic"] = True

    sl_order = 1
    for i in range(two_k):
        sl_order *= (1 << two_k) - (1 << i)
    checks["sl_excluded_by_cardinality"] = sl_order > symplectic_group_order(k)
    if not checks["sl_excluded_by_cardinality"]:  # pragma: no cover - k >= 2 always passes
        return RecognitionReport("inconclusive", checks, "SL cardinality exclusion failed")

    rng = np.random.default_rng(seed)
    found = _find_transvection(gens, rng, deadline)
    if found is None:
        return RecognitionReport(
            "inconclusive", checks, "no transvection found among generator products"
        )
    _, direction = found
    checks["transvection_exhibited"] = True

    cap = max(4 * two_k, 64)
    while True:
        if time.perf_counter() > deadline:
            return RecognitionReport("inconclusive", checks, "time budget exhausted")
        directions, orbit_closed = _direction_orbit(direction, gens, cap=cap)
        checks["directions_used"] = len(directions)
        # The span of the full orbit of the transvection direction is a
        # G-invariant subspace.  When the collected directions span a proper
        # subspace that is verified invariant under every generator, G is
        # reducible — while Sp(2k,2) acts irreducibly (indeed transitively,
        # by Witt) on nonzero vectors — so fullness is refuted outright.
        # Norton cannot certify anything from a non-spanning direction set,
        # so that case either refutes or forces more orbit.
        span_basis = row_basis(np.asarray(directions, dtype=np.uint8), ncols=two_k)
        checks["direction_span_dim"] = int(span_basis.shape[0])
        if span_basis.shape[0] < two_k:
            if _matrix_invariant(span_basis, gens):
                checks["invariant_subspace_dim"] = int(span_basis.shape[0])
                return RecognitionReport(
                    "not-full",
                    checks,
                    "the transvection-direction orbit spans a verified proper "
                    "G-invariant subspace: G is reducible, but the natural "
                    "Sp(2k,2) module is irreducible",
                )
            if orbit_closed or cap >= max_directions:
                return RecognitionReport(
                    "inconclusive",
                    checks,
                    "direction orbit does not span the module within the cap",
                )
            cap *= 2
            continue
        norton = _norton_irreducibility(directions, two_k, rng, deadline)
        if norton["status"] == "reducible":
            subspace = norton["subspace"]
            if _matrix_invariant(subspace, gens) and 0 < subspace.shape[0] < two_k:
                checks["invariant_subspace_dim"] = int(subspace.shape[0])
                return RecognitionReport(
                    "not-full",
                    checks,
                    "verified proper invariant subspace: G is reducible, but the "
                    "natural Sp(2k,2) module is irreducible",
                )
        elif norton["status"] == "abs_irreducible":
            checks["irreducible"] = True
            checks["norton_witness_degrees"] = norton["witness_degrees"]
            checks["endomorphism_field_is_F2"] = True
            form = _invariant_quadratic_form(directions, two_k)
            if form is None:
                checks["no_invariant_quadratic_form"] = True
                if two_k == 4:
                    # Exceptional isomorphisms collapse the 2k = 4 list:
                    # S_6 ~ Sp(4,2) (its natural module IS the symplectic
                    # module, so that case is already fullness) and
                    # S_5 ~ O^-(4,2) preserves a quadratic form (for odd m
                    # the deleted permutation module carries the invariant
                    # form Q(v) = wt(v)/2 mod 2 polarizing to the dot
                    # product), so the no-form certificate above excludes
                    # it.  No separate symmetric exclusion exists or is
                    # needed at this dimension.
                    checks["symmetric_groups_excluded"] = "exceptional isomorphisms at 2k=4"
                    return RecognitionReport(
                        "full",
                        checks,
                        "McLaughlin classification at 2k = 4: SL and O^+/- excluded, "
                        "S_5 ~ O^-(4,2) excluded with them, S_6 ~ Sp(4,2); T = Sp(4,2) <= G",
                    )
                witness = _excludes_symmetric_groups(directions, two_k, rng, deadline)
                if witness is not None:
                    checks["symmetric_groups_excluded"] = True
                    checks["symmetric_witness_degree"] = witness
                    return RecognitionReport(
                        "full",
                        checks,
                        "McLaughlin classification: irreducible transvection subgroup "
                        "with SL, O^+/-, S_{2k+1}, S_{2k+2} excluded; T = Sp(2k,2) <= G",
                    )
                return RecognitionReport(
                    "inconclusive", checks, "could not exclude S_{2k+1}/S_{2k+2}"
                )
            if _form_invariant_under(form, gens):
                checks["invariant_quadratic_form"] = True
                return RecognitionReport(
                    "not-full",
                    checks,
                    "verified G-invariant quadratic form polarizing to J: G lies in an "
                    "orthogonal group, but Sp(2k,2) (k >= 2) fixes no nonzero form",
                )
        if orbit_closed or cap >= max_directions:
            return RecognitionReport(
                "inconclusive",
                checks,
                "certificates did not stabilize within the direction-orbit cap",
            )
        cap *= 2


# ---------------------------------------------------------------------------
# Generator collection
# ---------------------------------------------------------------------------


@dataclass(frozen=True, eq=False)
class OneBlockGenerator:
    """One certified depth-one one-block layer, by its logical action."""

    matrix: np.ndarray
    kind: str  # "strict-Z" | "strict-X" | "fold-Z" | "fold-X" | "fold-H" | "perm"
    involution: int | None
    label: str

    @property
    def provenance(self) -> dict[str, Any]:
        return {"kind": self.kind, "involution": self.involution, "label": self.label}


def _affine_involutions(n: int, rng: np.random.Generator, count: int) -> list[np.ndarray]:
    """Involutions from the affine group ``AGL(m, 2)`` when ``n = 2^m``.

    Qubit ``j`` is read as the point ``bits(j)`` of ``F_2^m`` (the Reed-Muller
    convention of :func:`.codes.reed_muller_generator`).  Candidates:
    translations ``x -> x + b`` (fixed-point-free involutions), coordinate
    transpositions ``x_i <-> x_j``, and shears ``x_i -> x_i + x_j`` — the
    duality/automorphism supply behind the varying-fold generation theorem
    for middle Reed-Muller codes (arXiv:2602.09788).  These are only
    *candidates*: codes without affine symmetry simply reject them during
    matching certification, exactly like the structural guesses in
    :mod:`.dualities`.
    """

    m = n.bit_length() - 1
    if n != 1 << m or m < 1:
        return []
    points = np.arange(n)
    coordinates = [(points >> i) & 1 for i in range(m)]
    identity_m = np.eye(m, dtype=np.uint8)
    taus: list[np.ndarray] = []

    structured: list[np.ndarray] = []
    for b in range(1, min(n, m + 2)):  # a few translations (the rest are random)
        structured.append(points ^ b)
    for i in range(m):  # coordinate transpositions
        for j in range(i + 1, m):
            swapped = points & ~((1 << i) | (1 << j))
            swapped |= coordinates[j] << i
            swapped |= coordinates[i] << j
            structured.append(swapped)
    for i in range(m):  # shears x_i -> x_i + x_j
        for j in range(m):
            if i != j:
                structured.append(points ^ (coordinates[j] << i))
    taus.extend(structured[:count])

    def apply_affine(linear: np.ndarray, offset: np.ndarray) -> np.ndarray:
        bits = ((points[:, None] >> np.arange(m)) & 1).astype(np.uint8)
        image = (gf2_matmul(bits, linear.T) ^ offset).astype(np.int64)
        return (image * (1 << np.arange(m))).sum(axis=1)

    # General affine involutions x -> Lx + b with L^2 = I and (L + I)b = 0:
    # canonical unipotent involutions conjugated by random invertible maps.
    # Empirically these are the duality supply that saturates the middle
    # Reed-Muller fold groups where coordinate-aligned involutions plateau.
    attempts = 0
    while len(taus) < count and attempts < 20 * count:
        attempts += 1
        pairs = int(rng.integers(1, m // 2 + 1))
        canonical = identity_m.copy()
        for index in range(pairs):
            canonical[2 * index, 2 * index + 1] = 1
        while True:
            conjugator = rng.integers(0, 2, size=(m, m)).astype(np.uint8)
            try:
                inverse = gf2_inverse(conjugator)
                break
            except ValueError:
                continue
        linear = gf2_matmul(gf2_matmul(inverse, canonical), conjugator)
        kernel = nullspace(linear ^ identity_m)
        offset = np.zeros(m, dtype=np.uint8)
        if kernel.shape[0]:
            coefficients = rng.integers(0, 2, size=kernel.shape[0]).astype(np.uint8)
            offset = (coefficients[None, :] @ kernel % 2).astype(np.uint8)[0]
        tau = apply_affine(linear, offset)
        if not np.array_equal(tau, points) and np.array_equal(tau[tau], points):
            taus.append(tau)
    return taus[:count]


def _random_involution(rng: np.random.Generator, n: int) -> np.ndarray:
    """A uniformly paired random matching (twofold.py's fallback sampler)."""

    order = rng.permutation(n)
    tau = np.arange(n)
    for index in range(0, n - 1, 2):
        i, j = int(order[index]), int(order[index + 1])
        tau[i], tau[j] = j, i
    return tau


def _collect_involutions(
    code: CSSCode,
    name: str | None,
    aut,
    *,
    involution_cap: int,
    seed: int,
    extra_taus: list[np.ndarray] | None,
    discover: bool = True,
) -> list[tuple[str, np.ndarray]]:
    """Candidate involutions: identity, structural, BLISS duality, affine
    candidates (for ``n = 2^m``), automorphism-group samples, then random
    matchings as filler — every candidate is certified or rejected by
    :class:`.matching.MatchingAnalysis` before any gate is trusted."""

    n = code.n
    identity = np.arange(n)
    candidates: list[tuple[str, np.ndarray]] = [("identity", identity)]
    if name is not None:
        for label, tau in candidates_for(name):
            tau = np.asarray(tau, dtype=int)
            if np.array_equal(tau[tau], identity):
                candidates.append((label, tau))
    for index, tau in enumerate(extra_taus or []):
        tau = np.asarray(tau, dtype=int)
        if np.array_equal(tau[tau], identity):
            candidates.append((f"extra-{index}", tau))
    # Structure-inferred candidates are ADDITIVE: they raise the cap by their
    # own count instead of competing under it.  They are the only supply that
    # works on codes outside the registry (the 2026-08-19 census cross-check
    # found order-1 blind verdicts on quasi-cyclic codes whose certified
    # groups reach 5x10^11), but letting them displace the legacy supplies
    # under one shared cap costs certificates that depend on a wide legacy
    # sample (rm64's full-Sp(40,2) needs its 48 affine candidates).  The
    # analysis loop's time budget remains the hard guard on total work.
    discovered = discover_involutions(code, forward_cap=involution_cap) if discover else []
    candidates.extend(discovered)
    keep_cap = involution_cap + len(discovered)
    if aut is not None:
        duality = aut.involutive_duality()
        if duality is not None:
            candidates.append(("bliss-involutive-duality", duality))
        if aut.qubit_generators:
            sampled = automorphism_involutions(
                aut.qubit_generators, n, count=involution_cap, seed=seed
            )
            for index, tau in enumerate(sampled):
                candidates.append((f"aut-sample-{index}", tau))
    rng = np.random.default_rng(seed)
    for index, tau in enumerate(_affine_involutions(n, rng, involution_cap)):
        candidates.append((f"affine-{index}", tau))
    # Random-matching filler is sized against the LEGACY candidate count: the
    # additive discovered block must not eat the random sample (bb72's order
    # 35,715 depends on it) any more than the legacy supplies may crowd out
    # discovery.
    while len(candidates) - len(discovered) < 2 * involution_cap:
        candidates.append((f"random-{len(candidates)}", _random_involution(rng, n)))
    unique: list[tuple[str, np.ndarray]] = []
    seen: set[bytes] = set()
    for label, tau in candidates:
        key = tau.tobytes()
        if key not in seen:
            seen.add(key)
            unique.append((label, tau))
        if len(unique) >= keep_cap:
            break
    return unique


# ---------------------------------------------------------------------------
# Word-tracking Schreier-Sims chain (synthesis backend)
# ---------------------------------------------------------------------------


class _WordLevel:
    __slots__ = ("base", "gens", "orbit")

    def __init__(self, base: int):
        self.base = base
        # strong generators: (matrix, packed rows, word)
        self.gens: list[tuple[np.ndarray, tuple[int, ...], list[int]]] = []
        # orbit point -> (element u with base*u = point, u^-1, word of u)
        self.orbit: dict[int, tuple[np.ndarray, np.ndarray, list[int]]] = {}


class WordBSGS:
    """Deterministic Schreier-Sims chain that tracks generator words.

    The chain reaches a verified fixpoint (every Schreier generator sifts to
    the identity), which certifies both the group order and the completeness
    of membership testing: a target that fails to sift is provably outside
    the group.  Words are sequences of generator indices whose left-to-right
    matrix product reproduces the element; generator inverses are expanded as
    ``g^(order-1)`` using exact element orders, so words can be long — the
    caller records lengths and does not optimize.
    """

    _WORD_LIMIT = 2_000_000

    def __init__(self, generators: list[np.ndarray], *, node_budget: int = 2_000_000):
        self.generators = [
            (np.asarray(g, dtype=np.uint8) & 1).copy() for g in generators
        ]
        if not self.generators:
            raise ValueError("WordBSGS needs at least one generator")
        self.dimension = self.generators[0].shape[0]
        self.identity = np.eye(self.dimension, dtype=np.uint8)
        self.orders = [_matrix_order(g) for g in self.generators]
        self.node_budget = node_budget
        self.levels: list[_WordLevel] = []
        self._build()

    # -- word arithmetic ---------------------------------------------------

    def _inverse_word(self, word: list[int]) -> list[int]:
        out: list[int] = []
        for index in reversed(word):
            out.extend([index] * (self.orders[index] - 1))
        if len(out) > self._WORD_LIMIT:
            raise RuntimeError("synthesis word grew past the safety limit")
        return out

    def word_product(self, word: list[int]) -> np.ndarray:
        result = self.identity.copy()
        for index in word:
            result = gf2_matmul(result, self.generators[index])
        return result

    # -- chain construction ------------------------------------------------

    def _moved_basis_vector(self, matrix: np.ndarray) -> int:
        for index in range(self.dimension):
            expected = np.zeros(self.dimension, dtype=np.uint8)
            expected[index] = 1
            if not np.array_equal(matrix[index], expected):
                return 1 << index
        raise AssertionError("non-identity matrix moves some basis vector")

    def _rebuild_orbit(self, level: _WordLevel) -> None:
        level.orbit = {level.base: (self.identity, self.identity, [])}
        queue = [level.base]
        while queue:
            point = queue.pop()
            element, _, word = level.orbit[point]
            for matrix, packed, gen_word in level.gens:
                image = _apply(packed, point)
                if image not in level.orbit:
                    if sum(len(lvl.orbit) for lvl in self.levels) >= self.node_budget:
                        raise RuntimeError("WordBSGS exceeded its node budget")
                    product = gf2_matmul(element, matrix)
                    new_word = word + gen_word
                    if len(new_word) > self._WORD_LIMIT:
                        raise RuntimeError("synthesis word grew past the safety limit")
                    level.orbit[image] = (product, gf2_inverse(product), new_word)
                    queue.append(image)

    def _sift(
        self, matrix: np.ndarray, word: list[int]
    ) -> tuple[np.ndarray | None, list[int], int]:
        """Reduce through the chain: returns (residue, residue word, level).

        Residue ``None`` means the element sifted to the identity; the
        returned word then satisfies ``product(word(u_L) .. word(u_1)) =
        element`` and is reconstructed by :meth:`factor`.
        """

        current = matrix
        current_word = list(word)
        for index, level in enumerate(self.levels):
            packed = _pack_rows(current)
            image = _apply(packed, level.base)
            entry = level.orbit.get(image)
            if entry is None:
                return current, current_word, index
            current = gf2_matmul(current, entry[1])
            current_word = current_word + self._inverse_word(entry[2])
        if np.array_equal(current, self.identity):
            return None, current_word, len(self.levels)
        return current, current_word, len(self.levels)

    def _add_strong_generator(self, matrix: np.ndarray, word: list[int], level_index: int) -> None:
        if level_index == len(self.levels):
            self.levels.append(_WordLevel(self._moved_basis_vector(matrix)))
        packed = _pack_rows(matrix)
        for level in self.levels[: level_index + 1]:
            level.gens.append((matrix, packed, word))
        for level in self.levels[: level_index + 1]:
            self._rebuild_orbit(level)

    def _build(self) -> None:
        for index, matrix in enumerate(self.generators):
            if np.array_equal(matrix, self.identity):
                continue
            residue, residue_word, level_index = self._sift(matrix, [index])
            if residue is not None:
                self._add_strong_generator(residue, residue_word, level_index)
        level_index = 0
        while level_index < len(self.levels):
            level = self.levels[level_index]
            restart = False
            for point, (point_element, _inv, point_word) in list(level.orbit.items()):
                for matrix, packed, gen_word in level.gens:
                    image = _apply(packed, point)
                    image_entry = level.orbit.get(image)
                    if image_entry is None:
                        self._rebuild_orbit(level)
                        restart = True
                        break
                    schreier = gf2_matmul(gf2_matmul(point_element, matrix), image_entry[1])
                    schreier_word = point_word + gen_word + self._inverse_word(image_entry[2])
                    residue, residue_word, residue_level = self._sift(schreier, schreier_word)
                    if residue is not None:
                        self._add_strong_generator(residue, residue_word, residue_level)
                        restart = True
                        break
                if restart:
                    break
            if restart:
                continue
            level_index += 1

    # -- public interface --------------------------------------------------

    def order(self) -> int:
        order = 1
        for level in self.levels:
            order *= len(level.orbit)
        return order

    def factor(self, target: np.ndarray) -> list[int] | None:
        """A word with left-to-right product ``target``, or ``None``.

        ``None`` is a *certified* non-membership: the chain passed its
        deterministic fixpoint, so sifting is a complete membership test.
        """

        current = (np.asarray(target, dtype=np.uint8) & 1).copy()
        if current.shape != (self.dimension, self.dimension):
            raise ValueError("target has the wrong shape")
        transversal_words: list[list[int]] = []
        for level in self.levels:
            packed = _pack_rows(current)
            image = _apply(packed, level.base)
            entry = level.orbit.get(image)
            if entry is None:
                return None
            transversal_words.append(entry[2])
            current = gf2_matmul(current, entry[1])
        if not np.array_equal(current, self.identity):
            return None
        word: list[int] = []
        for transversal_word in reversed(transversal_words):
            word.extend(transversal_word)
        return word


# ---------------------------------------------------------------------------
# The analysis object and driver
# ---------------------------------------------------------------------------


class OneBlockAnalysis:
    """Result of :func:`analyze_one_block`; ``to_dict`` follows the shared
    one-block data contract (see the module docstring)."""

    def __init__(
        self,
        code: CSSCode,
        generators: tuple[OneBlockGenerator, ...],
        *,
        involutions_used: int,
        strict_dim: int,
        logical_order: int | None,
        logical_order_exact: bool,
        is_full: bool | None,
        certification: str,
        detail: str,
        seconds: float,
        recognition: RecognitionReport | None = None,
    ):
        self.code = code
        self.generators = generators
        self.involutions_used = involutions_used
        self.strict_dim = strict_dim
        self.logical_order = logical_order
        self.logical_order_exact = logical_order_exact
        self.sp_target = symplectic_group_order(code.k)
        self.is_full = is_full
        self.certification = certification
        self.detail = detail
        self.seconds = seconds
        self.recognition = recognition
        self._bsgs: WordBSGS | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "generator_count": len(self.generators),
            "involutions_used": int(self.involutions_used),
            "strict_dim": int(self.strict_dim),
            "logical_order": self.logical_order,
            "logical_order_exact": bool(self.logical_order_exact),
            "sp_target": int(self.sp_target),
            "is_full": self.is_full,
            "certification": self.certification,
            "detail": self.detail,
            "seconds": float(round(self.seconds, 3)),
        }


def analyze_one_block(
    code: CSSCode,
    *,
    name: str | None = None,
    involution_cap: int = 16,
    time_budget_s: float = 120.0,
    closure_cap: int = 100_000,
    seed: int = 7,
    extra_taus: list[np.ndarray] | None = None,
    discover: bool = True,
) -> OneBlockAnalysis:
    """Certified one-block varying-partition Clifford analysis of ``code``.

    Collects the logical actions of every certified depth-one one-block layer
    (strict shears, per-involution fold layers and fold-Hadamards, Tanner
    automorphism permutation gates) and certifies the generated subgroup of
    ``Sp(2k, 2)`` by the tier ladder described in the module docstring.
    ``name`` (a registry key) unlocks the structural duality candidates of
    :mod:`.dualities`; ``involution_cap`` bounds how many involutions are
    analyzed; ``extra_taus`` allows caller-supplied involutions (certified
    like all others before use).
    """

    start = time.perf_counter()
    deadline = start + time_budget_s
    notes: list[str] = []

    strict = code.analyze_transversal()
    strict_dim = strict.a_z.dimension + strict.a_x.dimension

    records: list[OneBlockGenerator] = []
    seen: set[bytes] = set()

    def add(matrix: np.ndarray, kind: str, involution: int | None, label: str) -> None:
        matrix = (np.asarray(matrix, dtype=np.uint8) & 1).copy()
        if matrix.size == 0 or np.array_equal(matrix, np.eye(matrix.shape[0], dtype=np.uint8)):
            return
        if not is_symplectic(matrix, qubits=code.k):  # pragma: no cover - certified upstream
            raise AssertionError("internal error: non-symplectic logical action collected")
        key = matrix.tobytes()
        if key in seen:
            return
        seen.add(key)
        records.append(OneBlockGenerator(matrix, kind, involution, label))

    if strict.certified:
        for generator in strict.generators:
            if all(generator.certificate.values()):
                add(
                    generator.logical_symplectic,
                    f"strict-{generator.family}",
                    None,
                    "strict transversal shear",
                )
    else:  # pragma: no cover - strict analysis certifies on all repo codes
        notes.append("strict analysis failed certification; strict layers skipped")

    aut = None
    if analyze_automorphisms is not None:
        try:
            aut = analyze_automorphisms(code)
        except ImportError:  # pragma: no cover
            notes.append("python-igraph unavailable; automorphism gates skipped")

    involutions = _collect_involutions(
        code,
        name,
        aut,
        involution_cap=involution_cap,
        seed=seed,
        extra_taus=extra_taus,
        discover=discover,
    )
    # Only involutions that actually hand over a gate are counted: a matching
    # whose kernels are empty certifies vacuously (``all()`` of nothing), and
    # counting those would advertise contributing pairings the code lacks.
    contributing: set[int] = set()
    truncated = False
    for index, (label, tau) in enumerate(involutions):
        if time.perf_counter() > deadline:
            notes.append(f"time budget hit during collection after {index} involutions")
            truncated = True
            break
        matching = analyze_matching(code, tau)
        if not matching.certified:
            continue
        before = len(records)
        for generator in matching.generators:
            if all(generator.certificate.values()):
                add(
                    generator.logical_symplectic,
                    f"fold-{generator.family}",
                    index,
                    f"fold layer on {label}",
                )
        fold_h = matching.fold_hadamard
        if fold_h is not None and all(fold_h.certificate.values()):
            add(fold_h.logical_symplectic, "fold-H", index, f"fold-Hadamard on {label}")
        if len(records) > before:
            contributing.add(index)

    if aut is not None and aut.certified:
        for generator in aut.generators:
            if all(generator.certificate.values()):
                add(generator.logical_symplectic, "perm", None, "Tanner automorphism")

    # Structural shift automorphisms: quasi-cyclic block shifts certified by
    # rank identities on the row SPACES, which the Tanner route (row-SET
    # scoped) misses whenever the recorded generators are not shift-closed —
    # precisely the failure observed on external census codes.
    if discover and describe_permutation is not None:
        for perm in structural_permutations(code):
            record = describe_permutation(code, perm)
            if all(record.certificate.values()):
                add(record.logical_symplectic, "perm", None, "structural shift automorphism")

    # Characteristic-set (row-space) permutation automorphisms: the
    # Leon-style invariant-set reduction through BLISS.  Enumeration is
    # 2^rank, so this stays behind rank/size caps; within them it is the
    # exact CSS permutation automorphism group, the capability every other
    # open tool defers to MAGMA or GAP for.
    if (
        discover
        and analyze_codeword_automorphisms is not None
        and max(code.c_x.shape[0], code.c_z.shape[0]) <= _CODEWORD_AUT_RANK_CAP
        and code.n <= _CODEWORD_AUT_N_CAP
        and time.perf_counter() < deadline
    ):
        try:
            codeword_group = analyze_codeword_automorphisms(code)
        except (ImportError, ValueError):
            codeword_group = None
        if codeword_group is not None:
            for generator in codeword_group.generators:
                if all(generator.certificate.values()):
                    add(generator.logical_symplectic, "perm", None, "codeword automorphism")

    generators = tuple(records)
    matrices = [record.matrix for record in generators]
    sp_target = symplectic_group_order(code.k)
    recognition: RecognitionReport | None = None

    def finish(
        logical_order, exact, is_full, certification, message
    ) -> OneBlockAnalysis:
        # ``is_full`` is one-sided by construction.  True is a certificate: we
        # exhibited certified layers whose logical images generate Sp(2k, 2).
        # False is NOT: the matchings a code admits cannot be enumerated (there
        # are exponentially many involutions of n qubits, and this engine
        # samples them), so a group short of the target only says "the layers
        # found so far do not suffice" — never "the code cannot".  Publishing
        # that as a negative would be exactly the failed-search-dressed-as-a-
        # proof this project refuses to ship, so it is reported as undecided
        # with an exact order for the collected generating set.
        if is_full is False:
            is_full = None
            message = (
                f"{message}; short of |Sp({2 * code.k},2)| for the layers found — "
                "a lower bound on the code's one-block group, not a negative verdict"
            )
        detail = "; ".join([message] + notes) if notes else message
        if truncated:
            # A deadline-truncated collection saw only part of the code's
            # layers: the group it found is a subgroup of the real one, so the
            # order is a lower bound however exactly it was computed, and a
            # not-full verdict would be unsound.
            return OneBlockAnalysis(
                code,
                generators,
                involutions_used=len(contributing),
                strict_dim=strict_dim,
                logical_order=logical_order,
                logical_order_exact=False,
                is_full=True if is_full else None,
                certification="lower-bound",
                detail=detail,
                seconds=time.perf_counter() - start,
                recognition=recognition,
            )
        return OneBlockAnalysis(
            code,
            generators,
            involutions_used=len(contributing),
            strict_dim=strict_dim,
            logical_order=logical_order,
            logical_order_exact=exact,
            is_full=is_full,
            certification=certification,
            detail=detail,
            seconds=time.perf_counter() - start,
            recognition=recognition,
        )

    if code.k == 0 or not matrices:
        order = 1
        return finish(
            order,
            True,
            order == sp_target,
            "closure",
            "no nontrivial certified generators" if code.k else "k = 0: trivial target",
        )

    if time.perf_counter() > deadline:
        return finish(None, False, None, "skipped", "time budget exhausted before certification")

    # Tier order matters more than any single budget.  Enumeration costs one
    # matrix product per (element, generator) pair, so a group of a few
    # million with fifty generators is hundreds of millions of numpy calls —
    # grid-4x6 (k = 8) spent over half an hour there — while the stabilizer
    # chain reaches the same exact order in polynomial time (gross, order
    # 11,059,200 at k = 12: 3.9 s).  So where the chain is viable at all, run
    # it FIRST and let enumeration be the fallback, not the gate.
    #
    # Cost is driven by the GENERATOR COUNT, not by k: the chain processes one
    # Schreier generator per (orbit point, generator), so gross (k = 12, nine
    # generators) certifies in three seconds while grid-4x6 (k = 8, but 270
    # generators after sweeping 48 matchings) does not finish at any budget.
    # Two consequences, both sound:
    #   * fullness is monotone — if a SUBSET generates Sp(2k,2) then so does
    #     the whole certified set, since every generator is symplectic — so
    #     subsets are tried first and a hit is a genuine certificate;
    #   * the exact order of a non-full group is never published (the column
    #     reports FULL or a lower bound), so the expensive all-generator chain
    #     is reserved for sets small enough to afford it.
    if code.k <= _CHAIN_CHEAP_K and time.perf_counter() < deadline:
        for size in (6, 10, 16):
            if size >= len(matrices):
                break
            if time.perf_counter() > deadline:
                break
            subset_order = schreier_sims_order(
                matrices[:size], node_budget=_SCHREIER_TIGHT_BUDGET
            )
            if subset_order == sp_target:
                return finish(
                    sp_target,
                    True,
                    True,
                    "exact-order",
                    f"Schreier-Sims: a {size}-generator subset already reaches "
                    f"|Sp({2 * code.k},2)|, so the full certified set does too",
                )
        if len(matrices) <= _CHAIN_GENERATOR_LIMIT and time.perf_counter() < deadline:
            chain_first = schreier_sims_order(matrices, node_budget=_SCHREIER_NODE_BUDGET)
            if chain_first is not None:
                return finish(
                    chain_first,
                    True,
                    chain_first == sp_target,
                    "exact-order",
                    "Schreier-Sims exact order over all generators",
                )

    # Tier: recognition-first for larger k.  The chain's cost grows with the
    # ORBIT size (up to 2^{2k} points per level), so past k = 6 it is the
    # recognition route — a transvection witness plus certified irreducibility
    # and the absence of an invariant quadratic form — that decides fullness
    # quickly (rm64, k = 20: 5.4 s).  Enumeration and the all-generator chain
    # stay below it as the ways to pin an order when fullness does not hold.
    if code.k > _CHAIN_CHEAP_K and time.perf_counter() < deadline:
        recognition = recognize_full_symplectic(
            matrices,
            code.k,
            seed=seed,
            time_budget_s=max(1.0, min(30.0, deadline - time.perf_counter())),
        )
        if recognition.verdict == "full":
            return finish(
                sp_target,
                True,
                True,
                "recognition",
                "McLaughlin transvection recognition certified fullness: " + recognition.detail,
            )
        if (
            len(matrices) <= _CHAIN_SPARSE_LIMIT
            and code.k <= _EXACT_ORDER_K_LIMIT
            and time.perf_counter() < deadline
        ):
            # Few generators: the chain is affordable and pins the exact order
            # of a proper subgroup (gross, nine generators at k = 12: 3.7 s).
            sparse_chain = schreier_sims_order(matrices, node_budget=_SCHREIER_NODE_BUDGET)
            if sparse_chain is not None:
                return finish(
                    sparse_chain,
                    True,
                    sparse_chain == sp_target,
                    "exact-order",
                    "Schreier-Sims exact order over all generators (sparse set)",
                )

    # Tier: closure — exact at any k when the group is small enough to list.
    effective_cap = closure_cap if code.k <= _CLOSURE_DENSE_K_LIMIT else min(
        closure_cap, _CLOSURE_TIGHT_CAP
    )
    effective_cap = _memory_safe_closure_cap(code.k, effective_cap)
    # Enumeration costs one matrix product per (element, generator) pair, so a
    # wide generating set is as expensive as a large cap: wzl20 sweeps 233
    # certified layers, where a 100k cap would mean 23M products.  Since this
    # tier only supplies a lower bound once recognition has declined to
    # certify, bound the WORK rather than the element count.
    effective_cap = max(64, min(effective_cap, _CLOSURE_WORK_BUDGET // max(1, len(matrices))))
    closure = generated_group_order(matrices, cap=effective_cap)
    if closure.exact:
        if code.k <= _EXACT_ORDER_K_LIMIT and closure.order <= 50_000:
            chain = schreier_sims_order(matrices)
            if chain is not None and chain != closure.order:
                raise AssertionError("internal error: closure and stabilizer chain disagree")
        return finish(
            closure.order,
            True,
            closure.order == sp_target,
            "closure",
            f"closure enumeration completed with {closure.order} elements",
        )

    # Tier: exact-order — deterministic Schreier-Sims for moderate k.
    #
    # The chain cannot be interrupted by the caller's deadline: it runs to
    # its own ``node_budget`` and only then returns ``None``.  The default
    # budget of two million transversal points is minutes of work per call
    # on a group the size of Sp(20,2) — a census run spent an hour inside a
    # single k = 10 code before this was bounded.  So the budget, not the
    # attempt, is what scales: generous where the chain is known to be cheap
    # (k <= 8, or a closure that already completed and so proved the group
    # small), tight elsewhere, where an over-budget ``None`` costs little and
    # simply hands the code to the recognition tier.
    # Gate on EVIDENCE, not on k.  A completed closure is proof the group is
    # small, so the chain will be quick; k alone proves nothing — grid-4x6 has
    # k = 8 and a group large enough that the full budget ran for 35 minutes
    # inside one code.  Everything else gets the tight budget, where an
    # over-budget ``None`` is cheap and simply defers to recognition.
    cheap_chain = closure.exact or code.k <= _SCHREIER_TRIVIAL_K
    node_budget = _SCHREIER_NODE_BUDGET if cheap_chain else _SCHREIER_TIGHT_BUDGET
    if code.k <= _EXACT_ORDER_K_LIMIT and time.perf_counter() < deadline:
        chain: int | None = None
        via = "stabilizer chain over all generators"
        if len(matrices) > 12:
            for size in (8, 12):
                subset_order = schreier_sims_order(matrices[:size], node_budget=node_budget)
                if subset_order == sp_target:
                    # A subgroup already reaches |Sp(2k,2)|; since every
                    # generator is certified symplectic, G <= Sp(2k,2), so
                    # G = Sp(2k,2) without processing the rest.
                    chain = subset_order
                    via = f"stabilizer chain over a {size}-generator subset (already full)"
                    break
        if chain is None:
            chain = schreier_sims_order(matrices, node_budget=node_budget)
        if chain is not None:
            return finish(
                chain,
                True,
                chain == sp_target,
                "exact-order",
                f"Schreier-Sims exact order via {via}",
            )

    # Tier: recognition — McLaughlin route for large k.
    if time.perf_counter() < deadline:
        recognition = recognize_full_symplectic(
            matrices,
            code.k,
            seed=seed,
            time_budget_s=max(1.0, deadline - time.perf_counter()),
        )
        if recognition.verdict == "full":
            return finish(
                sp_target,
                True,
                True,
                "recognition",
                "McLaughlin transvection recognition certified fullness: " + recognition.detail,
            )
        if recognition.verdict == "not-full":
            return finish(
                closure.lower_bound,
                False,
                False,
                "recognition",
                "recognition certified G != Sp(2k,2): " + recognition.detail,
            )
        notes.append("recognition inconclusive: " + recognition.detail)

    floor = closure.lower_bound
    if discover:
        # Discovery can widen the certified set past what any exact tier
        # affords, leaving only this truncated floor — which may sit BELOW
        # the order the LEGACY set alone certifies exactly (bb72: floor
        # 9,804 against a certified 35,715).  One discovery-free rerun
        # recovers that certificate; its order bounds the wider group from
        # below because the legacy generators are a subset of the full set.
        legacy = analyze_one_block(
            code,
            name=name,
            involution_cap=involution_cap,
            time_budget_s=max(1.0, deadline - time.perf_counter()),
            closure_cap=closure_cap,
            seed=seed,
            extra_taus=extra_taus,
            discover=False,
        )
        if legacy.logical_order is not None and legacy.logical_order > (floor or 0):
            floor = legacy.logical_order
            notes.append(
                f"floor raised to the legacy-set verdict {legacy.logical_order} "
                f"({legacy.certification}): its generators are a subset of this run's"
            )
    return finish(
        floor,
        False,
        None,
        "lower-bound",
        f"closure truncated at cap {effective_cap}; order >= {floor} "
        "— a partial-enumeration floor, so it can sit BELOW an order another "
        "column certifies exactly (the fold group is a subgroup of this one): "
        "read it as 'at least', never as a measurement of the group",
    )


def single_matching_fullness(
    code: CSSCode,
    name: str | None = None,
    *,
    involution_cap: int = 16,
    seed: int = 7,
    closure_cap: int = 4_000_000,
    time_budget_s: float = 300.0,
) -> dict[str, Any]:
    """Does *one* matching already suffice, or is varying them necessary?

    :func:`analyze_one_block` answers whether the union of every certified
    depth-one layer reaches ``Sp(2k, 2)``, but not how few matchings that
    took — and the distinction is the whole point of the
    Chakraborty-Gottesman discussion.  This routine tests each certified
    matching *on its own*: strict layers plus Tanner automorphism gates plus
    the fold layers of that single involution.

    A ``True`` verdict does not contradict arXiv:2602.13395.  That theorem
    bounds gadget sets built on ONE fixed partition, which are closed under
    composition; adding automorphism gates that fail to normalize the
    involution conjugates its fold layers onto *other* matchings, so the
    generated set is not of fixed partition.  ``normalized`` records, for the
    witnessing involution, whether each automorphism generator normalizes it
    — an all-``True`` list would be the case that genuinely needs explaining.

    Returns ``single_matching_full`` (``None`` when nothing could be decided
    inside the budget), the number of matchings tried, and the witness label.
    """

    deadline = time.perf_counter() + time_budget_s
    strict = code.analyze_transversal()
    strict_gens = [
        g.logical_symplectic
        for g in strict.generators
        if all(g.certificate.values()) and not g.is_logical_identity
    ] if strict.certified else []

    aut = None
    aut_gens: list[np.ndarray] = []
    if analyze_automorphisms is not None:
        try:
            aut = analyze_automorphisms(code)
            if aut.certified:
                aut_gens = [
                    g.logical_symplectic for g in aut.generators if all(g.certificate.values())
                ]
        except ImportError:  # pragma: no cover - optional dependency
            aut = None

    target = symplectic_group_order(code.k)
    base = strict_gens + aut_gens
    if base and generated_group_order(base, cap=closure_cap).order == target:
        return {
            "single_matching_full": True,
            "matchings_tried_singly": 0,
            "witness": "strict + automorphisms alone",
            "normalized": None,
        }

    involutions = _collect_involutions(
        code, name, aut, involution_cap=involution_cap, seed=seed, extra_taus=None
    )
    tried = 0
    for label, tau in involutions:
        if time.perf_counter() > deadline:
            return {
                "single_matching_full": None,
                "matchings_tried_singly": tried,
                "witness": "time budget exhausted",
                "normalized": None,
            }
        matching = analyze_matching(code, tau)
        if not matching.certified:
            continue
        fold = [
            g.logical_symplectic
            for g in matching.generators
            if all(g.certificate.values())
        ]
        if matching.fold_hadamard is not None and all(matching.fold_hadamard.certificate.values()):
            fold.append(matching.fold_hadamard.logical_symplectic)
        if not fold:
            continue
        tried += 1
        result = generated_group_order(base + fold, cap=closure_cap)
        if result.exact and result.order == target:
            normalized = None
            if aut is not None:
                tau_array = np.asarray(tau, dtype=int)
                normalized = []
                for generator in aut.generators:
                    permutation = np.asarray(generator.qubit_permutation, dtype=int)
                    conjugate = np.empty_like(tau_array)
                    for qubit in range(tau_array.size):
                        conjugate[permutation[qubit]] = permutation[tau_array[qubit]]
                    normalized.append(bool(np.array_equal(conjugate, tau_array)))
            return {
                "single_matching_full": True,
                "matchings_tried_singly": tried,
                "witness": label,
                "normalized": normalized,
            }
    return {
        "single_matching_full": False,
        "matchings_tried_singly": tried,
        "witness": None,
        "normalized": None,
    }


# ---------------------------------------------------------------------------
# Synthesis
# ---------------------------------------------------------------------------


def factor_target(analysis: OneBlockAnalysis, target: np.ndarray) -> dict[str, Any] | None:
    """Factor ``target`` (a ``2k x 2k`` logical symplectic matrix) into an
    explicit word in the collected depth-one layers, or return ``None``.

    The word-tracking Schreier-Sims chain is cross-checked against the
    independent order engine before use (an internal error is raised on any
    mismatch), and the returned word is verified by recomposition, so a
    reported factorization is always correct and ``None`` is a certified
    non-membership.  Words may be long; ``length`` records the cost honestly.
    """

    code = analysis.code
    if code.k > 8:
        raise ValueError("factor_target supports k <= 8")
    target = (np.asarray(target, dtype=np.uint8) & 1).copy()
    if target.shape != (2 * code.k, 2 * code.k):
        raise ValueError(f"target must be {2 * code.k} x {2 * code.k}")
    if not is_symplectic(target, qubits=code.k):
        raise ValueError("target must be symplectic")
    if not analysis.generators:
        if np.array_equal(target, np.eye(2 * code.k, dtype=np.uint8)):
            return {"found": True, "word": [], "length": 0, "provenance": [], "verified": True}
        return None

    if analysis._bsgs is None:
        matrices = [record.matrix for record in analysis.generators]
        bsgs = WordBSGS(matrices)
        independent = schreier_sims_order(matrices)
        if independent is not None and bsgs.order() != independent:
            raise AssertionError("internal error: word chain and order engine disagree")
        if analysis.logical_order_exact and analysis.logical_order is not None:
            if bsgs.order() != analysis.logical_order:
                raise AssertionError("internal error: word chain disagrees with certified order")
        analysis._bsgs = bsgs
    bsgs = analysis._bsgs

    word = bsgs.factor(target)
    if word is None:
        return None
    recomposed = bsgs.word_product(word)
    if not np.array_equal(recomposed, target):
        raise AssertionError("internal error: recomposition of the synthesis word failed")
    return {
        "found": True,
        "word": word,
        "length": len(word),
        "provenance": [analysis.generators[index].provenance for index in word],
        "verified": True,
    }
