"""Strict-transversal Clifford groups of general (non-CSS) stabilizer codes.

A strict-transversal Clifford mod Pauli is a block-diagonal symplectic
matrix ``M = diag(M_1, ..., M_n)`` with every ``M_i in SL(2,2)`` (the six
single-qubit Cliffords mod Pauli) whose column action preserves the
stabilizer row space.  The key to solving this exactly without search is a
Van den Nest-style linearization (cf. van den Nest, Dehaene, De Moor,
PRA 70, 034302 (2004)): drop invertibility and consider

    ``A = { M block-diagonal 2x2 over F_2 : H M \\subseteq rowspan(H) }``.

``A`` is a *linear subspace* (indeed a matrix algebra: if ``HM = RH`` and
``HM' = R'H`` then ``HMM' = R R' H``), computed by one GF(2) kernel.  The
strict-transversal group is exactly the subset of ``A`` whose blocks all
have determinant one — a condition checked per element, with the
enumeration bounded by ``2^dim(A)`` (small for any code with few local
symmetries; reported honestly when the cap is exceeded).

For CSS codes this group provably coincides with the group generated by
the diagonal ``A_Z``/``A_X`` shear families (Albert, arXiv:2608.05688),
which gives an independent cross-check; the point of this module is that
non-CSS codes such as the ``[[5,1,3]]`` perfect code are now in scope.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

from .gf2 import (
    BinaryMatrix,
    as_binary_matrix,
    nullspace,
    quotient_complement,
    reduce_rows,
    row_basis,
    rref,
    symplectic_product,
)
from .matching import logical_group_summary

#: The six elements of SL(2,2) as (a, b, c, d) with M = [[a, b], [c, d]].
_SL22 = [
    (1, 0, 0, 1),  # I
    (1, 1, 0, 1),  # S      (X -> Y)
    (1, 0, 1, 1),  # sqrtX  (Z -> Y)
    (0, 1, 1, 0),  # H      (X <-> Z)
    (1, 1, 1, 0),  # HS
    (0, 1, 1, 1),  # SH
]

_ENUMERATION_DIM_CAP = 24


def symplectic_gram_schmidt(
    rows: BinaryMatrix, qubits: int
) -> tuple[BinaryMatrix, BinaryMatrix]:
    """Split rows spanning a non-degenerate symplectic space into dual pairs
    ``(a_i, b_i)`` with ``<a_i, b_j> = delta_ij`` and all other products 0."""

    remaining = [row.copy() for row in rows]
    first: list[BinaryMatrix] = []
    second: list[BinaryMatrix] = []
    while remaining:
        a = remaining.pop(0)
        partner_index = next(
            (
                i
                for i, r in enumerate(remaining)
                if symplectic_product(a, r, qubits=qubits)[0, 0]
            ),
            None,
        )
        if partner_index is None:
            raise ValueError("symplectic form is degenerate on the given rows")
        b = remaining.pop(partner_index)
        cleaned = []
        for r in remaining:
            r = r ^ (symplectic_product(r, b, qubits=qubits)[0, 0] * a)
            r = r ^ (symplectic_product(r, a, qubits=qubits)[0, 0] * b)
            cleaned.append(r)
        remaining = cleaned
        first.append(a)
        second.append(b)
    k = len(first)
    width = rows.shape[1] if k else 2 * qubits
    return (
        np.asarray(first, dtype=np.uint8).reshape(k, width),
        np.asarray(second, dtype=np.uint8).reshape(k, width),
    )


class StabilizerCode:
    """A general stabilizer code given by symplectic rows ``(X | Z)``."""

    def __init__(self, h: object):
        matrix = as_binary_matrix(h)
        if matrix.shape[1] % 2 != 0:
            raise ValueError("stabilizer rows must have even width (X | Z)")
        self.n = matrix.shape[1] // 2
        if symplectic_product(matrix, matrix, qubits=self.n).any():
            raise ValueError("stabilizer generators do not commute")
        self.h = row_basis(matrix, ncols=2 * self.n)
        self.rank = self.h.shape[0]
        self.k = self.n - self.rank
        self._h_rref = rref(self.h)

        # normalizer = symplectic kernel of h; logicals complete h inside it
        swapped = np.hstack([self.h[:, self.n :], self.h[:, : self.n]])
        normalizer = nullspace(swapped)
        representatives = quotient_complement(normalizer, self.h)
        if representatives.shape[0] != 2 * self.k:
            raise AssertionError("internal error: logical space has wrong dimension")
        if self.k:
            a_rows, b_rows = symplectic_gram_schmidt(representatives, self.n)
            self.logical = np.vstack([a_rows, b_rows])
        else:
            self.logical = np.zeros((0, 2 * self.n), dtype=np.uint8)


def _block_action_matrix(entries: np.ndarray, n: int) -> BinaryMatrix:
    """The ``2n x 2n`` symplectic matrix of per-qubit blocks ``(a,b,c,d)``
    in the ``(x_0..x_{n-1} | z_0..z_{n-1})`` row-vector convention."""

    matrix = np.zeros((2 * n, 2 * n), dtype=np.uint8)
    a, b, c, d = entries[0::4], entries[1::4], entries[2::4], entries[3::4]
    idx = np.arange(n)
    matrix[idx, idx] = a
    matrix[idx, n + idx] = b
    matrix[n + idx, idx] = c
    matrix[n + idx, n + idx] = d
    return matrix


def local_clifford_algebra(code: StabilizerCode) -> BinaryMatrix:
    """Basis of ``{M block-diagonal : H M \\subseteq rowspan(H)}`` over F_2.

    Unknowns are the ``4n`` block entries ``(a_i, b_i, c_i, d_i)``.  A row
    ``s = (x|z)`` maps to ``s'`` with ``x'_i = a_i x_i + c_i z_i`` and
    ``z'_i = b_i x_i + d_i z_i``; membership ``s' in rowspan(H)`` is tested
    against ``N = rowspan(H)^\\perp``, giving linear constraints.  Constraints
    for ``s`` only touch qubits in its support, so ``N`` is restricted there
    first (the LDPC-friendly construction of the CSS solver).
    """

    n = code.n
    perp = nullspace(code.h)
    constraints: list[np.ndarray] = []
    for s in code.h:
        x, z = s[:n], s[n:]
        support = np.flatnonzero(x | z)
        if support.size == 0:
            continue
        columns = np.concatenate([support, n + support])
        local = row_basis(perp[:, columns], ncols=2 * support.size)
        for w in local:
            wx = np.zeros(n, dtype=np.uint8)
            wz = np.zeros(n, dtype=np.uint8)
            wx[support] = w[: support.size]
            wz[support] = w[support.size :]
            row = np.zeros(4 * n, dtype=np.uint8)
            row[0::4] = wx & x
            row[1::4] = wz & x
            row[2::4] = wx & z
            row[3::4] = wz & z
            if row.any():
                constraints.append(row)
    if constraints:
        constraint_matrix = row_basis(np.asarray(constraints, dtype=np.uint8))
    else:
        constraint_matrix = np.zeros((0, 4 * n), dtype=np.uint8)
    return nullspace(constraint_matrix)


@dataclass(frozen=True)
class LocalCliffordGenerator:
    blocks: tuple[tuple[int, int, int, int], ...]  # per-qubit (a, b, c, d)
    logical_symplectic: BinaryMatrix
    certificate: dict[str, bool]

    @property
    def is_logical_identity(self) -> bool:
        return np.array_equal(
            self.logical_symplectic,
            np.eye(self.logical_symplectic.shape[0], dtype=np.uint8),
        )

    @property
    def gate_names(self) -> tuple[str, ...]:
        names = {m: name for m, name in zip(_SL22, ("I", "S", "sqrtX", "H", "HS", "SH"))}
        return tuple(names[block] for block in self.blocks)


class LocalCliffordAnalysis:
    """The complete strict-transversal Clifford group of a stabilizer code."""

    def __init__(self, code: StabilizerCode, *, dim_cap: int = _ENUMERATION_DIM_CAP):
        self.code = code
        self.algebra = local_clifford_algebra(code)
        dimension = self.algebra.shape[0]
        self.enumeration_complete = dimension <= dim_cap
        self.elements: list[np.ndarray] = []
        if self.enumeration_complete:
            n = code.n
            for mask in range(1 << dimension):
                entries = np.zeros(4 * n, dtype=np.uint8)
                for bit in range(dimension):
                    if (mask >> bit) & 1:
                        entries ^= self.algebra[bit]
                a, b, c, d = entries[0::4], entries[1::4], entries[2::4], entries[3::4]
                determinant = (a & d) ^ (b & c)
                if determinant.all():
                    self.elements.append(entries)
        self.generators = tuple(
            self._describe(entries)
            for entries in self.elements
            if entries.any() and not self._is_identity(entries)
        )

    @staticmethod
    def _is_identity(entries: np.ndarray) -> bool:
        return bool(
            entries[0::4].all()
            and entries[3::4].all()
            and not entries[1::4].any()
            and not entries[2::4].any()
        )

    def _describe(self, entries: np.ndarray) -> LocalCliffordGenerator:
        code = self.code
        n = code.n
        matrix = _block_action_matrix(entries, n)
        stab_image = (code.h.astype(np.int64) @ matrix.astype(np.int64) % 2).astype(np.uint8)
        preserved = not reduce_rows(stab_image, *code._h_rref).any()
        if code.k:
            images = (code.logical.astype(np.int64) @ matrix.astype(np.int64) % 2).astype(
                np.uint8
            )
            x_coeff = symplectic_product(images, code.logical[code.k :], qubits=n)
            z_coeff = symplectic_product(images, code.logical[: code.k], qubits=n)
            logical = np.hstack([x_coeff, z_coeff]).astype(np.uint8)
            residue = (
                images
                ^ (logical.astype(np.int64) @ code.logical.astype(np.int64) % 2).astype(
                    np.uint8
                )
            ) & 1
            residue_ok = not reduce_rows(residue, *code._h_rref).any()
        else:
            logical = np.zeros((0, 0), dtype=np.uint8)
            residue_ok = True
        blocks = tuple(
            (int(entries[4 * i]), int(entries[4 * i + 1]), int(entries[4 * i + 2]), int(entries[4 * i + 3]))
            for i in range(n)
        )
        certificate = {
            "stabilizer_preserved": bool(preserved),
            "all_blocks_invertible": True,
            "logical_residue_in_stabilizer": bool(residue_ok),
        }
        return LocalCliffordGenerator(
            blocks=blocks, logical_symplectic=logical, certificate=certificate
        )

    @property
    def group_order(self) -> int | None:
        """Order of the physical transversal group mod Paulis (identity included)."""

        if not self.enumeration_complete:
            return None
        return len(self.elements)

    @property
    def certified(self) -> bool:
        return all(all(g.certificate.values()) for g in self.generators)

    def to_dict(self) -> dict[str, Any]:
        nontrivial = [
            g.logical_symplectic for g in self.generators if not g.is_logical_identity
        ]
        return {
            "algebra_dimension": int(self.algebra.shape[0]),
            "enumeration_complete": bool(self.enumeration_complete),
            "physical_group_order": self.group_order,
            "nontrivial_logical_generators": len(nontrivial),
            "logical_group": logical_group_summary(nontrivial, self.code.k),
            "certified": self.certified,
        }


def analyze_local_clifford(code: StabilizerCode) -> LocalCliffordAnalysis:
    """The complete strict-transversal Clifford group, CSS or not."""

    return LocalCliffordAnalysis(code)


def five_qubit_code() -> StabilizerCode:
    """The ``[[5,1,3]]`` perfect code — the canonical non-CSS example."""

    rows = np.zeros((4, 10), dtype=np.uint8)
    paulis = ["XZZXI", "IXZZX", "XIXZZ", "ZXIXZ"]
    for r, word in enumerate(paulis):
        for q, letter in enumerate(word):
            if letter in ("X", "Y"):
                rows[r, q] = 1
            if letter in ("Z", "Y"):
                rows[r, 5 + q] = 1
    return StabilizerCode(rows)
